"""Vocabulaire de sûreté de 35 langues supplémentaires (v0.25).

Jusqu'en v0.24, le tri connaissait 21 langues (fr, en, es, pt, de, it, nl, pl, tr, ru, uk, ar, he, id, th, zh, bn,
fa, ur, am, so). Les médias de référence des pays nordiques, d'Europe centrale, des Balkans, du Caucase, d'Asie
(Japon, Corée, Viêt Nam, Inde…) et d'Afrique de l'Est étaient donc interrogés avec des mots-clés anglais, et leurs
titres en langue locale n'étaient pas reconnus.

Pour chaque langue :
- search   : requête Google News (connecteurs gnews et outlets) ;
- cat      : mots par catégorie d'événement (racines : ≥ 5 lettres = début de mot, ≤ 4 lettres = mot entier ;
             écritures sans espaces – japonais, coréen, birman, khmer – : sous-chaîne) ;
- dead     : morts et blessés (bilans, « fait récent », violence) ;
- arrest   : arrestations (titres de contexte) ;
- judicial : procédures judiciaires (écartées) ;
- noise    : sport et divertissement (écartés).
Les mots courts ambigus d'une langue à l'autre ont été écartés (ex. « hari » = attaque en haoussa mais « jour » en
indonésien ; « sud » = tribunal en ouzbek mais « sud » en français ; « vita » = guerre en swahili mais « vie » en
italien ; « rån »/« ran » ; « bom » ; « kama »).
"""

LANGS = {
    # ---------------------------------------------------------------- Europe du Nord
    "sv": {
        "search": "attack OR explosion OR skottlossning OR demonstration OR upplopp OR kidnappning OR sammandrabbningar OR översvämning OR jordbävning OR undantagstillstånd",
        "cat": {
            "terrorism": ["terrordåd", "terrorattack", "terrorist"],
            "attack": ["angrepp", "sprängning", "skottlossning", "skjuten", "sköts ihjäl", "knivhugg", "knivattack", "kidnappning",
                       "kidnappad", "gisslan", "bombdåd", "mordbrand", "detonation"],
            "armed_conflict": ["flyganfall", "robotanfall", "drönarattack", "strider", "beskjutning"],
            "unrest": ["demonstration", "upplopp", "kravaller", "strejk", "tårgas"],
            "political": ["undantagstillstånd", "statskupp", "krigslagar"],
            "crime": ["dödsskjutning", "gängkriminal", "gängvåld", "narkotika", "utpressning", "väpnat rån", "rånare"],
            "cyber": ["cyberattack", "it-attack", "hackerattack", "dataintrång"],
            "infrastructure": ["strömavbrott", "urspårning", "spårade ur", "gasexplosion"],
            "health": ["utbrott av", "epidemi", "mässling"],
            "earthquake": ["jordbävning", "jordskalv"],
            "flood": ["översvämning", "skyfall"],
            "cyclone": ["tyfon", "cyklon"],
            "storm": ["oväder", "åskväder", "hagelstorm", "stormbyar"],
            "wildfire": ["skogsbrand", "gräsbrand"],
            "volcano": ["vulkanutbrott"],
            "landslide": ["jordskred", "lerskred"],
            "extreme_temp": ["värmebölja", "köldknäpp"],
            "drought": ["torka"],
        },
        "dead": ["döda", "dödad", "dödades", "omkom", "omkommit", "skadade", "skadad", "dödsoffer"],
        "arrest": ["gripen", "gripna", "greps", "anhållen", "häktad", "häktades"],
        "judicial": ["rättegång", "döms", "dömd", "dömdes", "åtalad", "åtal mot"],
        "noise": ["fotboll", "allsvenskan", "landskamp", "melodifestival"],
    },
    "no": {
        "search": "angrep OR eksplosjon OR skyting OR demonstrasjon OR opptøyer OR kidnapping OR sammenstøt OR flom OR jordskjelv OR unntakstilstand",
        "cat": {
            "terrorism": ["terrorangrep", "terrorist"],
            "attack": ["angrep", "eksplosjon", "skyting", "skutt", "knivstikking", "knivstukket", "kidnappet", "gissel", "bombe",
                       "ildspåsettelse"],
            "armed_conflict": ["luftangrep", "rakettangrep", "droneangrep", "kampene", "beskytning"],
            "unrest": ["demonstrasjon", "opptøyer", "streik", "tåregass"],
            "political": ["unntakstilstand", "statskupp"],
            "crime": ["drapet", "drept", "ranet", "gjengkriminal", "narkotika", "utpressing"],
            "cyber": ["dataangrep", "cyberangrep", "hackerangrep", "løsepengevirus"],
            "infrastructure": ["strømbrudd", "avsporing", "gasseksplosjon"],
            "health": ["utbrudd", "epidemi", "meslinger"],
            "earthquake": ["jordskjelv"],
            "flood": ["flommen", "flom", "oversvømmelse"],
            "cyclone": ["tyfon", "syklon"],
            "storm": ["uvær", "ekstremvær", "stormen"],
            "wildfire": ["skogbrann", "lyngbrann"],
            "landslide": ["jordskred", "leirskred", "steinskred"],
            "extreme_temp": ["hetebølge"],
            "drought": ["tørke"],
        },
        "dead": ["døde", "drept", "omkom", "omkommet", "skadd", "skadet"],
        "arrest": ["pågrepet", "arrestert", "siktet"],
        "judicial": ["rettssak", "dømt", "tiltalt", "lagmannsrett"],
        "noise": ["fotball", "eliteserien", "fotballkamp"],
    },
    "da": {
        "search": "angreb OR eksplosion OR skyderi OR demonstration OR uroligheder OR kidnapning OR sammenstød OR oversvømmelse OR jordskælv OR undtagelsestilstand",
        "cat": {
            "terrorism": ["terrorangreb", "terrorist"],
            "attack": ["angreb", "eksplosion", "skyderi", "skudt", "knivstik", "knivstukket", "kidnapning", "gidsel", "bombe",
                       "ildspåsættelse"],
            "armed_conflict": ["luftangreb", "missilangreb", "droneangreb", "kampene", "beskydning"],
            "unrest": ["demonstration", "uroligheder", "optøjer", "strejke", "tåregas"],
            "political": ["undtagelsestilstand", "statskup"],
            "crime": ["drabet", "dræbt", "røveri", "bandekonflikt", "narko", "afpresning"],
            "cyber": ["cyberangreb", "hackerangreb"],
            "infrastructure": ["strømafbrydelse", "strømsvigt", "afsporing", "gaseksplosion"],
            "health": ["udbrud", "epidemi", "mæslinger"],
            "earthquake": ["jordskælv"],
            "flood": ["oversvømmelse", "skybrud", "stormflod"],
            "cyclone": ["tyfon", "cyklon"],
            "storm": ["uvejr", "stormen"],
            "wildfire": ["skovbrand", "naturbrand"],
            "landslide": ["jordskred"],
            "extreme_temp": ["hedebølge"],
            "drought": ["tørke"],
        },
        "dead": ["døde", "dræbt", "dræbte", "omkom", "omkommet", "såret", "sårede"],
        "arrest": ["anholdt", "varetægtsfængslet", "sigtet"],
        "judicial": ["retssag", "dømt", "tiltalt", "byretten", "landsretten"],
        "noise": ["fodbold", "superligaen", "fodboldkamp"],
    },
    "fi": {
        "search": "hyökkäys OR räjähdys OR ammuskelu OR mielenosoitus OR mellakka OR sieppaus OR yhteenotot OR tulva OR maanjäristys OR poikkeustila",
        "cat": {
            "terrorism": ["terrori-isku", "terroristi", "terrorismi"],
            "attack": ["hyökkäy", "räjähdy", "ammuskel", "ammuttiin", "puukotu", "sieppau", "siepattiin", "panttivan", "pommi",
                       "tuhopolt"],
            "armed_conflict": ["ilmaisku", "ohjusisku", "drooni-isku", "taistelut", "tulitus"],
            "unrest": ["mielenosoitu", "mellakk", "lakko", "kyynelkaasu"],
            "political": ["poikkeustila", "vallankaappau", "sotatila"],
            "crime": ["murha", "henkirikos", "ryöstö", "jengi", "huumeet", "kiristy"],
            "cyber": ["kyberhyökkäy", "tietomurto", "hakkeri", "kiristyshaittaohjelm"],
            "infrastructure": ["sähkökatko", "suistui raiteilta", "kaasuräjähdy"],
            "health": ["epidemia", "taudinpurkau", "tuhkarokko"],
            "earthquake": ["maanjäristy"],
            "flood": ["tulva", "tulvi"],
            "cyclone": ["hirmumyrsky", "taifuuni", "sykloni"],
            "storm": ["myrsky", "rajuilma", "raesade"],
            "wildfire": ["metsäpalo", "maastopalo"],
            "volcano": ["tulivuor"],
            "landslide": ["maanvyöry"],
            "extreme_temp": ["helleaalto", "pakkasaalto"],
            "drought": ["kuivuus"],
        },
        "dead": ["kuoli", "kuollut", "kuollutta", "kuolonuhr", "loukkaantu", "sai surmansa"],
        "arrest": ["pidätetty", "pidätettiin", "otettiin kiinni", "vangittu", "vangittiin"],
        "judicial": ["oikeudenkäyn", "tuomittiin", "syyte", "käräjäoikeus", "hovioikeus"],
        "noise": ["jalkapallo", "veikkausliiga", "liiga-ottelu"],
    },
    "et": {
        "search": "rünnak OR plahvatus OR tulistamine OR meeleavaldus OR rahutused OR inimrööv OR kokkupõrked OR üleujutus OR maavärin OR eriolukord",
        "cat": {
            "terrorism": ["terrorirünnak", "terrorist"],
            "attack": ["rünnak", "plahvatus", "tulistam", "pussitam", "inimrööv", "pantvang", "pommi", "süütam"],
            "armed_conflict": ["õhurünnak", "raketirünnak", "droonirünnak", "lahingud"],
            "unrest": ["meeleavaldus", "rahutus", "streik", "pisargaas"],
            "political": ["eriolukord", "erakorraline seisukord", "riigipööre"],
            "crime": ["tapmine", "mõrv", "röövimine", "narkoo", "väljapressim"],
            "cyber": ["küberrünnak", "häkker", "lunavara"],
            "infrastructure": ["elektrikatkestus", "rööpaist välja"],
            "health": ["puhang", "epideemia", "leetrid"],
            "earthquake": ["maavärin"],
            "flood": ["üleujutus"],
            "cyclone": ["orkaan", "taifuun"],
            "storm": ["torm", "tormi"],
            "wildfire": ["metsapõleng", "maastikupõleng"],
            "landslide": ["maalihe"],
            "extreme_temp": ["kuumalaine"],
            "drought": ["põud"],
        },
        "dead": ["hukkus", "hukkunud", "surnud", "vigastat", "sai surma"],
        "arrest": ["vahistati", "peeti kinni", "kinni peetud"],
        "judicial": ["kohtuprotsess", "mõisteti", "süüdistus"],
        "noise": ["jalgpall", "korvpall"],
    },
    "lv": {
        "search": "uzbrukums OR sprādziens OR apšaude OR protests OR nemieri OR nolaupīšana OR sadursmes OR plūdi OR zemestrīce OR \"ārkārtējā situācija\"",
        "cat": {
            "terrorism": ["teroraktu", "terorakts", "teroris"],
            "attack": ["uzbrukum", "sprādzien", "apšaud", "nošāv", "nolaupīš", "ķīlniek", "bumba", "dedzināšan"],
            "armed_conflict": ["gaisa uzlidojum", "raķešu", "dronu uzbrukum", "kaujas"],
            "unrest": ["protest", "nemier", "streik", "asaru gāze"],
            "political": ["ārkārtējā situācija", "ārkārtas stāvokl", "apvērsum"],
            "crime": ["slepkavīb", "laupīšan", "narkotik", "izspiešan"],
            "cyber": ["kiberuzbrukum", "hakeri"],
            "infrastructure": ["elektroapgādes traucējum", "bez elektrības", "noskrēja no sliedēm"],
            "health": ["uzliesmojum", "epidēmij", "masalas"],
            "earthquake": ["zemestrīc"],
            "flood": ["plūdi", "plūdos", "plūdu"],
            "cyclone": ["viesuļvētr", "taifūn"],
            "storm": ["vētra", "vētras", "krusa"],
            "wildfire": ["meža ugunsgrēk", "kūlas ugunsgrēk"],
            "landslide": ["zemes nogruvum"],
            "extreme_temp": ["karstuma viln"],
            "drought": ["sausum"],
        },
        "dead": ["gāja bojā", "miris", "mirušo", "ievainot", "cietuš", "bojāgājuš"],
        "arrest": ["aizturēt", "apcietināt"],
        "judicial": ["notiesāt", "apsūdzīb", "tiesas sēd"],
        "noise": ["futbol", "hokej", "basketbol"],
    },
    "lt": {
        "search": "išpuolis OR sprogimas OR šaudymas OR protestas OR riaušės OR pagrobimas OR susirėmimai OR potvynis OR \"žemės drebėjimas\" OR \"nepaprastoji padėtis\"",
        "cat": {
            "terrorism": ["teroro aktas", "teroristin", "teroristai"],
            "attack": ["išpuol", "užpuol", "sprogim", "šaudym", "nušov", "pagrob", "įkaitai", "bomba", "padegim"],
            "armed_conflict": ["oro antpuol", "raketų ataka", "dronų ataka", "mūšiai", "apšaudym"],
            "unrest": ["protest", "riaušės", "streik", "ašarinės dujos"],
            "political": ["nepaprastoji padėtis", "karo padėtis", "perversm"],
            "crime": ["nužud", "apiplėš", "narkotik", "prievartavim"],
            "cyber": ["kibernetinė ataka", "kibernetinės atakos", "įsilauž"],
            "infrastructure": ["elektros tiekimo sutrikim", "be elektros", "nuvažiavo nuo bėgių"],
            "health": ["protrūk", "epidemij", "tymai"],
            "earthquake": ["žemės drebėjim"],
            "flood": ["potvyn"],
            "cyclone": ["uragan", "taifūn"],
            "storm": ["audra", "audros", "škvalas", "kruša"],
            "wildfire": ["miško gaisr"],
            "volcano": ["ugnikaln"],
            "landslide": ["nuošliauž"],
            "extreme_temp": ["karščio bang"],
            "drought": ["sausr"],
        },
        "dead": ["žuvo", "žuvusi", "žuvusių", "mirė", "sužeist", "nukentėj"],
        "arrest": ["sulaikyt", "suimt"],
        "judicial": ["nuteist", "kaltinim", "teismo posėd"],
        "noise": ["rungtyn", "futbol", "krepšin"],
    },
    # ---------------------------------------------------------------- Europe centrale et orientale, Balkans
    "cs": {
        "search": "útok OR výbuch OR střelba OR demonstrace OR nepokoje OR únos OR střety OR povodně OR zemětřesení OR \"nouzový stav\"",
        "cat": {
            "terrorism": ["teroristick", "terorismus", "teroristé"],
            "attack": ["útok", "útoku", "útočník", "výbuch", "střelba", "střelbě", "postřel", "pobodal", "únos", "unesen", "rukojm",
                       "žhářsk"],
            "armed_conflict": ["nálet", "raketový útok", "dronový útok", "boje", "ostřelov"],
            "unrest": ["demonstrac", "nepokoj", "stávk", "slzný plyn"],
            "political": ["nouzový stav", "převrat", "stanné právo"],
            "crime": ["vražd", "zavražd", "loupež", "přepaden", "drogy", "drogov", "vydírá"],
            "cyber": ["kybernetický útok", "hackerský útok", "ransomware"],
            "infrastructure": ["výpadek proudu", "vykolej", "zřícen", "výbuch plynu"],
            "health": ["epidemi", "nákaz", "spalničk"],
            "earthquake": ["zemětřesen"],
            "flood": ["povodn", "povodeň", "záplav"],
            "cyclone": ["hurikán", "tajfun"],
            "storm": ["bouřk", "krupobit", "tornád", "vichřic"],
            "wildfire": ["lesní požár"],
            "volcano": ["sopk", "erupc"],
            "landslide": ["sesuv"],
            "extreme_temp": ["vedra", "vedro", "horka"],
            "drought": ["sucho"],
        },
        "dead": ["mrtvých", "mrtví", "mrtvý", "zemřel", "zahynul", "zabit", "zraněn"],
        "arrest": ["zatčen", "zadržen", "obviněn"],
        "judicial": ["soud", "odsouzen", "obžalob"],
        "noise": ["zápas", "fotbal", "hokej"],
    },
    "sk": {
        "search": "útok OR výbuch OR streľba OR demonštrácia OR nepokoje OR únos OR strety OR povodne OR zemetrasenie OR \"núdzový stav\"",
        "cat": {
            "terrorism": ["teroristick", "terorizmus"],
            "attack": ["útok", "útoku", "útočník", "výbuch", "streľb", "postrelil", "pobodal", "únos", "unesen", "rukojem", "podpaľač"],
            "armed_conflict": ["nálet", "raketový útok", "dronový útok", "boje", "ostreľov"],
            "unrest": ["demonštrác", "nepokoj", "štrajk", "slzotvorn"],
            "political": ["núdzový stav", "mimoriadna situácia", "štátny prevrat"],
            "crime": ["vražd", "zavraždil", "lúpež", "prepaden", "drogy", "drogov", "vydieran"],
            "cyber": ["kybernetický útok", "hackerský útok", "ransomware"],
            "infrastructure": ["výpadok prúdu", "vykoľaj", "zrútil", "výbuch plynu"],
            "health": ["epidémi", "nákaz", "osýpk"],
            "earthquake": ["zemetrasen"],
            "flood": ["povodn", "povodeň", "záplav"],
            "storm": ["búrk", "krupobit", "víchric", "tornád"],
            "wildfire": ["lesný požiar"],
            "landslide": ["zosuv"],
            "extreme_temp": ["horúčav"],
            "drought": ["sucho"],
        },
        "dead": ["mŕtvych", "mŕtvy", "zomrel", "zahynul", "zabit", "zranen"],
        "arrest": ["zadržan", "zatknut", "obvinen"],
        "judicial": ["odsúden", "obžalob", "súdny proces"],
        "noise": ["zápas", "futbal", "hokej"],
    },
    "hu": {
        "search": "támadás OR robbanás OR lövöldözés OR tüntetés OR zavargás OR emberrablás OR összecsapás OR árvíz OR földrengés OR veszélyhelyzet",
        "cat": {
            "terrorism": ["terrortámadás", "terrorista", "terrorizmus"],
            "attack": ["támadás", "támadó", "robbanás", "lövöldöz", "lelőtt", "megkésel", "emberrabl", "elrabolt", "túsz", "bomba",
                       "gyújtogat"],
            "armed_conflict": ["légicsapás", "rakétatámadás", "dróntámadás", "harcok", "tüzérségi"],
            "unrest": ["tüntetés", "tüntető", "zavargás", "sztrájk", "könnygáz"],
            "political": ["veszélyhelyzet", "szükségállapot", "katonai puccs", "puccs"],
            "crime": ["gyilkosság", "megölt", "rablás", "kábítószer", "zsarolás"],
            "cyber": ["kibertámadás", "hackertámadás", "zsarolóvírus"],
            "infrastructure": ["áramszünet", "kisiklott", "gázrobbanás"],
            "health": ["járvány", "kanyaró", "kolera"],
            "earthquake": ["földrengés"],
            "flood": ["árvíz", "áradás", "belvíz"],
            "cyclone": ["hurrikán", "tájfun"],
            "storm": ["vihar", "jégeső", "tornádó", "szélvihar"],
            "wildfire": ["erdőtűz", "bozóttűz"],
            "volcano": ["vulkán"],
            "landslide": ["földcsuszamlás"],
            "extreme_temp": ["hőség", "kánikula", "hőhullám"],
            "drought": ["aszály"],
        },
        "dead": ["halott", "meghalt", "életét vesztette", "sérült", "megsebesült", "halálos áldozat"],
        "arrest": ["őrizetbe", "letartóztat", "elfogták"],
        "judicial": ["bíróság", "elítélt", "vádemelés", "ítélet"],
        "noise": ["meccs", "labdarúgás", "foci"],
    },
    "ro": {
        "search": "atac OR explozie OR împușcături OR protest OR revolte OR răpire OR ciocniri OR inundații OR cutremur OR \"stare de urgență\"",
        "cat": {
            "terrorism": ["atentat terorist", "teroris"],
            "attack": ["atac armat", "atacat", "explozi", "împușcătur", "înjunghi", "răpire", "răpit", "ostatic", "bombă", "incendiere"],
            "armed_conflict": ["bombardament", "lovitură aeriană", "atac cu rachete", "atac cu drone", "lupte grele"],
            "unrest": ["protest", "manifestați", "revolt", "grevă", "gaze lacrimogene"],
            "political": ["stare de urgență", "lovitură de stat", "lege marțială"],
            "crime": ["crimă", "omor", "tâlhări", "narcotrafic", "extorcare"],
            "cyber": ["atac cibernetic", "atac informatic", "ransomware"],
            "infrastructure": ["pană de curent", "fără curent", "deraiere", "deraiat", "explozie de gaz"],
            "health": ["epidemie", "focar", "holeră", "rujeol"],
            "earthquake": ["cutremur", "seism"],
            "flood": ["inundați", "viitur"],
            "cyclone": ["ciclon", "uragan", "taifun"],
            "storm": ["furtun", "vijeli", "grindin", "tornadă"],
            "wildfire": ["incendiu de pădure", "incendiu de vegetație"],
            "volcano": ["vulcan"],
            "landslide": ["alunecare de teren", "alunecări de teren"],
            "extreme_temp": ["caniculă", "val de căldură"],
            "drought": ["secetă"],
        },
        "dead": ["morți", "decedat", "decedați", "uciși", "ucis", "răniți", "rănit", "și-au pierdut viața"],
        "arrest": ["arestat", "reținut", "reținuți", "încătușat"],
        "judicial": ["condamnat", "sentință", "inculpat", "rechizitoriu"],
        "noise": ["meci", "fotbal", "superliga"],
    },
    "bg": {
        "search": "атака OR взрив OR стрелба OR протест OR безредици OR отвличане OR сблъсъци OR наводнение OR земетресение OR \"извънредно положение\"",
        "cat": {
            "terrorism": ["терористич", "тероризъм"],
            "attack": ["нападение", "взрив", "стрелба", "простреля", "намушка", "отвлич", "заложни", "бомба", "палеж"],
            "armed_conflict": ["въздушен удар", "ракетен удар", "дронове", "боеве", "обстрел"],
            "unrest": ["протест", "безредиц", "стачк", "сълзотворен"],
            "political": ["извънредно положение", "военно положение", "преврат"],
            "crime": ["убийств", "обир", "наркоти", "изнудв"],
            "cyber": ["кибератака", "хакерска атака"],
            "infrastructure": ["без ток", "спиране на тока", "дерайлира", "срути"],
            "health": ["епидеми", "огнище", "морбили"],
            "earthquake": ["земетресен", "земетръс"],
            "flood": ["наводнен", "порой"],
            "storm": ["буря", "бури", "градушк", "торнадо"],
            "wildfire": ["горски пожар"],
            "landslide": ["свлачищ"],
            "extreme_temp": ["горещини", "жега"],
            "drought": ["суша"],
        },
        "dead": ["загина", "загинаха", "загинали", "убит", "убити", "починал", "ранен", "ранени", "пострадал"],
        "arrest": ["арестуван", "задържан", "задържаха"],
        "judicial": ["осъден", "присъда", "обвинение"],
        "noise": ["футбол", "мач"],
    },
    "mk": {
        "search": "напад OR експлозија OR пукање OR протест OR немири OR киднапирање OR судири OR поплави OR земјотрес OR \"вонредна состојба\"",
        "cat": {
            "terrorism": ["терористич", "тероризам"],
            "attack": ["напад", "нападот", "експлозиј", "пукање", "престрел", "прободен", "киднап", "заложни", "бомба"],
            "armed_conflict": ["воздушен напад", "ракетен напад", "борби"],
            "unrest": ["протест", "немири", "штрајк", "солзавец"],
            "political": ["вонредна состојба", "државен удар"],
            "crime": ["убиство", "убиен", "грабеж", "дрога", "изнуда"],
            "cyber": ["сајбер напад", "хакерски напад"],
            "infrastructure": ["прекин на струја", "без струја", "урнат"],
            "health": ["епидемиј", "морбили"],
            "earthquake": ["земјотрес"],
            "flood": ["поплав"],
            "storm": ["невреме", "бура"],
            "wildfire": ["шумски пожар"],
            "landslide": ["свлечиште"],
            "extreme_temp": ["топлотен бран"],
            "drought": ["суша"],
        },
        "dead": ["загина", "загинаа", "загинат", "починал", "повреден", "повредени", "ранет"],
        "arrest": ["уапсен", "уапсени", "приведен"],
        "judicial": ["осуден", "пресуда", "обвинение"],
        "noise": ["фудбал", "натпревар"],
    },
    "sh": {   # serbe, croate, bosnien, monténégrin (alphabet latin)
        "search": "napad OR eksplozija OR pucnjava OR protest OR neredi OR otmica OR sukobi OR poplave OR zemljotres OR potres OR \"vanredno stanje\"",
        "cat": {
            "terrorism": ["terorist", "teroriz"],
            "attack": ["napad", "napadnut", "napadač", "eksplozij", "pucnjav", "uboden", "izboden", "otmic", "otet", "bombašk",
                       "talac", "taoci", "podmetnut"],
            "armed_conflict": ["vazdušni napad", "zračni napad", "raketni napad", "dronovi", "granatiran", "sukobi"],
            "unrest": ["prosvjed", "demonstraci", "neredi", "štrajk", "suzavac", "blokada"],
            "political": ["vanredno stanje", "izvanredno stanje", "državni udar"],
            "crime": ["ubistvo", "ubojstvo", "ubijen", "pljačk", "narko", "iznud"],
            "cyber": ["hakerski napad", "sajber napad", "kibernetički napad"],
            "infrastructure": ["nestanak struje", "bez struje", "iskliznuć", "urušavanj", "eksplozija gasa", "eksplozija plina"],
            "health": ["epidemij", "ospice", "zarazn"],
            "earthquake": ["zemljotres", "potres"],
            "flood": ["poplav", "bujic"],
            "cyclone": ["uragan", "tajfun"],
            "storm": ["oluja", "oluje", "olujni", "nevrem", "nevrijem", "tuča", "tornado"],
            "wildfire": ["šumski požar"],
            "volcano": ["vulkan"],
            "landslide": ["klizišt", "odron"],
            "extreme_temp": ["toplotni talas", "toplinski val", "ekstremne vrućine"],
            "drought": ["suša"],
        },
        "dead": ["poginul", "poginuo", "ubijen", "ubijeno", "mrtvih", "ranjen", "povređen", "ozlijeđen", "stradal"],
        "arrest": ["uhapšen", "uhićen", "priveden", "pritvor"],
        "judicial": ["suđenje", "presuda", "optužnic", "osuđen"],
        "noise": ["fudbal", "nogomet", "utakmic"],
    },
    "sl": {
        "search": "napad OR eksplozija OR streljanje OR protest OR nemiri OR ugrabitev OR spopadi OR poplave OR potres OR \"izredne razmere\"",
        "cat": {
            "terrorism": ["teroristič", "terorizem"],
            "attack": ["napad", "eksplozij", "streljanj", "ustrelil", "zabodel", "ugrabit", "talec", "bomba", "požig"],
            "armed_conflict": ["zračni napad", "raketni napad", "spopadi"],
            "unrest": ["demonstrac", "nemiri", "stavk", "solzivec"],
            "political": ["izredne razmere", "državni udar"],
            "crime": ["umor", "umora", "ropar", "mamil", "izsiljev"],
            "cyber": ["kibernetski napad", "hekerski napad"],
            "infrastructure": ["izpad elektrike", "brez elektrike", "iztiril"],
            "health": ["epidemij", "izbruh", "ošpice"],
            "earthquake": ["potres"],
            "flood": ["poplav", "hudournik"],
            "storm": ["nevihta", "neurje", "toča"],
            "wildfire": ["gozdni požar"],
            "landslide": ["zemeljski plaz"],
            "extreme_temp": ["vročinski val"],
            "drought": ["suša"],
        },
        "dead": ["umrl", "umrli", "mrtvih", "smrtno", "poškodovan", "ranjen"],
        "arrest": ["aretiran", "pridržan", "prijet"],
        "judicial": ["obsojen", "obtožb", "sojenje"],
        "noise": ["nogomet", "tekma"],
    },
    "sq": {
        "search": "sulm OR shpërthim OR \"të shtëna\" OR protestë OR trazira OR rrëmbim OR përplasje OR përmbytje OR tërmet OR \"gjendje e jashtëzakonshme\"",
        "cat": {
            "terrorism": ["terrorist", "terroriz"],
            "attack": ["sulm", "sulmi", "sulmuar", "shpërthim", "të shtëna", "plagos", "rrëmbim", "rrëmbye", "peng", "granat"],
            "armed_conflict": ["bombardim", "sulm ajror", "sulm me raketa", "luftim"],
            "unrest": ["protest", "trazir", "greva", "grevë", "demonstrat", "gaz lotsjellës"],
            "political": ["gjendje e jashtëzakonshme", "grusht shteti"],
            "crime": ["vrasje", "vrarë", "grabit", "droga", "zhvatje"],
            "cyber": ["sulm kibernetik", "haker"],
            "infrastructure": ["ndërprerje e energjisë", "pa drita", "shembje"],
            "health": ["epidemi", "fruth", "kolera"],
            "earthquake": ["tërmet"],
            "flood": ["përmbytj"],
            "storm": ["stuhi", "breshër"],
            "wildfire": ["zjarr në pyll", "zjarri"],
            "landslide": ["rrëshqitje dheu"],
            "extreme_temp": ["valë të nxehti"],
            "drought": ["thatësir"],
        },
        "dead": ["vdekur", "vdiq", "humbën jetën", "humbi jetën", "plagosur", "të vrarë"],
        "arrest": ["arrestohet", "arrestuar", "arrestim", "shoqërohen"],
        "judicial": ["gjykat", "dënuar", "dënim"],
        "noise": ["futboll", "ndeshj"],
    },
    "el": {
        "search": "επίθεση OR έκρηξη OR πυροβολισμοί OR διαδήλωση OR επεισόδια OR απαγωγή OR συγκρούσεις OR πλημμύρες OR σεισμός OR \"κατάσταση έκτακτης ανάγκης\"",
        "cat": {
            "terrorism": ["τρομοκρατ"],
            "attack": ["επίθεσ", "έκρηξ", "πυροβολ", "μαχαιρ", "απαγωγ", "όμηρ", "βόμβα", "εμπρησμ"],
            "armed_conflict": ["βομβαρδισμ", "αεροπορική επιδρομή", "πυραυλ", "μάχες", "εχθροπραξ"],
            "unrest": ["διαδήλωσ", "διαμαρτυρ", "επεισόδι", "ταραχ", "απεργ", "δακρυγόνα", "χημικά"],
            "political": ["κατάσταση έκτακτης ανάγκης", "πραξικόπημα", "στρατιωτικός νόμος"],
            "crime": ["δολοφον", "ληστεί", "μαφία", "ναρκωτικ", "εκβιασμ"],
            "cyber": ["κυβερνοεπίθεσ", "χάκερ"],
            "infrastructure": ["μπλακ άουτ", "διακοπή ρεύματος", "εκτροχιασμ", "κατάρρευσ"],
            "health": ["επιδημ", "κρούσματα", "χολέρα", "ιλαρά"],
            "earthquake": ["σεισμ"],
            "flood": ["πλημμύρ"],
            "cyclone": ["κυκλώνα", "τυφώνα", "μεσογειακός κυκλώνας"],
            "storm": ["καταιγίδ", "κακοκαιρία", "χαλαζόπτωσ", "ανεμοστρόβιλ"],
            "wildfire": ["πυρκαγι", "δασική φωτιά"],
            "volcano": ["ηφαίστει"],
            "landslide": ["κατολίσθησ"],
            "extreme_temp": ["καύσωνα", "παγετό"],
            "drought": ["ξηρασία", "λειψυδρία"],
        },
        "dead": ["νεκρ", "σκοτώθηκ", "τραυματ", "έχασαν τη ζωή", "έχασε τη ζωή"],
        "arrest": ["σύλληψη", "συνελήφθ", "προσαγωγ"],
        "judicial": ["δίκη", "καταδικ", "ποινή", "κατηγορούμεν"],
        "noise": ["ποδόσφαιρ", "αγώνα", "σούπερ λίγκα"],
    },
    # ---------------------------------------------------------------- Caucase, Asie centrale, Mongolie
    "ka": {
        "search": "თავდასხმა OR აფეთქება OR სროლა OR აქცია OR არეულობა OR გატაცება OR შეტაკება OR წყალდიდობა OR მიწისძვრა OR \"საგანგებო მდგომარეობა\"",
        "cat": {
            "terrorism": ["ტერორ"],
            "attack": ["თავდასხმ", "აფეთქებ", "სროლ", "გატაცებ", "მძევ", "ბომბ"],
            "armed_conflict": ["საჰაერო დარტყმ", "რაკეტ", "დრონ", "დაბომბვ"],
            "unrest": ["აქცი", "პროტესტ", "დემონსტრაცი", "არეულობ", "გაფიცვ", "ცრემლსადენ", "შეტაკებ"],
            "political": ["საგანგებო მდგომარეობ", "სამხედრო გადატრიალებ", "საომარი მდგომარეობ"],
            "crime": ["მკვლელობ", "ძარცვ", "ნარკოტიკ", "გამოძალვ"],
            "cyber": ["კიბერშეტევ", "ჰაკერ"],
            "infrastructure": ["ელექტროენერგიის გათიშვ", "შუქის გათიშვ", "ჩამონგრევ"],
            "health": ["ეპიდემი", "წითელა", "ქოლერა"],
            "earthquake": ["მიწისძვრ"],
            "flood": ["წყალდიდობ", "ღვარცოფ"],
            "storm": ["ქარიშხალ", "სეტყვ"],
            "wildfire": ["ტყის ხანძარ", "ხანძარ"],
            "landslide": ["მეწყერ"],
            "drought": ["გვალვ"],
        },
        "dead": ["დაიღუპ", "გარდაიცვალ", "დაჭრილ", "მოკლეს", "დაშავდ"],
        "arrest": ["დააკავეს", "დაკავებ"],
        "judicial": ["სასამართლო", "მსჯავრ", "ბრალდებ"],
        "noise": ["ფეხბურთ", "მატჩ"],
    },
    "hy": {
        "search": "հարձակում OR պայթյուն OR կրակոց OR ցույց OR անկարգություններ OR առևանգում OR բախումներ OR ջրհեղեղ OR երկրաշարժ OR \"արտակարգ դրություն\"",
        "cat": {
            "terrorism": ["ահաբեկ"],
            "attack": ["հարձակ", "պայթյուն", "կրակոց", "դանակահար", "առևանգ", "պատանդ", "ռումբ", "հրկիզ"],
            "armed_conflict": ["ավիահարված", "հրթիռ", "անօդաչու", "մարտեր", "գնդակոծ", "հրետակոծ"],
            "unrest": ["բողոքի ակցիա", "ցույց", "անկարգություն", "գործադուլ", "արցունքաբեր"],
            "political": ["արտակարգ դրություն", "ռազմական դրություն", "հեղաշրջում"],
            "crime": ["սպանություն", "կողոպուտ", "թմրանյութ", "շորթում"],
            "cyber": ["կիբերհարձակում", "հաքեր"],
            "infrastructure": ["հոսանքազրկ", "փլուզ"],
            "health": ["համաճարակ", "բռնկում", "կարմրուկ"],
            "earthquake": ["երկրաշարժ"],
            "flood": ["ջրհեղեղ", "հեղեղ"],
            "storm": ["փոթորիկ", "կարկուտ"],
            "wildfire": ["անտառային հրդեհ"],
            "landslide": ["սողանք"],
            "drought": ["երաշտ"],
        },
        "dead": ["զոհվել", "մահացել", "սպանվել", "վիրավոր", "զոհեր"],
        "arrest": ["ձերբակալ"],
        "judicial": ["դատարան", "դատապարտ", "մեղադրանք"],
        "noise": ["ֆուտբոլ"],
    },
    "az": {
        "search": "hücum OR partlayış OR atışma OR etiraz OR iğtişaş OR girov OR toqquşma OR daşqın OR zəlzələ OR \"fövqəladə vəziyyət\"",
        "cat": {
            "terrorism": ["terror aktı", "terrorçu"],
            "attack": ["hücum", "partlayış", "atəş açıl", "bıçaqla", "girov", "bomba", "yandırıl"],
            "armed_conflict": ["hava zərbəsi", "raket zərbəsi", "dron hücumu", "döyüşlər", "atəşkəs"],
            "unrest": ["etiraz", "iğtişaş", "tətil", "gözyaşardıcı"],
            "political": ["fövqəladə vəziyyət", "hərbi vəziyyət", "dövlət çevrilişi"],
            "crime": ["qətl", "öldürül", "soyğun", "narkotik", "qəsb"],
            "cyber": ["kiberhücum", "haker"],
            "infrastructure": ["elektrik kəsil", "işıq kəsil", "çökmə"],
            "health": ["epidemiya", "qızılca", "vəba"],
            "earthquake": ["zəlzələ", "zəlzələ"],
            "flood": ["daşqın", "sel"],
            "storm": ["fırtına", "qasırğa", "dolu"],
            "wildfire": ["meşə yanğın"],
            "landslide": ["sürüşmə"],
            "extreme_temp": ["istilik dalğası"],
            "drought": ["quraqlıq"],
        },
        "dead": ["həlak olub", "həyatını itirib", "yaralan", "yaralı"],
        "arrest": ["həbs", "saxlanıl"],
        "judicial": ["məhkəmə", "hökm"],
        "noise": ["futbol", "matç"],
    },
    "uz": {
        "search": "hujum OR portlash OR otishma OR namoyish OR tartibsizlik OR garov OR to'qnashuv OR \"suv toshqini\" OR zilzila OR \"favqulodda holat\"",
        "cat": {
            "terrorism": ["terrorchi", "terrorizm"],
            "attack": ["hujum", "portlash", "otishma", "pichoqla", "garovga", "bomba"],
            "armed_conflict": ["havo hujumi", "raketa zarbasi", "dron hujumi", "janglar"],
            "unrest": ["namoyish", "norozilik", "tartibsizlik", "ish tashlash"],
            "political": ["favqulodda holat", "harbiy holat", "davlat to'ntarishi"],
            "crime": ["qotillik", "talonchilik", "giyohvand", "tovlamachilik"],
            "cyber": ["kiberhujum", "xaker"],
            "infrastructure": ["elektr uzil", "qulab tushdi"],
            "health": ["epidemiya", "qizamiq", "yuqumli"],
            "earthquake": ["zilzila", "yer silkinishi"],
            "flood": ["suv toshqini", "sel"],
            "storm": ["kuchli shamol", "do'l"],
            "landslide": ["ko'chki"],
            "extreme_temp": ["jazirama"],
            "drought": ["qurg'oqchilik"],
        },
        "dead": ["halok", "vafot", "yarador", "jarohat"],
        "arrest": ["hibsga", "qo'lga olindi"],
        "judicial": ["sudlandi", "hukm qilindi"],
        "noise": ["futbol"],
    },
    "mn": {
        "search": "халдлага OR дэлбэрэлт OR буудлага OR жагсаал OR үймээн OR барьцаа OR мөргөлдөөн OR үер OR \"газар хөдлөлт\" OR \"онцгой байдал\"",
        "cat": {
            "attack": ["халдлага", "дэлбэрэлт", "буудлага", "хутгал", "барьцаа"],
            "armed_conflict": ["агаарын цохилт", "пуужин", "байлдаан"],
            "unrest": ["жагсаал", "эсэргүүцлийн", "үймээн", "ажил хаялт"],
            "political": ["онцгой байдал", "төрийн эргэлт"],
            "crime": ["хүн амины", "аллага", "дээрэм", "хар тамхи"],
            "cyber": ["кибер халдлага", "хакер"],
            "infrastructure": ["цахилгаан тасар", "нурсан"],
            "health": ["дэгдэлт", "тахал", "улаанбурхан", "халдварт"],
            "earthquake": ["газар хөдлөл"],
            "flood": ["үер", "үерт"],
            "storm": ["шуурга", "мөндөр"],
            "wildfire": ["түймэр"],
            "extreme_temp": ["хүйтний давалгаа"],
            "drought": ["ган гачиг"],
        },
        "dead": ["нас барж", "нас барсан", "амь үрэгд", "гэмтэ"],
        "arrest": ["баривчил", "саатуул"],
        "judicial": ["шүүх хурал", "ял оноо"],
        "noise": ["хөлбөмбөг", "тэмцээн"],
    },
    # ---------------------------------------------------------------- Asie du Sud
    "hi": {
        "search": "हमला OR विस्फोट OR गोलीबारी OR प्रदर्शन OR दंगा OR अपहरण OR झड़प OR बाढ़ OR भूकंप OR आपातकाल",
        "cat": {
            "terrorism": ["आतंकी", "आतंकवाद", "आतंकियों"],
            "attack": ["हमला", "हमले", "विस्फोट", "धमाका", "धमाके", "गोलीबारी", "फायरिंग", "चाकू", "अपहरण", "बंधक", "आगजनी"],
            "armed_conflict": ["हवाई हमला", "मिसाइल", "ड्रोन हमला", "मुठभेड़", "गोलाबारी", "नक्सली", "माओवादी"],
            "unrest": ["प्रदर्शन", "दंगा", "दंगे", "हड़ताल", "आंसू गैस", "लाठीचार्ज", "बवाल", "पथराव"],
            "political": ["आपातकाल", "कर्फ्यू", "तख्तापलट", "राष्ट्रपति शासन"],
            "crime": ["हत्या", "लूट", "डकैती", "गैंगस्टर", "रंगदारी"],
            "cyber": ["साइबर हमला", "हैकर", "रैनसमवेयर"],
            "infrastructure": ["बिजली गुल", "ब्लैकआउट", "पटरी से उतर", "सिलेंडर विस्फोट", "पुल गिरा", "इमारत ढह"],
            "health": ["महामारी", "प्रकोप", "हैजा", "डेंगू", "खसरा"],
            "earthquake": ["भूकंप"],
            "flood": ["बाढ़", "जलभराव"],
            "cyclone": ["चक्रवात"],
            "storm": ["आंधी", "ओलावृष्टि", "बवंडर", "तूफान"],
            "wildfire": ["जंगल में आग"],
            "landslide": ["भूस्खलन"],
            "extreme_temp": ["शीतलहर", "भीषण गर्मी", "लू का"],
            "drought": ["सूखा"],
        },
        "dead": ["मौत", "मारे गए", "मृत", "घायल", "जान गई", "शहीद"],
        "arrest": ["गिरफ्तार", "हिरासत"],
        "judicial": ["अदालत", "सजा", "कोर्ट", "फैसला"],
        "noise": ["क्रिकेट", "मैच", "फिल्म", "बॉलीवुड"],
    },
    "ne": {
        "search": "आक्रमण OR विस्फोट OR गोली OR प्रदर्शन OR दंगा OR अपहरण OR झडप OR बाढी OR भूकम्प OR संकटकाल",
        "cat": {
            "terrorism": ["आतंककारी"],
            "attack": ["आक्रमण", "विस्फोट", "गोली हान", "गोली प्रहार", "अपहरण", "बन्धक"],
            "armed_conflict": ["हवाई आक्रमण", "भिडन्त", "झडप"],
            "unrest": ["प्रदर्शन", "आन्दोलन", "दंगा", "हडताल", "अश्रुग्यास", "नेपाल बन्द"],
            "political": ["संकटकाल", "कर्फ्यु", "निषेधाज्ञा"],
            "crime": ["हत्या", "डकैती", "लागूऔषध"],
            "cyber": ["साइबर आक्रमण", "ह्याक"],
            "infrastructure": ["बिजुली अवरुद्ध", "भत्कियो"],
            "health": ["महामारी", "प्रकोप", "हैजा", "डेंगु", "दादुरा"],
            "earthquake": ["भूकम्प"],
            "flood": ["बाढी", "डुबान"],
            "storm": ["हावाहुरी", "असिना"],
            "wildfire": ["डढेलो"],
            "landslide": ["पहिरो"],
            "extreme_temp": ["शीतलहर"],
            "drought": ["खडेरी"],
        },
        "dead": ["मृत्यु", "ज्यान गयो", "मारिए", "घाइते"],
        "arrest": ["पक्राउ"],
        "judicial": ["अदालत", "फैसला"],
        "noise": ["क्रिकेट", "फुटबल"],
    },
    "ps": {   # pachto (Afghanistan, Pakistan : Khyber Pakhtunkhwa, Baloutchistan)
        "search": "برید OR چاودنه OR ډزې OR لاریون OR تښتونه OR نښته OR سیلاب OR زلزله",
        "cat": {
            "terrorism": ["ترهګر", "ځانمرګي برید", "ځانمرګی"],
            "attack": ["برید", "چاودنه", "چاودنې", "ډزې", "تښتونه", "وتښتول"],
            "armed_conflict": ["نښته", "نښتې", "هوايي برید", "ډرون برید", "جګړه"],
            "unrest": ["لاریون", "مظاهره", "اعتصاب"],
            "political": ["بیړني حالت", "کودتا"],
            "crime": ["وژنه", "غلا"],
            "health": ["وبا", "کولرا", "شری"],
            "earthquake": ["زلزله", "زلزلې"],
            "flood": ["سیلاب", "سېلاب"],
            "landslide": ["ښویدنه"],
            "drought": ["وچکالي"],
        },
        "dead": ["ووژل شول", "مړه", "ټپيان", "ټپي شول"],
        "arrest": ["ونیول شو", "ونیول شول"],
        "judicial": ["محکمه"],
        "noise": ["کرکټ", "فوټبال"],
    },
    "ta": {
        "search": "தாக்குதல் OR வெடிப்பு OR \"துப்பாக்கிச் சூடு\" OR போராட்டம் OR கலவரம் OR கடத்தல் OR மோதல் OR வெள்ளம் OR நிலநடுக்கம் OR அவசரநிலை",
        "cat": {
            "terrorism": ["பயங்கரவாத"],
            "attack": ["தாக்குதல்", "வெடிகுண்டு", "குண்டுவெடிப்பு", "துப்பாக்கிச் சூடு", "கடத்தல்", "பணயக்கைதி"],
            "armed_conflict": ["வான்வழித் தாக்குதல்", "ஏவுகணை", "ட்ரோன்"],
            "unrest": ["போராட்டம்", "ஆர்ப்பாட்டம்", "கலவரம்", "வேலைநிறுத்தம்", "கண்ணீர்ப்புகை", "மறியல்"],
            "political": ["அவசரநிலை", "ஊரடங்கு"],
            "crime": ["கொலை", "கொள்ளை", "போதைப்பொருள்"],
            "cyber": ["சைபர் தாக்குதல்"],
            "infrastructure": ["மின்தடை", "மின் தடை", "தடம் புரண்ட"],
            "health": ["தொற்று பரவல்", "காலரா", "டெங்கு"],
            "earthquake": ["நிலநடுக்கம்"],
            "flood": ["வெள்ளம்", "வெள்ளப்பெருக்கு"],
            "cyclone": ["புயல்"],
            "storm": ["சூறாவளி", "ஆலங்கட்டி"],
            "wildfire": ["காட்டுத்தீ"],
            "landslide": ["நிலச்சரிவு"],
            "extreme_temp": ["வெப்ப அலை"],
            "drought": ["வறட்சி"],
        },
        "dead": ["உயிரிழப்பு", "பலி", "உயிரிழந்த", "படுகாயம்", "காயம்"],
        "arrest": ["கைது"],
        "judicial": ["நீதிமன்றம்", "தீர்ப்பு"],
        "noise": ["கிரிக்கெட்"],
    },
    # ---------------------------------------------------------------- Asie de l'Est et du Sud-Est
    "ja": {
        "search": "テロ OR 爆発 OR 銃撃 OR デモ OR 暴動 OR 誘拐 OR 衝突 OR 洪水 OR 地震 OR 非常事態",
        "cat": {
            "terrorism": ["テロ"],
            "attack": ["襲撃", "爆発", "銃撃", "発砲", "刺傷", "刺され", "誘拐", "人質", "爆弾", "放火"],
            "armed_conflict": ["空爆", "ミサイル", "ドローン攻撃", "戦闘", "砲撃"],
            "unrest": ["デモ隊", "抗議デモ", "暴動", "ストライキ", "催涙"],
            "political": ["非常事態", "クーデター", "戒厳令"],
            "crime": ["殺人", "強盗", "暴力団", "麻薬", "恐喝"],
            "cyber": ["サイバー攻撃", "ハッカー", "ランサムウェア", "不正アクセス"],
            "infrastructure": ["停電", "脱線", "崩落", "ガス爆発"],
            "health": ["感染拡大", "集団感染", "コレラ", "はしか"],
            "earthquake": ["地震", "震度"],
            "flood": ["洪水", "浸水", "氾濫", "大雨特別警報"],
            "cyclone": ["台風"],
            "storm": ["暴風", "竜巻", "大雪"],
            "wildfire": ["山火事", "林野火災"],
            "volcano": ["噴火", "火山"],
            "landslide": ["土砂崩れ", "土石流", "がけ崩れ"],
            "extreme_temp": ["猛暑", "熱中症", "寒波"],
            "drought": ["干ばつ", "水不足"],
        },
        "dead": ["死亡", "死者", "遺体", "負傷", "重傷", "けが"],
        "arrest": ["逮捕", "送検"],
        "judicial": ["判決", "起訴", "公判"],
        "noise": ["サッカー", "野球", "試合"],
    },
    "ko": {
        "search": "테러 OR 폭발 OR 총격 OR 시위 OR 폭동 OR 납치 OR 충돌 OR 홍수 OR 지진 OR 비상사태",
        "cat": {
            "terrorism": ["테러"],
            "attack": ["습격", "폭발", "총격", "흉기", "피습", "납치", "인질", "폭탄", "방화"],
            "armed_conflict": ["공습", "미사일", "드론 공격", "교전", "포격"],
            "unrest": ["시위", "폭동", "파업", "최루"],
            "political": ["비상사태", "계엄", "쿠데타"],
            "crime": ["살인", "강도", "조직폭력", "마약", "갈취"],
            "cyber": ["사이버 공격", "해킹", "랜섬웨어"],
            "infrastructure": ["정전", "탈선", "붕괴", "가스 폭발"],
            "health": ["집단감염", "콜레라", "홍역"],
            "earthquake": ["지진"],
            "flood": ["홍수", "침수", "폭우"],
            "cyclone": ["태풍"],
            "storm": ["강풍", "우박", "토네이도", "폭설"],
            "wildfire": ["산불"],
            "volcano": ["화산"],
            "landslide": ["산사태"],
            "extreme_temp": ["폭염", "한파"],
            "drought": ["가뭄"],
        },
        "dead": ["사망", "숨져", "숨진", "부상", "사상자"],
        "arrest": ["체포", "검거", "구속"],
        "judicial": ["재판", "선고", "기소", "징역"],
        "noise": ["축구", "야구", "경기"],
    },
    "vi": {
        "search": "\"tấn công\" OR \"vụ nổ\" OR \"xả súng\" OR \"biểu tình\" OR \"bạo loạn\" OR \"bắt cóc\" OR \"đụng độ\" OR \"lũ lụt\" OR \"động đất\" OR \"tình trạng khẩn cấp\"",
        "cat": {
            "terrorism": ["khủng bố"],
            "attack": ["tấn công", "vụ nổ", "xả súng", "nổ súng", "đâm chém", "bắt cóc", "con tin", "đánh bom", "phóng hỏa"],
            "armed_conflict": ["không kích", "tên lửa", "máy bay không người lái", "giao tranh", "pháo kích"],
            "unrest": ["biểu tình", "bạo loạn", "đình công", "hơi cay", "xô xát"],
            "political": ["tình trạng khẩn cấp", "đảo chính", "thiết quân luật"],
            "crime": ["giết người", "cướp tài sản", "ma túy", "băng nhóm", "tống tiền"],
            "cyber": ["tấn công mạng", "tin tặc", "mã độc tống tiền"],
            "infrastructure": ["mất điện", "trật bánh", "sập cầu", "nổ khí gas"],
            "health": ["bùng phát dịch", "dịch bệnh", "ổ dịch", "dịch tả", "sốt xuất huyết", "bệnh sởi"],
            "earthquake": ["động đất"],
            "flood": ["lũ lụt", "lũ quét", "ngập lụt"],
            "cyclone": ["cơn bão", "siêu bão", "bão số", "áp thấp nhiệt đới"],
            "storm": ["lốc xoáy", "mưa đá", "dông lốc"],
            "wildfire": ["cháy rừng"],
            "volcano": ["núi lửa"],
            "landslide": ["sạt lở", "lở đất"],
            "extreme_temp": ["nắng nóng", "rét đậm", "rét hại"],
            "drought": ["hạn hán", "xâm nhập mặn"],
        },
        "dead": ["thiệt mạng", "tử vong", "bị thương", "người chết"],
        "arrest": ["bắt giữ", "bị bắt", "khởi tố"],
        "judicial": ["xét xử", "tuyên án", "phiên tòa"],
        "noise": ["bóng đá", "trận đấu"],
    },
    "ms": {   # malais (complète l'indonésien, très proche)
        "search": "serangan OR letupan OR tembakan OR \"tunjuk perasaan\" OR rusuhan OR culik OR pertempuran OR banjir OR \"gempa bumi\" OR darurat",
        "cat": {
            "terrorism": ["pengganas", "keganasan"],
            "attack": ["letupan", "tembakan", "ditembak", "ditikam", "diculik", "tebusan"],
            "armed_conflict": ["pertempuran", "serangan udara", "peluru berpandu", "dron"],
            "unrest": ["tunjuk perasaan", "rusuhan", "mogok"],
            "political": ["darurat", "rampasan kuasa"],
            "crime": ["pembunuhan", "rompakan", "dadah", "kongsi gelap", "peras ugut"],
            "cyber": ["serangan siber", "penggodam"],
            "infrastructure": ["gangguan bekalan elektrik", "terbabas", "runtuh"],
            "health": ["wabak", "denggi", "campak"],
            "earthquake": ["gempa bumi"],
            "flood": ["banjir kilat"],
            "storm": ["ribut", "puting beliung"],
            "wildfire": ["kebakaran hutan", "jerebu"],
            "landslide": ["tanah runtuh"],
            "extreme_temp": ["gelombang haba", "cuaca panas"],
            "drought": ["kemarau"],
        },
        "dead": ["maut", "terbunuh", "cedera", "parah"],
        "arrest": ["ditahan", "direman"],
        "judicial": ["mahkamah", "didakwa", "dijatuhi hukuman"],
        "noise": ["bola sepak", "liga super"],
    },
    "tl": {   # filipino
        "search": "pag-atake OR pagsabog OR pamamaril OR protesta OR kaguluhan OR dinukot OR sagupaan OR baha OR lindol OR \"state of calamity\"",
        "cat": {
            "terrorism": ["terorista", "terorismo"],
            "attack": ["pag-atake", "inatake", "pagsabog", "pamamaril", "binaril", "sinaksak", "dinukot", "pagdukot", "bihag",
                       "panununog"],
            "armed_conflict": ["sagupaan", "bakbakan", "engkuwentro"],
            "unrest": ["kilos-protesta", "kaguluhan", "welga"],
            "political": ["state of calamity", "batas militar", "kudeta"],
            "crime": ["pinatay", "pagpatay", "nakawan", "holdap", "iligal na droga"],
            "health": ["tigdas", "kolera"],
            "earthquake": ["lindol"],
            "flood": ["pagbaha", "baha"],
            "cyclone": ["bagyo"],
            "storm": ["buhawi"],
            "landslide": ["pagguho ng lupa", "guho"],
            "drought": ["tagtuyot"],
        },
        "dead": ["patay", "nasawi", "sugatan", "nasugatan"],
        "arrest": ["arestado", "inaresto", "timbog", "nadakip"],
        "judicial": ["hinatulan", "korte"],
        "noise": ["basketball", "pba"],
    },
    "my": {   # birman (sans espaces : recherche en sous-chaîne)
        "search": "တိုက်ခိုက် OR ပေါက်ကွဲ OR ပစ်ခတ် OR ဆန္ဒပြ OR ပြန်ပေးဆွဲ OR တိုက်ပွဲ OR ရေကြီး OR ငလျင်",
        "cat": {
            "terrorism": ["အကြမ်းဖက်"],
            "attack": ["တိုက်ခိုက်", "ပေါက်ကွဲ", "ပစ်ခတ်", "ပြန်ပေးဆွဲ", "ဗုံး", "မီးရှို့"],
            "armed_conflict": ["လေကြောင်းတိုက်ခိုက်", "တိုက်ပွဲ", "ဒရုန်း", "လက်နက်ကြီး"],
            "unrest": ["ဆန္ဒပြ", "သပိတ်"],
            "political": ["အရေးပေါ်အခြေအနေ", "အာဏာသိမ်း", "စစ်ဥပဒေ"],
            "crime": ["လူသတ်", "လုယက်", "မူးယစ်"],
            "health": ["ကာလဝမ်း", "ကူးစက်ရောဂါ", "သွေးလွန်တုပ်ကွေး"],
            "earthquake": ["ငလျင်"],
            "flood": ["ရေကြီး", "ရေလွှမ်း"],
            "cyclone": ["မုန်တိုင်း"],
            "landslide": ["မြေပြို"],
        },
        "dead": ["သေဆုံး", "ဒဏ်ရာ", "ကျဆုံး"],
        "arrest": ["ဖမ်းဆီး"],
        "judicial": ["တရားရုံး", "ထောင်ဒဏ်"],
        "noise": ["ဘောလုံး"],
    },
    "km": {   # khmer (sans espaces)
        "search": "វាយប្រហារ OR ផ្ទុះ OR បាញ់ OR បាតុកម្ម OR ចាប់ជំរិត OR ប៉ះទង្គិច OR ទឹកជំនន់ OR រញ្ជួយដី",
        "cat": {
            "terrorism": ["ភេរវកម្ម"],
            "attack": ["វាយប្រហារ", "ផ្ទុះ", "បាញ់សម្លាប់", "ចាប់ជំរិត", "គ្រាប់បែក"],
            "armed_conflict": ["ប៉ះទង្គិច", "ការបាញ់ផ្លោង"],
            "unrest": ["បាតុកម្ម", "កូដកម្ម"],
            "political": ["គ្រាអាសន្ន", "រដ្ឋប្រហារ"],
            "crime": ["ឃាតកម្ម", "ប្លន់", "គ្រឿងញៀន"],
            "health": ["ជំងឺរាតត្បាត", "គ្រុនឈាម"],
            "earthquake": ["រញ្ជួយដី"],
            "flood": ["ទឹកជំនន់", "ទឹកលិច"],
            "storm": ["ព្យុះ"],
            "landslide": ["ដីបាក់"],
            "drought": ["រាំងស្ងួត"],
        },
        "dead": ["ស្លាប់", "របួស"],
        "arrest": ["ចាប់ខ្លួន"],
        "judicial": ["តុលាការ"],
        "noise": ["បាល់ទាត់"],
    },
    # ---------------------------------------------------------------- Afrique
    "sw": {
        "search": "shambulio OR mlipuko OR risasi OR maandamano OR ghasia OR utekaji OR mapigano OR mafuriko OR \"tetemeko la ardhi\" OR \"hali ya hatari\"",
        "cat": {
            "terrorism": ["ugaidi", "magaidi"],
            "attack": ["shambulio", "mashambulizi", "kushambuliwa", "mlipuko", "milipuko", "kupigwa risasi", "utekaji", "kutekwa",
                       "mateka", "bomu"],
            "armed_conflict": ["mapigano", "vita vya", "waasi", "makombora"],
            "unrest": ["maandamano", "waandamanaji", "ghasia", "vurugu", "mgomo", "machafuko", "mabomu ya machozi"],
            "political": ["hali ya hatari", "mapinduzi", "amri ya kutotoka nje"],
            "crime": ["mauaji", "ujambazi", "majambazi", "dawa za kulevya"],
            "cyber": ["udukuzi"],
            "infrastructure": ["kukatika kwa umeme", "ajali ya treni", "kuporomoka"],
            "health": ["mlipuko wa ugonjwa", "kipindupindu", "surua"],
            "earthquake": ["tetemeko la ardhi"],
            "flood": ["mafuriko"],
            "cyclone": ["kimbunga"],
            "storm": ["dhoruba", "upepo mkali"],
            "wildfire": ["moto wa msitu"],
            "landslide": ["maporomoko ya ardhi"],
            "drought": ["ukame"],
        },
        "dead": ["wamefariki", "wameuawa", "waliuawa", "kuuawa", "wamejeruhiwa", "majeruhi"],
        "arrest": ["wakamatwa", "wamekamatwa", "kukamatwa", "mbaroni"],
        "judicial": ["mahakamani", "hukumu"],
        "noise": ["ligi kuu", "soka"],
    },
    "ha": {
        "search": "\"kai hari\" OR fashewa OR harbi OR zanga-zanga OR tarzoma OR garkuwa OR rikici OR ambaliya OR \"girgizar kasa\"",
        "cat": {
            "terrorism": ["ta'addanci", "'yan ta'adda"],
            "attack": ["kai hari", "harin", "fashewar", "harbe", "sace mutane", "garkuwa da mutane", "'yan bindiga"],
            "armed_conflict": ["rikicin", "yakin"],
            "unrest": ["zanga-zanga", "tarzoma", "yajin aiki"],
            "political": ["dokar ta-baci", "juyin mulki", "dokar hana fita"],
            "crime": ["kisan kai", "fashi da makami", "miyagun kwayoyi"],
            "health": ["annobar", "kwalara", "barkewar cuta"],
            "earthquake": ["girgizar kasa"],
            "flood": ["ambaliya", "ambaliyar ruwa"],
            "storm": ["guguwa"],
            "wildfire": ["gobara"],
        },
        "dead": ["sun mutu", "an kashe", "rasu", "jikkata", "raunuka"],
        "arrest": ["an kama", "cafke"],
        "judicial": ["kotun", "hukunci"],
        "noise": ["kwallon kafa"],
    },
}

# Éditions Google News (hl, gl, ceid) connues ; les autres langues passent par l'édition internationale (en-US)
# avec leurs propres mots-clés (la recherche site: + mots-clés fonctionne quelle que soit l'édition).
EDITIONS = {
    "ja": ("ja-JP", ("ja", "JP", "JP:ja")), "ko": ("ko-KR", ("ko", "KR", "KR:ko")), "vi": ("vi-VN", ("vi", "VN", "VN:vi")),
    "hi": ("hi-IN", ("hi", "IN", "IN:hi")), "ta": ("ta-IN", ("ta", "IN", "IN:ta")), "ro": ("ro-RO", ("ro", "RO", "RO:ro")),
    "hu": ("hu-HU", ("hu", "HU", "HU:hu")), "cs": ("cs-CZ", ("cs", "CZ", "CZ:cs")), "sk": ("sk-SK", ("sk", "SK", "SK:sk")),
    "el": ("el-GR", ("el", "GR", "GR:el")), "bg": ("bg-BG", ("bg", "BG", "BG:bg")), "sv": ("sv-SE", ("sv", "SE", "SE:sv")),
    "no": ("no-NO", ("no", "NO", "NO:no")), "lt": ("lt-LT", ("lt", "LT", "LT:lt")), "lv": ("lv-LV", ("lv", "LV", "LV:lv")),
    "sl": ("sl-SI", ("sl", "SI", "SI:sl")),
}


def words(field):
    """Tous les mots d'un champ (« dead », « arrest »…) pour toutes les langues."""
    return [w for spec in LANGS.values() for w in spec.get(field, [])]


def category_words():
    out = {}
    for spec in LANGS.values():
        for cat, ws in spec["cat"].items():
            out.setdefault(cat, []).extend(ws)
    return out
