"""Source du catalogue config/press_outlets.json (médias de référence par pays).

Format : ISO2 → liste de (nom, domaine[/chemin], langue[, "+"[, fiabilité]])
  langue    : langue des mots-clés de recherche (fr, en, es, pt, de, it, nl, pl, tr, ru, uk, ar, he, id,
              th, zh, bn, fa, ur, am, so)
  "+"       : média régional ou international → la requête ajoute le nom du pays ("" sinon)
  fiabilité : lettre de la grille de l'Amirauté (A à F) ; « B » par défaut
Critères : rédaction professionnelle identifiable, pas de relais de propagande d'État ;
dans les pays sans presse libre, médias indépendants en exil ou références internationales.
Regénérer : python tools/outlets_src.py
"""
import json
import re
from pathlib import Path

O = {
 # ---------------- Europe de l'Ouest
 "FR": [("Le Monde", "lemonde.fr", "fr"), ("Le Figaro", "lefigaro.fr", "fr"), ("Libération", "liberation.fr", "fr"), ("Franceinfo", "francetvinfo.fr", "fr"), ("Ouest-France", "ouest-france.fr", "fr")],
 "BE": [("Le Soir", "lesoir.be", "fr"), ("La Libre", "lalibre.be", "fr"), ("RTBF", "rtbf.be", "fr"), ("De Standaard", "standaard.be", "nl")],
 "LU": [("L'essentiel", "lessentiel.lu", "fr"), ("Luxembourg Times", "luxtimes.lu", "en"), ("Luxemburger Wort", "wort.lu", "de")],
 "CH": [("Le Temps", "letemps.ch", "fr"), ("RTS", "rts.ch", "fr"), ("NZZ", "nzz.ch", "de"), ("Swissinfo", "swissinfo.ch", "en")],
 "MC": [("Monaco-Matin", "monacomatin.mc", "fr"), ("Monaco Tribune", "monaco-tribune.com", "fr"), ("Nice-Matin", "nicematin.com", "fr", "+")],
 "DE": [("Der Spiegel", "spiegel.de", "de"), ("FAZ", "faz.net", "de"), ("Süddeutsche Zeitung", "sueddeutsche.de", "de"), ("Tagesschau", "tagesschau.de", "de")],
 "AT": [("Der Standard", "derstandard.at", "de"), ("Die Presse", "diepresse.com", "de"), ("ORF", "orf.at", "de")],
 "LI": [("Liechtensteiner Vaterland", "vaterland.li", "de"), ("Liechtensteiner Volksblatt", "volksblatt.li", "de"), ("NZZ", "nzz.ch", "de", "+")],
 "NL": [("NOS", "nos.nl", "nl"), ("NRC", "nrc.nl", "nl"), ("de Volkskrant", "volkskrant.nl", "nl")],
 "IT": [("Corriere della Sera", "corriere.it", "it"), ("la Repubblica", "repubblica.it", "it"), ("ANSA", "ansa.it", "it"), ("Il Sole 24 Ore", "ilsole24ore.com", "it")],
 "SM": [("San Marino RTV", "sanmarinortv.sm", "it"), ("Libertas", "libertas.sm", "it"), ("ANSA", "ansa.it", "it", "+")],
 "VA": [("Vatican News", "vaticannews.va", "en"), ("ANSA", "ansa.it", "it", "+"), ("Catholic News Agency", "catholicnewsagency.com", "en", "+")],
 "MT": [("Times of Malta", "timesofmalta.com", "en"), ("MaltaToday", "maltatoday.com.mt", "en"), ("Malta Independent", "independent.com.mt", "en")],
 "ES": [("El País", "elpais.com", "es"), ("El Mundo", "elmundo.es", "es"), ("La Vanguardia", "lavanguardia.com", "es"), ("RTVE", "rtve.es", "es")],
 "AD": [("Diari d'Andorra", "diariandorra.ad", "es"), ("Bondia", "bondia.ad", "es"), ("La Vanguardia", "lavanguardia.com", "es", "+")],
 "PT": [("Público", "publico.pt", "pt"), ("Expresso", "expresso.pt", "pt"), ("RTP", "rtp.pt", "pt"), ("Diário de Notícias", "dn.pt", "pt")],
 "GB": [("BBC News", "bbc.com", "en"), ("The Guardian", "theguardian.com", "en"), ("The Independent", "independent.co.uk", "en"), ("Financial Times", "ft.com", "en")],
 "IE": [("The Irish Times", "irishtimes.com", "en"), ("RTÉ", "rte.ie", "en"), ("Irish Independent", "independent.ie", "en")],
 "IS": [("RÚV English", "ruv.is", "en"), ("Iceland Review", "icelandreview.com", "en"), ("Reykjavík Grapevine", "grapevine.is", "en")],
 # ---------------- Europe du Nord et Baltes
 "DK": [("The Local Denmark", "thelocal.dk", "en"), ("The Copenhagen Post", "cphpost.dk", "en"), ("DR", "dr.dk", "en")],
 "SE": [("The Local Sweden", "thelocal.se", "en"), ("Sveriges Radio", "sverigesradio.se", "en"), ("SVT", "svt.se", "en")],
 "NO": [("The Local Norway", "thelocal.no", "en"), ("News in English", "newsinenglish.no", "en"), ("NRK", "nrk.no", "en")],
 "FI": [("Yle News", "yle.fi", "en"), ("Helsinki Times", "helsinkitimes.fi", "en"), ("Helsingin Sanomat", "hs.fi", "en")],
 "EE": [("ERR News", "news.err.ee", "en"), ("Postimees", "news.postimees.ee", "en"), ("Estonian World", "estonianworld.com", "en")],
 "LV": [("LSM", "lsm.lv", "en"), ("BNN", "bnn-news.com", "en"), ("The Baltic Times", "baltictimes.com", "en", "+")],
 "LT": [("LRT", "lrt.lt", "en"), ("Delfi", "delfi.lt", "en"), ("The Baltic Times", "baltictimes.com", "en", "+")],
 # ---------------- Europe centrale et orientale
 "PL": [("Rzeczpospolita", "rp.pl", "pl"), ("TVN24", "tvn24.pl", "pl"), ("Gazeta Wyborcza", "wyborcza.pl", "pl"), ("Notes from Poland", "notesfrompoland.com", "en")],
 "CZ": [("Radio Prague International", "radio.cz", "en"), ("Expats.cz", "expats.cz", "en"), ("Prague Morning", "praguemorning.cz", "en")],
 "SK": [("The Slovak Spectator", "spectator.sme.sk", "en"), ("TASR", "newsnow.tasr.sk", "en"), ("Denník N", "dennikn.sk", "en")],
 "HU": [("Telex", "telex.hu", "en"), ("Daily News Hungary", "dailynewshungary.com", "en"), ("Budapest Times", "budapesttimes.hu", "en")],
 "RO": [("Romania Insider", "romania-insider.com", "en"), ("HotNews", "hotnews.ro", "en"), ("Digi24", "digi24.ro", "en")],
 "BG": [("Novinite", "novinite.com", "en"), ("BTA", "bta.bg", "en"), ("The Sofia Globe", "sofiaglobe.com", "en")],
 "GR": [("Kathimerini", "ekathimerini.com", "en"), ("Greek Reporter", "greekreporter.com", "en"), ("Keep Talking Greece", "keeptalkinggreece.com", "en")],
 "CY": [("Cyprus Mail", "cyprus-mail.com", "en"), ("in-cyprus", "in-cyprus.philenews.com", "en"), ("Kathimerini Cyprus", "kathimerini.com.cy", "en")],
 "SI": [("RTV Slovenija", "rtvslo.si", "en"), ("Total Slovenia News", "total-slovenia-news.com", "en"), ("Slovenia Times", "sloveniatimes.com", "en")],
 "HR": [("Total Croatia News", "total-croatia-news.com", "en"), ("HINA", "hina.hr", "en"), ("Index.hr", "index.hr", "en")],
 "BA": [("Sarajevo Times", "sarajevotimes.com", "en"), ("N1 BiH", "n1info.ba", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "RS": [("N1 Serbia", "n1info.rs", "en"), ("Serbian Monitor", "serbianmonitor.com", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "ME": [("Vijesti", "vijesti.me", "en"), ("RTCG", "rtcg.me", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "MK": [("MIA", "mia.mk", "en"), ("Meta.mk", "meta.mk", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "AL": [("Exit News", "exit.al", "en"), ("Euronews Albania", "euronews.al", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "XK": [("Prishtina Insight", "prishtinainsight.com", "en"), ("Koha", "koha.net", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "UA": [("The Kyiv Independent", "kyivindependent.com", "en"), ("Ukrainska Pravda", "pravda.com.ua", "en"), ("Suspilne", "suspilne.media", "uk"), ("Ukrinform", "ukrinform.net", "en")],
 "BY": [("Belsat", "belsat.eu", "en"), ("Zerkalo", "zerkalo.io", "ru"), ("RFE/RL", "rferl.org", "en", "+")],
 "MD": [("NewsMaker", "newsmaker.md", "ru"), ("IPN", "ipn.md", "en"), ("Moldova.org", "moldova.org", "en")],
 "RU": [("Meduza", "meduza.io", "en"), ("The Moscow Times", "themoscowtimes.com", "en"), ("Novaya Gazeta Europe", "novayagazeta.eu", "en"), ("Kommersant", "kommersant.ru", "ru")],
 # ---------------- Caucase, Turquie, Asie centrale
 "GE": [("Civil.ge", "civil.ge", "en"), ("Interpressnews", "interpressnews.ge", "en"), ("OC Media", "oc-media.org", "en", "+")],
 "AM": [("Azatutyun (RFE/RL)", "azatutyun.am", "en"), ("CivilNet", "civilnet.am", "en"), ("OC Media", "oc-media.org", "en", "+")],
 "AZ": [("Turan", "turan.az", "en"), ("JAMnews", "jam-news.net", "en", "+"), ("OC Media", "oc-media.org", "en", "+")],
 "TR": [("Hürriyet Daily News", "hurriyetdailynews.com", "en"), ("Bianet", "bianet.org", "en"), ("T24", "t24.com.tr", "tr"), ("Cumhuriyet", "cumhuriyet.com.tr", "tr")],
 "KZ": [("The Times of Central Asia", "timesca.com", "en", "+"), ("Vlast.kz", "vlast.kz", "ru"), ("Orda.kz", "orda.kz", "ru")],
 "UZ": [("Kun.uz", "kun.uz", "en"), ("Gazeta.uz", "gazeta.uz", "en"), ("Daryo", "daryo.uz", "en")],
 "KG": [("24.kg", "24.kg", "en"), ("Kloop", "kloop.kg", "ru"), ("AKIpress", "akipress.com", "en")],
 "TJ": [("Asia-Plus", "asiaplustj.info", "en"), ("Ozodi (RFE/RL)", "ozodi.org", "ru"), ("The Times of Central Asia", "timesca.com", "en", "+")],
 "TM": [("Turkmen.news", "turkmen.news", "en"), ("Chronicles of Turkmenistan", "hronikatm.com", "en"), ("Azathabar (RFE/RL)", "azathabar.com", "ru")],
 # ---------------- Moyen-Orient
 "IL": [("The Times of Israel", "timesofisrael.com", "en"), ("Haaretz", "haaretz.com", "en"), ("Ynetnews", "ynetnews.com", "en"), ("The Jerusalem Post", "jpost.com", "en")],
 "PS": [("Al Jazeera", "aljazeera.com", "en", "+"), ("Middle East Eye", "middleeasteye.net", "en", "+"), ("+972 Magazine", "972mag.com", "en")],
 "LB": [("L'Orient-Le Jour", "lorientlejour.com", "fr"), ("Naharnet", "naharnet.com", "en"), ("An-Nahar", "annahar.com", "ar")],
 "SY": [("Enab Baladi", "enabbaladi.net", "en"), ("Syria Direct", "syriadirect.org", "en"), ("Al Jazeera", "aljazeera.com", "en", "+")],
 "JO": [("The Jordan Times", "jordantimes.com", "en"), ("Roya News", "royanews.tv", "en"), ("Ammon News", "ammonnews.net", "en")],
 "IQ": [("Shafaq News", "shafaq.com", "en"), ("Rudaw", "rudaw.net", "en"), ("Kurdistan24", "kurdistan24.net", "en")],
 "IR": [("IranWire", "iranwire.com", "en"), ("Iran International", "iranintl.com", "en"), ("Financial Tribune", "financialtribune.com", "en")],
 "SA": [("Arab News", "arabnews.com", "en"), ("Saudi Gazette", "saudigazette.com.sa", "en"), ("Asharq Al-Awsat", "english.aawsat.com", "en")],
 "AE": [("The National", "thenationalnews.com", "en"), ("Gulf News", "gulfnews.com", "en"), ("Khaleej Times", "khaleejtimes.com", "en")],
 "QA": [("The Peninsula", "thepeninsulaqatar.com", "en"), ("Gulf Times", "gulf-times.com", "en"), ("Doha News", "dohanews.co", "en")],
 "KW": [("Kuwait Times", "kuwaittimes.com", "en"), ("Arab Times", "arabtimesonline.com", "en"), ("Times Kuwait", "timeskuwait.com", "en")],
 "BH": [("Gulf Daily News", "gdnonline.com", "en"), ("News of Bahrain", "newsofbahrain.com", "en"), ("Al Ayam", "alayam.com", "ar")],
 "OM": [("Times of Oman", "timesofoman.com", "en"), ("Oman Observer", "omanobserver.om", "en"), ("Muscat Daily", "muscatdaily.com", "en")],
 "YE": [("Al Jazeera", "aljazeera.com", "en", "+"), ("Middle East Eye", "middleeasteye.net", "en", "+"), ("The New Arab", "newarab.com", "en", "+")],
 # ---------------- Afrique du Nord
 "EG": [("Mada Masr", "madamasr.com", "en"), ("Egypt Independent", "egyptindependent.com", "en"), ("Daily News Egypt", "dailynewsegypt.com", "en")],
 "LY": [("Libya Observer", "libyaobserver.ly", "en"), ("Libya Herald", "libyaherald.com", "en"), ("Al Wasat", "alwasat.ly", "ar")],
 "TN": [("La Presse", "lapresse.tn", "fr"), ("Business News", "businessnews.com.tn", "fr"), ("Kapitalis", "kapitalis.com", "fr")],
 "DZ": [("TSA Algérie", "tsa-algerie.com", "fr"), ("El Watan", "elwatan-dz.com", "fr"), ("Algérie 360", "algerie360.com", "fr")],
 "MA": [("TelQuel", "telquel.ma", "fr"), ("Médias24", "medias24.com", "fr"), ("Hespress", "hespress.com", "fr")],
 "MR": [("Cridem", "cridem.org", "fr"), ("Le Calame", "lecalame.info", "fr"), ("Alakhbar", "alakhbar.info", "fr")],
 "SD": [("Sudan Tribune", "sudantribune.com", "en"), ("Radio Dabanga", "dabangasudan.org", "en"), ("Radio Tamazuj", "radiotamazuj.org", "en", "+")],
 "SS": [("Radio Tamazuj", "radiotamazuj.org", "en"), ("Eye Radio", "eyeradio.org", "en"), ("Sudans Post", "sudanspost.com", "en")],
 # ---------------- Afrique de l'Est et Corne
 "ET": [("Addis Standard", "addisstandard.com", "en"), ("The Reporter", "thereporterethiopia.com", "en"), ("Addis Fortune", "addisfortune.news", "en")],
 "ER": [("BBC News", "bbc.com", "en", "+"), ("Africanews", "africanews.com", "en", "+"), ("The EastAfrican", "theeastafrican.co.ke", "en", "+")],
 "DJ": [("Jeune Afrique", "jeuneafrique.com", "fr", "+"), ("RFI", "rfi.fr", "fr", "+"), ("Africanews", "africanews.com", "fr", "+")],
 "SO": [("Hiiraan Online", "hiiraan.com", "en"), ("Garowe Online", "garoweonline.com", "en"), ("Somali Guardian", "somaliguardian.com", "en")],
 "KE": [("Nation", "nation.africa", "en"), ("The Standard", "standardmedia.co.ke", "en"), ("The Star", "the-star.co.ke", "en")],
 "UG": [("Daily Monitor", "monitor.co.ug", "en"), ("The Observer", "observer.ug", "en"), ("New Vision", "newvision.co.ug", "en")],
 "TZ": [("The Citizen", "thecitizen.co.tz", "en"), ("Daily News", "dailynews.co.tz", "en"), ("IPP Media", "ippmedia.com", "en")],
 "RW": [("The New Times", "newtimes.co.rw", "en"), ("KT Press", "ktpress.rw", "en"), ("IGIHE", "en.igihe.com", "en")],
 "BI": [("Iwacu", "iwacu-burundi.org", "fr"), ("Burundi Eco", "burundi-eco.com", "fr"), ("RFI", "rfi.fr", "fr", "+")],
 # ---------------- Afrique centrale
 "CD": [("Actualite.cd", "actualite.cd", "fr"), ("Radio Okapi", "radiookapi.net", "fr"), ("7sur7.cd", "7sur7.cd", "fr")],
 "CG": [("Les Dépêches de Brazzaville", "adiac-congo.com", "fr"), ("RFI", "rfi.fr", "fr", "+"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+")],
 "CF": [("Radio Ndeke Luka", "radiondekeluka.org", "fr"), ("Corbeau News", "corbeaunews-centrafrique.org", "fr"), ("RFI", "rfi.fr", "fr", "+")],
 "CM": [("Journal du Cameroun", "journalducameroun.com", "fr"), ("Actu Cameroun", "actucameroun.com", "fr"), ("Cameroon Tribune", "cameroon-tribune.cm", "fr")],
 "GA": [("Gabonreview", "gabonreview.com", "fr"), ("Gabonactu", "gabonactu.com", "fr"), ("Gabon Media Time", "gabonmediatime.com", "fr")],
 "GQ": [("Jeune Afrique", "jeuneafrique.com", "fr", "+"), ("RFI", "rfi.fr", "fr", "+"), ("Africanews", "africanews.com", "en", "+")],
 "TD": [("Alwihda Info", "alwihdainfo.com", "fr"), ("Tchadinfos", "tchadinfos.com", "fr"), ("Journal du Tchad", "journaldutchad.com", "fr")],
 "ST": [("Téla Nón", "telanon.info", "pt"), ("RFI", "rfi.fr", "fr", "+"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+")],
 # ---------------- Sahel et Afrique de l'Ouest
 "NE": [("ActuNiger", "actuniger.com", "fr"), ("aNiamey", "aniamey.com", "fr"), ("RFI", "rfi.fr", "fr", "+")],
 "ML": [("Maliweb", "maliweb.net", "fr"), ("Malijet", "malijet.com", "fr"), ("Studio Tamani", "studiotamani.org", "fr")],
 "BF": [("Lefaso.net", "lefaso.net", "fr"), ("Burkina24", "burkina24.com", "fr"), ("Le Pays", "lepays.bf", "fr")],
 "SN": [("Seneweb", "seneweb.com", "fr"), ("Dakaractu", "dakaractu.com", "fr"), ("Le Quotidien", "lequotidien.sn", "fr")],
 "GM": [("The Point", "thepoint.gm", "en"), ("Foroyaa", "foroyaa.net", "en"), ("The Standard", "standard.gm", "en")],
 "GW": [("O Democrata", "odemocratagb.com", "pt"), ("RFI", "rfi.fr", "fr", "+"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+")],
 "GN": [("Guinéenews", "guineenews.org", "fr"), ("Africaguinee", "africaguinee.com", "fr"), ("Mosaïque Guinée", "mosaiqueguinee.com", "fr")],
 "SL": [("Awoko", "awokonewspaper.sl", "en"), ("Sierraloaded", "sierraloaded.sl", "en"), ("Calabash", "thecalabashnewspaper.com", "en")],
 "LR": [("FrontPage Africa", "frontpageafricaonline.com", "en"), ("Liberian Observer", "liberianobserver.com", "en"), ("The New Dawn", "thenewdawnliberia.com", "en")],
 "CI": [("Linfodrome", "linfodrome.com", "fr"), ("Abidjan.net", "abidjan.net", "fr"), ("Fraternité Matin", "fratmat.info", "fr")],
 "GH": [("MyJoyOnline", "myjoyonline.com", "en"), ("Citi Newsroom", "citinewsroom.com", "en"), ("Graphic Online", "graphic.com.gh", "en")],
 "TG": [("icilome", "icilome.com", "fr"), ("Republicoftogo.com", "republicoftogo.com", "fr"), ("24heureinfo", "24heureinfo.com", "fr")],
 "BJ": [("La Nouvelle Tribune", "lanouvelletribune.info", "fr"), ("24 Heures au Bénin", "24haubenin.info", "fr"), ("Banouto", "banouto.bj", "fr")],
 "NG": [("Premium Times", "premiumtimesng.com", "en"), ("Punch", "punchng.com", "en"), ("TheCable", "thecable.ng", "en"), ("Vanguard", "vanguardngr.com", "en")],
 "CV": [("Expresso das Ilhas", "expressodasilhas.cv", "pt"), ("Inforpress", "inforpress.cv", "pt"), ("A Semana", "asemana.publ.cv", "pt")],
 # ---------------- Afrique australe et océan Indien
 "AO": [("Novo Jornal", "novojornal.co.ao", "pt"), ("Maka Angola", "makaangola.org", "pt"), ("Jornal de Angola", "jornaldeangola.ao", "pt")],
 "ZM": [("Lusaka Times", "lusakatimes.com", "en"), ("News Diggers", "diggers.news", "en"), ("Zambia Monitor", "zambiamonitor.com", "en")],
 "ZW": [("NewsDay", "newsday.co.zw", "en"), ("ZimLive", "zimlive.com", "en"), ("NewZimbabwe", "newzimbabwe.com", "en")],
 "MW": [("Nyasa Times", "nyasatimes.com", "en"), ("The Nation", "mwnation.com", "en"), ("Times 360", "times.mw", "en")],
 "MZ": [("Club of Mozambique", "clubofmozambique.com", "en"), ("Carta de Moçambique", "cartamz.com", "pt"), ("O País", "opais.co.mz", "pt")],
 "MG": [("L'Express de Madagascar", "lexpress.mg", "fr"), ("Midi Madagasikara", "midi-madagasikara.mg", "fr"), ("NewsMada", "newsmada.com", "fr")],
 "MU": [("L'Express", "lexpress.mu", "fr"), ("Defimedia", "defimedia.info", "fr"), ("Le Mauricien", "lemauricien.com", "fr")],
 "SC": [("Seychelles Nation", "nation.sc", "en"), ("Seychelles News Agency", "seychellesnewsagency.com", "en"), ("Today in Seychelles", "todayinseychelles.com", "en")],
 "KM": [("Al-Watwan", "alwatwan.net", "fr"), ("Comores Infos", "comoresinfos.net", "fr"), ("Habari za Comores", "habarizacomores.com", "fr")],
 "ZA": [("News24", "news24.com", "en"), ("Daily Maverick", "dailymaverick.co.za", "en"), ("TimesLIVE", "timeslive.co.za", "en"), ("IOL", "iol.co.za", "en")],
 "NA": [("The Namibian", "namibian.com.na", "en"), ("New Era", "neweralive.na", "en"), ("Namibian Sun", "namibiansun.com", "en")],
 "BW": [("Mmegi", "mmegi.bw", "en"), ("Sunday Standard", "sundaystandard.info", "en"), ("Weekend Post", "weekendpost.co.bw", "en")],
 "LS": [("Lesotho Times", "lestimes.com", "en"), ("The Post", "thepost.co.ls", "en"), ("Public Eye", "publiceyenews.com", "en")],
 "SZ": [("Times of Eswatini", "times.co.sz", "en"), ("Swaziland News", "swazilandnews.co.za", "en"), ("Africanews", "africanews.com", "en", "+")],
 # ---------------- Asie du Sud
 "AF": [("Amu TV", "amu.tv", "en"), ("TOLOnews", "tolonews.com", "en"), ("8am Media", "8am.media", "en")],
 "PK": [("Dawn", "dawn.com", "en"), ("The News", "thenews.com.pk", "en"), ("The Express Tribune", "tribune.com.pk", "en"), ("Geo News", "geo.tv", "en")],
 "IN": [("The Hindu", "thehindu.com", "en"), ("The Indian Express", "indianexpress.com", "en"), ("Hindustan Times", "hindustantimes.com", "en"), ("NDTV", "ndtv.com", "en")],
 "BD": [("The Daily Star", "thedailystar.net", "en"), ("The Business Standard", "tbsnews.net", "en"), ("bdnews24", "bdnews24.com", "en")],
 "LK": [("Daily Mirror", "dailymirror.lk", "en"), ("EconomyNext", "economynext.com", "en"), ("Sunday Times", "sundaytimes.lk", "en")],
 "NP": [("The Kathmandu Post", "kathmandupost.com", "en"), ("My Republica", "myrepublica.nagariknetwork.com", "en"), ("The Rising Nepal", "risingnepaldaily.com", "en")],
 "BT": [("Kuensel", "kuenselonline.com", "en"), ("The Bhutanese", "thebhutanese.bt", "en"), ("BBS", "bbs.bt", "en")],
 "MV": [("Sun", "sun.mv", "en"), ("Edition.mv", "edition.mv", "en"), ("PSM News", "psmnews.mv", "en")],
 # ---------------- Asie du Sud-Est
 "MM": [("The Irrawaddy", "irrawaddy.com", "en"), ("Mizzima", "mizzima.com", "en"), ("Frontier Myanmar", "frontiermyanmar.net", "en"), ("Myanmar Now", "myanmar-now.org", "en")],
 "TH": [("Bangkok Post", "bangkokpost.com", "en"), ("The Nation", "nationthailand.com", "en"), ("Thai PBS World", "thaipbsworld.com", "en"), ("Khaosod English", "khaosodenglish.com", "en")],
 "KH": [("Khmer Times", "khmertimeskh.com", "en"), ("Phnom Penh Post", "phnompenhpost.com", "en"), ("CamboJA News", "cambojanews.com", "en")],
 "LA": [("Laotian Times", "laotiantimes.com", "en"), ("Vientiane Times", "vientianetimes.gov.la", "en"), ("The Diplomat", "thediplomat.com", "en", "+")],
 "VN": [("VnExpress International", "e.vnexpress.net", "en"), ("Tuoi Tre News", "tuoitrenews.vn", "en"), ("Viet Nam News", "vietnamnews.vn", "en")],
 "MY": [("The Star", "thestar.com.my", "en"), ("Malaysiakini", "malaysiakini.com", "en"), ("Free Malaysia Today", "freemalaysiatoday.com", "en"), ("New Straits Times", "nst.com.my", "en")],
 "SG": [("The Straits Times", "straitstimes.com", "en"), ("CNA", "channelnewsasia.com", "en"), ("TODAY", "todayonline.com", "en")],
 "ID": [("The Jakarta Post", "thejakartapost.com", "en"), ("Tempo", "tempo.co", "en"), ("Kompas", "kompas.com", "id"), ("Antara", "antaranews.com", "en")],
 "PH": [("Philippine Daily Inquirer", "inquirer.net", "en"), ("Rappler", "rappler.com", "en"), ("Philstar", "philstar.com", "en"), ("GMA News", "gmanetwork.com", "en")],
 "TL": [("Tatoli", "tatoli.tl", "en"), ("ABC News", "abc.net.au", "en", "+"), ("The Diplomat", "thediplomat.com", "en", "+")],
 "BN": [("Borneo Bulletin", "borneobulletin.com.bn", "en"), ("The Scoop", "thescoop.co", "en"), ("The Star", "thestar.com.my", "en", "+")],
 # ---------------- Asie de l'Est
 "CN": [("South China Morning Post", "scmp.com", "en", "+"), ("Caixin Global", "caixinglobal.com", "en"), ("Reuters", "reuters.com", "en", "+")],
 "HK": [("Hong Kong Free Press", "hongkongfp.com", "en"), ("The Standard", "thestandard.com.hk", "en"), ("RTHK", "rthk.hk", "en")],
 "TW": [("Taipei Times", "taipeitimes.com", "en"), ("Focus Taiwan", "focustaiwan.tw", "en"), ("Taiwan News", "taiwannews.com.tw", "en")],
 "JP": [("The Japan Times", "japantimes.co.jp", "en"), ("The Mainichi", "mainichi.jp", "en"), ("The Asahi Shimbun", "asahi.com", "en"), ("NHK World", "nhk.or.jp", "en")],
 "KR": [("The Korea Herald", "koreaherald.com", "en"), ("Yonhap", "yna.co.kr", "en"), ("Korea JoongAng Daily", "koreajoongangdaily.joins.com", "en")],
 "KP": [("NK News", "nknews.org", "en"), ("Daily NK", "dailynk.com", "en"), ("38 North", "38north.org", "en")],
 "MN": [("Montsame", "montsame.mn", "en"), ("News.mn", "news.mn", "en"), ("Reuters", "reuters.com", "en", "+")],
 # ---------------- Amérique du Nord
 "US": [("The New York Times", "nytimes.com", "en"), ("The Washington Post", "washingtonpost.com", "en"), ("AP News", "apnews.com", "en"), ("NPR", "npr.org", "en")],
 "CA": [("CBC News", "cbc.ca", "en"), ("The Globe and Mail", "theglobeandmail.com", "en"), ("CTV News", "ctvnews.ca", "en"), ("La Presse", "lapresse.ca", "fr")],
 "MX": [("El Universal", "eluniversal.com.mx", "es"), ("Milenio", "milenio.com", "es"), ("Animal Político", "animalpolitico.com", "es"), ("Proceso", "proceso.com.mx", "es")],
 # ---------------- Amérique centrale et Caraïbes
 "GT": [("Prensa Libre", "prensalibre.com", "es"), ("Soy502", "soy502.com", "es"), ("La Hora", "lahora.gt", "es")],
 "BZ": [("Amandala", "amandala.com.bz", "en"), ("Breaking Belize News", "breakingbelizenews.com", "en"), ("7 News Belize", "7newsbelize.com", "en")],
 "HN": [("La Prensa", "laprensa.hn", "es"), ("El Heraldo", "elheraldo.hn", "es"), ("Proceso Digital", "proceso.hn", "es")],
 "SV": [("La Prensa Gráfica", "laprensagrafica.com", "es"), ("El Diario de Hoy", "elsalvador.com", "es"), ("El Faro", "elfaro.net", "es")],
 "NI": [("Confidencial", "confidencial.digital", "es"), ("La Prensa", "laprensani.com", "es"), ("100% Noticias", "100noticias.com.ni", "es")],
 "CR": [("La Nación", "nacion.com", "es"), ("CRHoy", "crhoy.com", "es"), ("The Tico Times", "ticotimes.net", "en")],
 "PA": [("La Prensa", "prensa.com", "es"), ("La Estrella de Panamá", "laestrella.com.pa", "es"), ("TVN", "tvn-2.com", "es")],
 "CU": [("14ymedio", "14ymedio.com", "es"), ("Diario de Cuba", "diariodecuba.com", "es"), ("elTOQUE", "eltoque.com", "es")],
 "HT": [("Le Nouvelliste", "lenouvelliste.com", "fr"), ("HaïtiLibre", "haitilibre.com", "fr"), ("AyiboPost", "ayibopost.com", "fr")],
 "DO": [("Diario Libre", "diariolibre.com", "es"), ("Listín Diario", "listindiario.com", "es"), ("El Caribe", "elcaribe.com.do", "es")],
 "JM": [("The Gleaner", "jamaica-gleaner.com", "en"), ("Jamaica Observer", "jamaicaobserver.com", "en"), ("Radio Jamaica News", "radiojamaicanewsonline.com", "en")],
 "TT": [("Trinidad Guardian", "guardian.co.tt", "en"), ("Newsday", "newsday.co.tt", "en"), ("Trinidad Express", "trinidadexpress.com", "en")],
 "BS": [("The Tribune", "tribune242.com", "en"), ("The Nassau Guardian", "thenassauguardian.com", "en"), ("EyeWitness News", "ewnews.com", "en")],
 "BB": [("Nation News", "nationnews.com", "en"), ("Barbados Today", "barbadostoday.bb", "en"), ("Barbados Advocate", "barbadosadvocate.com", "en")],
 "LC": [("St Lucia Times", "stluciatimes.com", "en"), ("The Voice", "thevoiceslu.com", "en"), ("St Lucia News Online", "stlucianewsonline.com", "en")],
 "GD": [("NOW Grenada", "nowgrenada.com", "en"), ("The New Today", "thenewtodaygrenada.com", "en"), ("GBN", "grenadabroadcast.com", "en")],
 "VC": [("iWitness News", "iwnsvg.com", "en"), ("Searchlight", "searchlight.vc", "en"), ("St Vincent Times", "stvincenttimes.com", "en")],
 "AG": [("Antigua Observer", "antiguaobserver.com", "en"), ("Antigua Newsroom", "antiguanewsroom.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "KN": [("SKNVibes", "sknvibes.com", "en"), ("The Observer", "thestkittsnevisobserver.com", "en"), ("WINN FM", "winnfm.com", "en")],
 "DM": [("Dominica News Online", "dominicanewsonline.com", "en"), ("Emo News", "emonewsdm.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "GY": [("Stabroek News", "stabroeknews.com", "en"), ("Kaieteur News", "kaieteurnewsonline.com", "en"), ("News Room", "newsroom.gy", "en")],
 "SR": [("Starnieuws", "starnieuws.com", "nl"), ("De Ware Tijd", "dwtonline.com", "nl"), ("Waterkant", "waterkant.net", "nl")],
 # ---------------- Amérique du Sud
 "CO": [("El Tiempo", "eltiempo.com", "es"), ("El Espectador", "elespectador.com", "es"), ("Semana", "semana.com", "es")],
 "VE": [("Efecto Cocuyo", "efectococuyo.com", "es"), ("El Pitazo", "elpitazo.net", "es"), ("Tal Cual", "talcualdigital.com", "es"), ("El Nacional", "elnacional.com", "es")],
 "EC": [("Primicias", "primicias.ec", "es"), ("El Comercio", "elcomercio.com", "es"), ("El Universo", "eluniverso.com", "es")],
 "PE": [("El Comercio", "elcomercio.pe", "es"), ("La República", "larepublica.pe", "es"), ("RPP", "rpp.pe", "es")],
 "BO": [("El Deber", "eldeber.com.bo", "es"), ("Los Tiempos", "lostiempos.com", "es"), ("Correo del Sur", "correodelsur.com", "es")],
 "BR": [("Folha de S.Paulo", "folha.uol.com.br", "pt"), ("g1", "g1.globo.com", "pt"), ("Estadão", "estadao.com.br", "pt"), ("O Globo", "oglobo.globo.com", "pt")],
 "PY": [("ABC Color", "abc.com.py", "es"), ("Última Hora", "ultimahora.com", "es"), ("La Nación", "lanacion.com.py", "es")],
 "UY": [("El País", "elpais.com.uy", "es"), ("El Observador", "elobservador.com.uy", "es"), ("la diaria", "ladiaria.com.uy", "es")],
 "AR": [("La Nación", "lanacion.com.ar", "es"), ("Clarín", "clarin.com", "es"), ("Infobae", "infobae.com", "es"), ("Página/12", "pagina12.com.ar", "es")],
 "CL": [("La Tercera", "latercera.com", "es"), ("Emol", "emol.com", "es"), ("BioBioChile", "biobiochile.cl", "es"), ("El Mostrador", "elmostrador.cl", "es")],
 # ---------------- Océanie
 "AU": [("ABC News", "abc.net.au", "en"), ("The Sydney Morning Herald", "smh.com.au", "en"), ("The Age", "theage.com.au", "en")],
 "NZ": [("RNZ", "rnz.co.nz", "en"), ("NZ Herald", "nzherald.co.nz", "en"), ("Stuff", "stuff.co.nz", "en")],
 "PG": [("Post-Courier", "postcourier.com.pg", "en"), ("The National", "thenational.com.pg", "en"), ("EMTV", "emtv.com.pg", "en")],
 "FJ": [("The Fiji Times", "fijitimes.com.fj", "en"), ("Fijivillage", "fijivillage.com", "en"), ("FBC News", "fbcnews.com.fj", "en")],
 "SB": [("Solomon Star", "solomonstarnews.com", "en"), ("SIBC", "sibconline.com.sb", "en"), ("Island Sun", "theislandsun.com.sb", "en")],
 "VU": [("Vanuatu Daily Post", "dailypost.vu", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+")],
 "NC": [("Les Nouvelles Calédoniennes", "lnc.nc", "fr"), ("NC la 1ère", "la1ere.francetvinfo.fr", "fr", "+"), ("Outremers360", "outremers360.com", "fr", "+")],
 "PF": [("TNTV", "tntv.pf", "fr"), ("Radio 1", "radio1.pf", "fr"), ("Polynésie la 1ère", "la1ere.francetvinfo.fr", "fr", "+")],
 "WS": [("Samoa Observer", "samoaobserver.ws", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+")],
 "TO": [("Matangi Tonga", "matangitonga.to", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+")],
 "KI": [("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "FM": [("Kaselehlie Press", "kpress.info", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "MH": [("Marshall Islands Journal", "marshallislandsjournal.com", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "PW": [("Island Times", "islandtimes.org", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "NR": [("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "TV": [("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 # ---------------- Territoires
 "PR": [("El Nuevo Día", "elnuevodia.com", "es"), ("Primera Hora", "primerahora.com", "es"), ("NotiCel", "noticel.com", "es")],
 "GU": [("Pacific Daily News", "guampdn.com", "en"), ("KUAM News", "kuam.com", "en"), ("The Guam Daily Post", "postguam.com", "en")],
 "MO": [("Macau Daily Times", "macaudailytimes.com.mo", "en"), ("Macau Business", "macaubusiness.com", "en"), ("Macau News Agency", "macaonews.org", "en")],
 "BM": [("The Royal Gazette", "royalgazette.com", "en"), ("Bernews", "bernews.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "KY": [("Cayman Compass", "caymancompass.com", "en"), ("Cayman News Service", "caymannewsservice.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "GL": [("Sermitsiaq", "sermitsiaq.ag", "en"), ("KNR", "knr.gl", "en"), ("Arctic Today", "arctictoday.com", "en", "+")],
}

# ---------------- Presse de 25 pays à risque (liste de Stef, presse_25_pays.csv, v0.9)
# (nom, site, langue des mots-clés, "+" si le nom du pays est ajouté, fiabilité Amirauté A-F), par priorité P1 → P3
PRESSE_25 = {
 "NE": [('Aïr Info', 'airinfoagadez.com', 'fr', '', 'B'), ('Studio Kalangou (Fondation Hirondelle)', 'studiokalangou.org', 'fr', '', 'B'), ("L'Événement Niger", 'levenementniger.com', 'fr', '', 'B'), ('Les Échos du Niger', 'lesechosduniger.com', 'fr', '', 'C'), ('aNiamey', 'news.aniamey.com', 'fr', '', 'C'), ('Labari Info (RTL Niger)', 'labarinfo.com', 'fr', '', 'C'), ('Le Sahel', 'lesahel.org', 'fr', '', 'D'), ('ANP – Agence nigérienne de presse', 'anp.ne', 'fr', '', 'D')],
 "BF": [("L'Observateur Paalga", 'lobservateur.bf', 'fr', '', 'C'), ("Aujourd'hui au Faso", 'aujourd8.net', 'fr', '', 'C'), ('Wakat Séra', 'wakatsera.com', 'fr', '', 'C'), ('Studio Yafa (Fondation Hirondelle)', 'studioyafa.org', 'fr', '', 'B'), ('Sidwaya', 'sidwaya.info', 'fr', '', 'D'), ("AIB – Agence d'information du Burkina", 'aib.media', 'fr', '', 'D')],
 "ML": [('Journal du Mali', 'journaldumali.com', 'fr', '', 'C'), ('Sahelien.com', 'sahelien.com', 'fr', '', 'C'), ('aBamako', 'news.abamako.com', 'fr', '', 'C'), ('Mali Actu', 'maliactu.net', 'fr', '', 'D'), ("L'Essor", 'lessormali.com', 'fr', '', 'D')],
 "TH": [('Prachatai English', 'prachatai.com/english', 'en', '', 'B'), ('Thairath', 'thairath.co.th', 'th', '', 'C'), ('Matichon', 'matichon.co.th', 'th', '', 'C'), ('Khaosod', 'khaosod.co.th', 'th', '', 'C')],
 "ID": [('Antara News', 'en.antaranews.com', 'en', '', 'C'), ('Detik.com', 'detik.com', 'id', '', 'C'), ('CNN Indonesia', 'cnnindonesia.com', 'id', '', 'C'), ('Jakarta Globe', 'jakartaglobe.id', 'en', '', 'C'), ('Liputan6', 'liputan6.com', 'id', '', 'C'), ('Republika', 'republika.co.id', 'id', '', 'C')],
 "CN": [('Hong Kong Free Press', 'hongkongfp.com', 'en', '', 'B'), ('China Digital Times', 'chinadigitaltimes.net', 'en', '', 'B'), ('The Standard (Hong Kong)', 'thestandard.com.hk', 'en', '', 'C'), ('The Paper (澎湃新闻)', 'thepaper.cn', 'zh', '', 'D'), ('Sixth Tone', 'sixthtone.com', 'en', '', 'D'), ('RTHK News', 'news.rthk.hk', 'en', '', 'D')],
 "AU": [('The Guardian Australia', 'theguardian.com/au', 'en', '', 'B'), ('SBS News', 'sbs.com.au/news', 'en', '', 'B'), ('news.com.au', 'news.com.au', 'en', '', 'C'), ('9News', '9news.com.au', 'en', '', 'C'), ('7NEWS', '7news.com.au', 'en', '', 'C'), ('The New Daily', 'thenewdaily.com.au', 'en', '', 'C'), ('The Conversation Australia', 'theconversation.com/au', 'en', '+', 'B')],
 "SD": [('Al-Taghyeer', 'altaghyeer.info', 'ar', '', 'C'), ('Ayin Network', '3ayin.com', 'en', '', 'B'), ('Darfur24', 'darfur24.com', 'en', '', 'C'), ('Sudan War Monitor', 'sudanwarmonitor.com', 'en', '', 'C'), ('Sudans Post', 'sudanspost.com', 'en', '+', 'C'), ('Alrakoba', 'alrakoba.net', 'ar', '', 'D'), ('SUNA', 'suna-sd.net', 'en', '', 'D')],
 "CD": [('Kivu Morning Post', 'kivumorningpost.com', 'fr', '', 'C'), ('Politico.cd', 'politico.cd', 'fr', '', 'C'), ('Studio Hirondelle RDC', 'studiohirondellerdc.org', 'fr', '', 'B'), ('Habari RDC', 'habarirdc.net', 'fr', '', 'C'), ('Mediacongo', 'mediacongo.net', 'fr', '', 'C')],
 "LB": [("NNA – Agence nationale d'information", 'nna-leb.gov.lb', 'en', '', 'C'), ('LBCI', 'lbcgroup.tv', 'en', '', 'C'), ('MTV Lebanon', 'mtv.com.lb', 'en', '', 'C'), ('Al Jadeed', 'aljadeed.tv', 'ar', '', 'C'), ('Nidaa al-Watan', 'nidaalwatan.com', 'ar', '', 'C'), ('Megaphone', 'megaphone.news', 'en', '', 'B')],
 "IL": [('Ynet', 'ynet.co.il', 'he', '', 'B'), ('i24NEWS', 'i24news.tv', 'en', '', 'C'), ('N12 (Mako)', 'mako.co.il', 'he', '', 'C'), ('Israel Hayom', 'israelhayom.com', 'en', '', 'C'), ('+972 Magazine', '972mag.com', 'en', '', 'C')],
 "ET": [('Ethiopia Insight', 'ethiopia-insight.com', 'en', '', 'B'), ('Wazema', 'wazemaradio.com', 'am', '', 'C'), ('Capital Ethiopia', 'capitalethiopia.com', 'en', '', 'C'), ('Borkena', 'borkena.com', 'en', '', 'D'), ('ENA – Ethiopian News Agency', 'ena.et', 'en', '', 'D')],
 "SY": [('Enab Baladi', 'english.enabbaladi.net', 'en', '', 'B'), ("SOHR – Observatoire syrien des droits de l'homme", 'syriahr.com/en', 'en', '', 'C'), ('The Syrian Observer', 'syrianobserver.com', 'en', '', 'C'), ('Zaman al-Wasl', 'zamanalwsl.net', 'ar', '', 'C'), ('Syria TV', 'syria.tv', 'ar', '', 'C'), ('North Press Agency', 'npasyria.com/en', 'en', '', 'D'), ('SANA', 'sana.sy/en', 'en', '', 'D')],
 "UA": [('Hromadske', 'hromadske.ua', 'uk', '', 'B'), ('UNIAN', 'unian.info', 'en', '', 'C'), ('RBC-Ukraine', 'newsukraine.rbc.ua', 'en', '', 'C'), ('LB.ua', 'lb.ua', 'uk', '', 'C'), ('Kyiv Post', 'kyivpost.com', 'en', '', 'B')],
 "MM": [('DVB – Democratic Voice of Burma', 'english.dvb.no', 'en', '', 'B'), ('Mizzima', 'eng.mizzima.com', 'en', '', 'C'), ('BNI – Burma News International', 'bnionline.net', 'en', '', 'B'), ('SHAN – Shan Herald Agency for News', 'english.shannews.org', 'en', '', 'C'), ('Narinjara', 'narinjara.com', 'en', '', 'C')],
 "CM": [('Mimi Mefo Info', 'mimimefoinfos.com', 'en', '', 'C'), ('The Guardian Post', 'theguardianpostcameroon.com', 'en', '', 'C'), ('Cameroon News Agency', 'cameroonnewsagency.com', 'en', '', 'C'), ('Datacameroon', 'datacameroon.com', 'fr', '', 'C')],
 "IR": [('Amwaj.media', 'amwaj.media', 'en', '+', 'B'), ('BBC Persian', 'bbc.com/persian', 'fa', '', 'B'), ('HRANA', 'en-hrana.org', 'en', '', 'C'), ('Hengaw', 'hengaw.net', 'en', '', 'C'), ('Radio Farda', 'radiofarda.com', 'fa', '', 'B'), ('Shargh', 'sharghdaily.com', 'fa', '', 'C'), ('Etemad', 'etemadonline.com', 'fa', '', 'C'), ('ISNA', 'en.isna.ir', 'en', '', 'D')],
 "SO": [('Caasimada', 'caasimada.net', 'so', '', 'C'), ('Radio Dalsan', 'radiodalsan.com', 'en', '', 'C'), ('Horseed Media', 'horseedmedia.net', 'en', '', 'C'), ('Horn Observer', 'hornobserver.com', 'en', '', 'C'), ('Horn Diplomat', 'horndiplomat.com', 'en', '', 'C'), ('SONNA', 'sonna.so', 'en', '', 'D')],
 "GB": [('BBC News', 'bbc.co.uk/news', 'en', '', 'B'), ('Sky News', 'news.sky.com', 'en', '', 'B'), ('Evening Standard', 'standard.co.uk', 'en', '', 'C'), ('Manchester Evening News', 'manchestereveningnews.co.uk', 'en', '', 'C'), ('Metro', 'metro.co.uk', 'en', '', 'C'), ('Daily Mirror', 'mirror.co.uk', 'en', '', 'C'), ('Daily Record', 'dailyrecord.co.uk', 'en', '', 'C'), ('Belfast Live', 'belfastlive.co.uk', 'en', '', 'C')],
 "PK": [('Business Recorder', 'brecorder.com', 'en', '', 'B'), ('Daily Jang', 'jang.com.pk', 'ur', '', 'C'), ('Pakistan Today', 'pakistantoday.com.pk', 'en', '', 'C'), ('Samaa', 'samaa.tv', 'en', '', 'C'), ('Daily Express (ourdou)', 'express.pk', 'ur', '', 'C'), ('The Balochistan Post', 'thebalochistanpost.net', 'en', '', 'D')],
 "NG": [('Daily Trust', 'dailytrust.com', 'en', '', 'B'), ('HumAngle', 'humanglemedia.com', 'en', '', 'B'), ('Channels TV', 'channelstv.com', 'en', '', 'B'), ('The Guardian Nigeria', 'guardian.ng', 'en', '', 'C'), ('ThisDay', 'thisdaylive.com', 'en', '', 'C'), ('Leadership', 'leadership.ng', 'en', '', 'C')],
 "RU": [('Mediazona', 'zona.media', 'en', '', 'B'), ('The Insider', 'theins.ru', 'en', '', 'B'), ('Verstka', 'verstka.media', 'ru', '', 'B'), ('7x7', 'semnasem.org', 'ru', '', 'C'), ('Sibir.Realii (RFE/RL)', 'sibreal.org', 'ru', '', 'B'), ('Fontanka.ru', 'fontanka.ru', 'ru', '', 'C'), ('Interfax', 'interfax.ru', 'ru', '', 'D')],
 "BD": [('Prothom Alo', 'prothomalo.com', 'en', '', 'B'), ('New Age', 'newagebd.net', 'en', '', 'B'), ('Dhaka Tribune', 'dhakatribune.com', 'en', '', 'C'), ('The Financial Express', 'thefinancialexpress.com.bd', 'en', '', 'C'), ('Kaler Kantho', 'kalerkantho.com', 'bn', '', 'C'), ('BSS', 'bssnews.net', 'en', '', 'D')],
 "MX": [('La Jornada', 'jornada.com.mx', 'es', '', 'C'), ('Excélsior', 'excelsior.com.mx', 'es', '', 'C'), ('Aristegui Noticias', 'aristeguinoticias.com', 'es', '', 'B'), ('Infobae México', 'infobae.com/mexico', 'es', '', 'C'), ('El Informador', 'informador.mx', 'es', '', 'C'), ('Zeta Tijuana', 'zetatijuana.com', 'es', '', 'B'), ('Ríodoce', 'riodoce.mx', 'es', '', 'B'), ('El Financiero', 'elfinanciero.com.mx', 'es', '', 'B')],
 "AF": [('KabulNow', 'kabulnow.com', 'en', '', 'B'), ('Etilaatroz', 'etilaatroz.com', 'fa', '', 'B'), ('Khaama Press', 'khaama.com', 'en', '', 'C'), ('Rukhshana Media', 'rukhshana.com', 'en', '', 'B'), ('Afghanistan International', 'afintl.com', 'en', '', 'D'), ('Ariana News', 'ariananews.af', 'en', '', 'D')],
}
# fiabilité (grille de l'Amirauté) des médias déjà présents au catalogue, d'après la même liste
FIABILITE = {"AF|8am.media": "B",
 "AF|amu.tv": "B",
 "AF|tolonews.com": "C",
 "AU|abc.net.au": "B",
 "BD|bdnews24.com": "C",
 "BD|tbsnews.net": "B",
 "BD|thedailystar.net": "B",
 "BF|burkina24.com": "C",
 "BF|lefaso.net": "C",
 "BF|lepays.bf": "C",
 "CD|7sur7.cd": "C",
 "CD|actualite.cd": "B",
 "CD|radiookapi.net": "B",
 "CM|actucameroun.com": "C",
 "CM|cameroon-tribune.cm": "D",
 "CM|journalducameroun.com": "C",
 "ET|addisfortune.news": "B",
 "ET|addisstandard.com": "B",
 "ET|thereporterethiopia.com": "C",
 "GB|independent.co.uk": "C",
 "GB|theguardian.com": "B",
 "ID|kompas.com": "B",
 "ID|tempo.co": "B",
 "IL|jpost.com": "C",
 "IL|timesofisrael.com": "B",
 "IL|ynetnews.com": "B",
 "IR|iranintl.com": "D",
 "IR|iranwire.com": "B",
 "LB|annahar.com": "B",
 "LB|naharnet.com": "C",
 "ML|maliweb.net": "C",
 "ML|studiotamani.org": "B",
 "MM|irrawaddy.com": "B",
 "MM|myanmar-now.org": "B",
 "MX|animalpolitico.com": "B",
 "MX|eluniversal.com.mx": "B",
 "MX|milenio.com": "C",
 "NE|actuniger.com": "C",
 "NG|premiumtimesng.com": "B",
 "NG|punchng.com": "B",
 "NG|thecable.ng": "B",
 "NG|vanguardngr.com": "C",
 "PK|dawn.com": "B",
 "PK|geo.tv": "C",
 "PK|thenews.com.pk": "C",
 "PK|tribune.com.pk": "B",
 "RU|kommersant.ru": "C",
 "RU|meduza.io": "B",
 "RU|novayagazeta.eu": "B",
 "RU|themoscowtimes.com": "B",
 "SD|dabangasudan.org": "B",
 "SD|sudantribune.com": "B",
 "SO|garoweonline.com": "C",
 "SO|hiiraan.com": "C",
 "SO|somaliguardian.com": "C",
 "SY|syriadirect.org": "B",
 "TH|bangkokpost.com": "B",
 "TH|khaosodenglish.com": "B",
 "TH|nationthailand.com": "C",
 "TH|thaipbsworld.com": "B",
 "UA|kyivindependent.com": "B",
 "UA|pravda.com.ua": "B",
 "UA|suspilne.media": "B",
 "UA|ukrinform.net": "C"}
for _iso, _items in PRESSE_25.items():  # ajoutés au catalogue du pays (sans doublon de domaine)
    _base = lambda d: re.sub(r"^(news|www|m|en|english|eng)\.", "", d.split("/")[0])  # news.aniamey.com ~ aniamey.com
    _known = {_base(o[1]) for o in O.get(_iso, [])}
    O.setdefault(_iso, []).extend(o for o in _items if _base(o[1]) not in _known)
for _iso, _items in O.items():
    for _i, _o in enumerate(_items):
        _l = FIABILITE.get(f"{_iso}|{_o[1].split('/')[0]}")
        if _l and len(_o) < 5:
            _items[_i] = tuple(_o) + (("",) if len(_o) == 3 else ()) + (_l,)

# ---------------------------------------------------------------- ajouts v0.25 (octobre 2026)
# Presse nationale et régionale en langue locale, médias en exil, agences : recherche documentaire assistée,
# domaines vérifiés par recherche web quand ils étaient incertains. 5e champ : fiabilité (B référence, C presse
# correcte mais moins établie ou partisane, D média d'État ou aligné sur un pouvoir autoritaire).
# Un domaine qui ne donne jamais de résultat est signalé par le robot (« médias muets », État des sources).
AJOUTS_V25 = {
 "AE": [("Al Khaleej", "alkhaleej.ae", "ar", "", "C"), ("Emarat Al Youm", "emaratalyoum.com", "ar", "", "C"), ("WAM", "wam.ae", "en", "", "D")],
 "AF": [("BBC Pashto", "bbc.com/pashto", "ps", "", "B")],
 "AL": [("Top Channel", "top-channel.tv", "sq", "", "B"), ("Reporter.al (BIRN)", "reporter.al", "sq", "", "B"), ("BalkanWeb", "balkanweb.com", "sq", "", "C")],
 "AM": [("Armenpress", "armenpress.am", "hy", "", "C"), ("News.am", "news.am", "hy", "", "C"), ("Hetq", "hetq.am", "hy", "", "B"), ("Aravot", "aravot.am", "hy", "", "C"), ("Panorama.am", "panorama.am", "hy", "", "C"), ("JAMnews", "jam-news.net", "en", "+", "B")],
 "AO": [("Club-K", "club-k.net", "pt", "", "C"), ("Expansão", "expansao.co.ao", "pt", "", "C"), ("DW África (português)", "dw.com/pt-002", "pt", "+", "B")],
 "AR": [("Perfil", "perfil.com", "es", "", "B"), ("TN", "tn.com.ar", "es", "", "B"), ("La Capital (Rosario)", "lacapital.com.ar", "es", "", "B"), ("Rosario3", "rosario3.com", "es", "", "C"), ("La Voz (Córdoba)", "lavoz.com.ar", "es", "", "B"), ("Los Andes (Mendoza)", "losandes.com.ar", "es", "", "B"), ("Río Negro", "rionegro.com.ar", "es", "", "B")],
 "AT": [("Kurier", "kurier.at", "de", "", "B"), ("Kleine Zeitung (Graz)", "kleinezeitung.at", "de", "", "B"), ("Kronen Zeitung", "krone.at", "de", "", "C")],
 "AU": [("AAP", "aap.com.au", "en", "", "B"), ("The West Australian", "thewest.com.au", "en", "", "C"), ("Brisbane Times", "brisbanetimes.com.au", "en", "", "B")],
 "AZ": [("Meydan TV", "meydan.tv", "az", "", "B"), ("Azadliq Radiosu (RFE/RL)", "azadliq.org", "az", "", "B"), ("APA", "apa.az", "az", "", "D"), ("Report.az", "report.az", "az", "", "D"), ("Trend", "trend.az", "en", "", "D")],
 "BA": [("Klix.ba", "klix.ba", "sh", "", "B"), ("Oslobođenje", "oslobodjenje.ba", "sh", "", "B"), ("Dnevni avaz", "avaz.ba", "sh", "", "C"), ("Nezavisne novine (Banja Luka)", "nezavisne.com", "sh", "", "B"), ("Detektor (BIRN BiH)", "detektor.ba", "sh", "", "B"), ("CIN", "cin.ba", "sh", "", "B")],
 "BD": [("Prothom Alo English", "en.prothomalo.com", "en", "", "B"), ("BBC Bangla", "bbc.com/bengali", "bn", "", "B")],
 "BE": [("VRT NWS", "vrt.be/vrtnws/nl", "nl", "", "B"), ("HLN", "hln.be", "nl", "", "C"), ("Sudinfo", "sudinfo.be", "fr", "", "C")],
 "BF": [("RFI", "rfi.fr", "fr", "+", "B"), ("Le Monde Afrique", "lemonde.fr/afrique", "fr", "+", "B")],
 "BG": [("Dnevnik", "dnevnik.bg", "bg", "", "B"), ("BNT", "bnt.bg", "bg", "", "B"), ("Mediapool", "mediapool.bg", "bg", "", "B")],
 "BH": [("Akhbar Al Khaleej", "akhbar-alkhaleej.com", "ar", "", "C"), ("BNA", "bna.bh", "en", "", "D")],
 "BI": [("SOS Médias Burundi", "sosmediasburundi.org", "fr", "", "B"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+", "B")],
 "BJ": [("Matin Libre", "matinlibre.com", "fr", "", "C"), ("Fraternité", "fraternitebj.info", "fr", "", "C"), ("Bénin Web TV", "beninwebtv.com", "fr", "", "C")],
 "BO": [("Opinión", "opinion.com.bo", "es", "", "B"), ("Unitel", "unitel.bo", "es", "", "B"), ("Red Uno", "reduno.com.bo", "es", "", "C"), ("Brújula Digital", "brujuladigital.net", "es", "", "B"), ("Erbol", "erbol.com.bo", "es", "", "B"), ("Urgente.bo", "urgente.bo", "es", "", "C")],
 "BR": [("Extra (Rio)", "extra.globo.com", "pt", "", "C"), ("CNN Brasil", "cnnbrasil.com.br", "pt", "", "B"), ("Agência Brasil", "agenciabrasil.ebc.com.br", "pt", "", "B"), ("Metrópoles", "metropoles.com", "pt", "", "C"), ("Correio (Bahia)", "correio24horas.com.br", "pt", "", "B"), ("A Tarde (Bahia)", "atarde.com.br", "pt", "", "B"), ("O Povo (Ceará)", "opovo.com.br", "pt", "", "B"), ("Diário do Nordeste (Ceará)", "diariodonordeste.verdesmares.com.br", "pt", "", "B"), ("A Crítica (Amazonas)", "acritica.com", "pt", "", "C"), ("O Liberal (Pará)", "oliberal.com", "pt", "", "C"), ("GZH (Rio Grande do Sul)", "gauchazh.clicrbs.com.br", "pt", "", "B"), ("Ponte Jornalismo", "ponte.org", "pt", "", "B"), ("Amazônia Real", "amazoniareal.com.br", "pt", "", "B")],
 "BW": [("The Voice Botswana", "thevoicebw.com", "en", "", "C"), ("Daily News (BOPA)", "dailynews.gov.bw", "en", "", "C")],
 "BY": [("Pozirk", "pozirk.online", "ru", "", "B"), ("Reform.news", "reform.news", "ru", "", "B"), ("Belarusian Partisan", "belaruspartisan.by", "ru", "", "C"), ("BelTA", "belta.by", "ru", "", "D")],
 "BZ": [("News 5 (Greater Belize Media)", "greaterbelize.com", "en", "", "B")],
 "CA": [("Radio-Canada", "ici.radio-canada.ca", "fr", "", "B"), ("Global News", "globalnews.ca", "en", "", "B"), ("Toronto Star", "thestar.com", "en", "", "B"), ("Le Devoir", "ledevoir.com", "fr", "", "B"), ("TVA Nouvelles", "tvanouvelles.ca", "fr", "", "C"), ("National Post", "nationalpost.com", "en", "", "B"), ("Vancouver Sun", "vancouversun.com", "en", "", "B"), ("Calgary Herald", "calgaryherald.com", "en", "", "B")],
 "CD": [("La Libre Afrique", "afrique.lalibre.be", "fr", "+", "B"), ("La Prunelle RDC", "laprunellerdc.info", "fr", "", "C"), ("BBC News Swahili", "bbc.com/swahili", "sw", "+", "B")],
 "CF": [("Oubangui Médias", "oubanguimedias.com", "fr", "", "C"), ("Journal de Bangui", "journaldebangui.com", "fr", "", "C"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+", "B")],
 "CG": [("Africanews", "africanews.com", "fr", "+", "B")],
 "CH": [("SRF", "srf.ch", "de", "", "B"), ("RSI", "rsi.ch", "it", "", "B")],
 "CI": [("Koaci", "koaci.com", "fr", "", "C"), ("AIP – Agence ivoirienne de presse", "aip.ci", "fr", "", "C"), ("7info", "7info.ci", "fr", "", "C"), ("Connectionivoirienne", "connectionivoirienne.net", "fr", "", "C")],
 "CL": [("Cooperativa", "cooperativa.cl", "es", "", "B"), ("24 Horas (TVN)", "24horas.cl", "es", "", "B"), ("T13", "t13.cl", "es", "", "B"), ("CIPER", "ciperchile.cl", "es", "", "B"), ("SoyChile (réseau régional)", "soychile.cl", "es", "", "C")],
 "CM": [("Cameroon-Info.net", "cameroon-info.net", "fr", "", "C"), ("StopBlaBlaCam", "stopblablacam.com", "fr", "", "C"), ("RFI", "rfi.fr", "fr", "+", "B")],
 "CN": [("BBC News 中文", "bbc.com/zhongwen", "zh", "", "B"), ("端传媒 Initium", "theinitium.com", "zh", "+", "B"), ("DW 中文", "dw.com/zh", "zh", "", "B"), ("RFI 中文", "rfi.fr/cn", "zh", "", "B"), ("中国数字时代", "chinadigitaltimes.net/chinese", "zh", "", "B"), ("财新网 Caixin", "caixin.com", "zh", "", "C"), ("Phayul (Tibet)", "phayul.com", "en", "", "C"), ("新华网 Xinhua", "news.cn", "zh", "", "D")],
 "CO": [("El Colombiano (Antioquia)", "elcolombiano.com", "es", "", "B"), ("El País Cali (Valle)", "elpais.com.co", "es", "", "B"), ("La Opinión (Cúcuta/Catatumbo)", "laopinion.com.co", "es", "", "B"), ("El Heraldo (Barranquilla)", "elheraldo.co", "es", "", "B"), ("Vanguardia (Santander)", "vanguardia.com", "es", "", "B"), ("Caracol Radio", "caracol.com.co", "es", "", "B"), ("Blu Radio", "bluradio.com", "es", "", "B"), ("Noticias Caracol", "noticias.caracoltv.com", "es", "", "B"), ("Verdad Abierta", "verdadabierta.com", "es", "", "B"), ("La Silla Vacía", "lasillavacia.com", "es", "", "B")],
 "CR": [("Teletica", "teletica.com", "es", "", "B"), ("Diario Extra", "diarioextra.com", "es", "", "C"), ("Delfino", "delfino.cr", "es", "", "B")],
 "CU": [("CubaNet", "cubanet.org", "es", "", "C"), ("CiberCuba", "cibercuba.com", "es", "", "C"), ("Cubadebate", "cubadebate.cu", "es", "", "D")],
 "CY": [("Philenews", "philenews.com", "el", "", "B"), ("Politis", "politis.com.cy", "el", "", "B"), ("Kıbrıs Postası (Nord)", "kibrispostasi.com", "tr", "", "C")],
 "CZ": [("ČT24", "ct24.ceskatelevize.cz", "cs", "", "B"), ("iROZHLAS", "irozhlas.cz", "cs", "", "B"), ("Seznam Zprávy", "seznamzpravy.cz", "cs", "", "B"), ("iDNES.cz", "idnes.cz", "cs", "", "B")],
 "DE": [("Die Zeit", "zeit.de", "de", "", "B"), ("Die Welt", "welt.de", "de", "", "B"), ("Der Tagesspiegel (Berlin)", "tagesspiegel.de", "de", "", "B"), ("rbb24 (Berlin-Brandenburg)", "rbb24.de", "de", "", "B"), ("BR24 (Bayern)", "br.de", "de", "", "B"), ("NDR (Norddeutschland)", "ndr.de", "de", "", "B"), ("WDR (Nordrhein-Westfalen)", "wdr.de", "de", "", "B"), ("MDR (Mitteldeutschland)", "mdr.de", "de", "", "B"), ("SWR (Südwesten)", "swr.de", "de", "", "B")],
 "DJ": [("Human Village", "human-village.org", "fr", "", "C"), ("La Nation", "lanation.dj", "fr", "", "D")],
 "DK": [("Politiken", "politiken.dk", "da", "", "B"), ("Berlingske", "berlingske.dk", "da", "", "B"), ("Jyllands-Posten", "jp.dk", "da", "", "B"), ("TV 2 Nyheder", "nyheder.tv2.dk", "da", "", "B"), ("Ekstra Bladet", "ekstrabladet.dk", "da", "", "C"), ("Fyens Stiftstidende", "fyens.dk", "da", "", "C")],
 "DO": [("Hoy", "hoy.com.do", "es", "", "B"), ("N Digital", "n.com.do", "es", "", "C"), ("El Nuevo Diario", "elnuevodiario.com.do", "es", "", "C")],
 "DZ": [("El Khabar", "elkhabar.com", "ar", "", "C"), ("Echorouk", "echoroukonline.com", "ar", "", "C"), ("Ennahar", "ennaharonline.com", "ar", "", "C"), ("Le Soir d'Algérie", "lesoirdalgerie.com", "fr", "", "C"), ("APS – Algérie Presse Service", "aps.dz", "fr", "", "D")],
 "EC": [("Expreso (Guayaquil)", "expreso.ec", "es", "", "B"), ("Extra", "extra.ec", "es", "", "C"), ("El Diario (Manabí)", "eldiario.ec", "es", "", "C"), ("La Hora", "lahora.com.ec", "es", "", "B"), ("Ecuavisa", "ecuavisa.com", "es", "", "B"), ("Teleamazonas", "teleamazonas.com", "es", "", "B"), ("GK", "gk.city", "es", "", "B")],
 "EE": [("ERR (estonien)", "err.ee", "et", "", "B"), ("Postimees", "postimees.ee", "et", "", "B"), ("Delfi Eesti", "delfi.ee", "et", "", "B"), ("Õhtuleht", "ohtuleht.ee", "et", "", "C"), ("ERR (russe)", "rus.err.ee", "ru", "", "B")],
 "EG": [("Mada Masr (arabe)", "madamasr.com/ar", "ar", "", "B"), ("Al Manassa", "almanassa.com", "ar", "", "B"), ("Al-Masry Al-Youm", "almasryalyoum.com", "ar", "", "C"), ("Shorouk News", "shorouknews.com", "ar", "", "C"), ("Masrawy", "masrawy.com", "ar", "", "C"), ("Youm7", "youm7.com", "ar", "", "D"), ("Ahram Online", "english.ahram.org.eg", "en", "", "D")],
 "ER": [("Awate", "awate.com", "en", "", "C"), ("Asmarino Independent", "asmarino.com", "en", "", "C"), ("Eritrea Hub", "eritreahub.org", "en", "", "C"), ("Shabait (ministère de l'Information)", "shabait.com", "en", "", "D")],
 "ES": [("ABC", "abc.es", "es", "", "B"), ("Europa Press", "europapress.es", "es", "", "B"), ("elDiario.es", "eldiario.es", "es", "", "B"), ("El Periódico (Barcelona)", "elperiodico.com", "es", "", "B"), ("El Correo (País Vasco)", "elcorreo.com", "es", "", "B"), ("La Voz de Galicia", "lavozdegalicia.es", "es", "", "B"), ("Diario de Sevilla", "diariodesevilla.es", "es", "", "B"), ("Levante-EMV (Valencia)", "levante-emv.com", "es", "", "B"), ("Canarias7", "canarias7.es", "es", "", "B")],
 "ET": [("BBC News Amharic", "bbc.com/amharic", "am", "", "B"), ("DW Amharic", "dw.com/am", "am", "", "B"), ("Zehabesha", "zehabesha.com", "en", "", "C")],
 "FI": [("MTV Uutiset", "mtvuutiset.fi", "fi", "", "B"), ("Iltalehti", "iltalehti.fi", "fi", "", "C"), ("Ilta-Sanomat", "is.fi", "fi", "", "C"), ("Aamulehti (Tampere)", "aamulehti.fi", "fi", "", "B"), ("Turun Sanomat", "ts.fi", "fi", "", "B"), ("Kaleva (Oulu)", "kaleva.fi", "fi", "", "B"), ("Hufvudstadsbladet", "hbl.fi", "sv", "", "B")],
 "FJ": [("RNZ Pacific", "rnz.co.nz", "en", "+", "B"), ("Islands Business", "islandsbusiness.com", "en", "+", "B")],
 "FR": [("Le Parisien", "leparisien.fr", "fr", "", "B"), ("BFMTV", "bfmtv.com", "fr", "", "B"), ("La Dépêche du Midi", "ladepeche.fr", "fr", "", "B"), ("Sud Ouest", "sudouest.fr", "fr", "", "B"), ("La Provence", "laprovence.com", "fr", "", "B"), ("Le Progrès", "leprogres.fr", "fr", "", "B"), ("La Voix du Nord", "lavoixdunord.fr", "fr", "", "B"), ("Le Dauphiné Libéré", "ledauphine.com", "fr", "", "B"), ("Nice-Matin", "nicematin.com", "fr", "", "B"), ("Dernières Nouvelles d'Alsace", "dna.fr", "fr", "", "B"), ("Corse-Matin", "corsematin.com", "fr", "", "B"), ("Actu.fr", "actu.fr", "fr", "", "C")],
 "GA": [("L'Union", "union.sonapresse.com", "fr", "", "C"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+", "B")],
 "GB": [("The Herald (Scotland)", "heraldscotland.com", "en", "", "B"), ("Belfast Telegraph", "belfasttelegraph.co.uk", "en", "", "B"), ("WalesOnline", "walesonline.co.uk", "en", "", "C"), ("Birmingham Mail", "birminghammail.co.uk", "en", "", "C"), ("Liverpool Echo", "liverpoolecho.co.uk", "en", "", "C")],
 "GE": [("Netgazeti", "netgazeti.ge", "ka", "", "B"), ("Publika", "publika.ge", "ka", "", "B"), ("Radio Tavisupleba (RFE/RL)", "radiotavisupleba.ge", "ka", "", "B"), ("Formula", "formulanews.ge", "ka", "", "C"), ("JAMnews", "jam-news.net", "en", "+", "B"), ("Georgia Today", "georgiatoday.ge", "en", "", "C")],
 "GH": [("GhanaWeb", "ghanaweb.com", "en", "", "C"), ("3News", "3news.com", "en", "", "C"), ("Ghana News Agency", "gna.org.gh", "en", "", "C"), ("Modern Ghana", "modernghana.com", "en", "", "C"), ("The Fourth Estate", "thefourthestategh.com", "en", "", "B")],
 "GM": [("Kerr Fatou", "kerrfatou.com", "en", "", "C")],
 "GN": [("Guinée360", "guinee360.com", "fr", "", "C"), ("Guinéematin", "guineematin.com", "fr", "", "C"), ("Vision Guinée", "visionguinee.info", "fr", "", "C"), ("RFI", "rfi.fr", "fr", "+", "B")],
 "GQ": [("Diario Rombe", "diariorombe.es", "es", "", "B"), ("Ahora EG", "ahoraeg.com", "es", "", "C"), ("Guinea Ecuatorial Press", "guineaecuatorialpress.com", "es", "", "D")],
 "GR": [("Kathimerini (GR)", "kathimerini.gr", "el", "", "B"), ("ERT News", "ertnews.gr", "el", "", "B"), ("ANA-MPA (AMNA)", "amna.gr", "el", "", "B"), ("Efimerida ton Syntakton", "efsyn.gr", "el", "", "B"), ("Proto Thema", "protothema.gr", "el", "", "C"), ("Voria.gr (Thessaloniki)", "voria.gr", "el", "", "C"), ("CretaLive (Crète)", "cretalive.gr", "el", "", "C")],
 "GT": [("Emisoras Unidas", "emisorasunidas.com", "es", "", "B"), ("Publinews", "publinews.gt", "es", "", "C"), ("República", "republica.gt", "es", "", "C"), ("Plaza Pública", "plazapublica.com.gt", "es", "", "B"), ("Agencia Ocote", "agenciaocote.com", "es", "", "B"), ("No-Ficción", "no-ficcion.com", "es", "", "B")],
 "GW": [("DW África (português)", "dw.com/pt-002", "pt", "+", "B")],
 "GY": [("Demerara Waves", "demerarawaves.com", "en", "", "C"), ("Guyana Chronicle", "guyanachronicle.com", "en", "", "C")],
 "HK": [("South China Morning Post", "scmp.com", "en", "", "B"), ("明報 Ming Pao", "news.mingpao.com", "zh", "", "B"), ("香港01 HK01", "hk01.com", "zh", "", "C"), ("端传媒 Initium", "theinitium.com", "zh", "+", "B"), ("獨立媒體 InMedia", "inmediahk.net", "zh", "", "C")],
 "HN": [("La Tribuna", "latribuna.hn", "es", "", "C"), ("Criterio.hn", "criterio.hn", "es", "", "B"), ("Contracorriente", "contracorriente.red", "es", "", "B"), ("HCH", "hch.tv", "es", "", "C"), ("Tu Nota", "tunota.com", "es", "", "C")],
 "HR": [("Jutarnji list", "jutarnji.hr", "sh", "", "B"), ("Večernji list", "vecernji.hr", "sh", "", "B"), ("HRT Vijesti", "vijesti.hrt.hr", "sh", "", "B")],
 "HT": [("AlterPresse", "alterpresse.org", "fr", "", "B"), ("Radio Télévision Caraïbes", "radiotelevisioncaraibes.com", "fr", "", "C"), ("Gazette Haïti", "gazettehaiti.com", "fr", "", "C"), ("Le National", "lenational.org", "fr", "", "C"), ("Juno7", "juno7.ht", "fr", "", "C"), ("The Haitian Times", "haitiantimes.com", "en", "", "B")],
 "HU": [("HVG", "hvg.hu", "hu", "", "B"), ("444", "444.hu", "hu", "", "B"), ("24.hu", "24.hu", "hu", "", "C"), ("Index", "index.hu", "hu", "", "C"), ("Szabad Európa (RFE/RL)", "szabadeuropa.hu", "hu", "", "B"), ("Népszava", "nepszava.hu", "hu", "", "C")],
 "ID": [("BBC News Indonesia", "bbc.com/indonesia", "id", "", "B"), ("Kompas.id", "kompas.id", "id", "", "B"), ("Tempo English", "en.tempo.co", "en", "", "B"), ("Antara English", "en.antaranews.com", "en", "", "C"), ("Jubi (Papua)", "jubi.id", "id", "", "B"), ("Suara Papua", "suarapapua.com", "id", "", "C"), ("Serambi Indonesia (Aceh)", "serambinews.com", "id", "", "C"), ("Tribun Timur (Sulawesi)", "makassar.tribunnews.com", "id", "", "C")],
 "IE": [("TheJournal.ie", "thejournal.ie", "en", "", "B"), ("Irish Examiner", "irishexaminer.com", "en", "", "B"), ("BreakingNews.ie", "breakingnews.ie", "en", "", "C")],
 "IL": [("Haaretz (hébreu)", "haaretz.co.il", "he", "", "B")],
 "IN": [("The Times of India", "timesofindia.indiatimes.com", "en", "", "C"), ("PTI", "ptinews.com", "en", "", "B"), ("The Tribune (Punjab, J&K)", "tribuneindia.com", "en", "", "B"), ("Greater Kashmir", "greaterkashmir.com", "en", "", "C"), ("Imphal Free Press (Manipur)", "ifp.co.in", "en", "", "C"), ("The Hitavada (Chhattisgarh/MP)", "thehitavada.com", "en", "", "C"), ("Dainik Bhaskar", "bhaskar.com", "hi", "", "C"), ("Amar Ujala", "amarujala.com", "hi", "", "C"), ("BBC Hindi", "bbc.com/hindi", "hi", "", "B"), ("Daily Thanthi", "dailythanthi.com", "ta", "", "C")],
 "IQ": [("Shafaq News (arabe)", "shafaq.com/ar", "ar", "", "C"), ("Alsumaria News", "alsumaria.tv", "ar", "", "C"), ("Al Mada", "almadapaper.net", "ar", "", "B"), ("Baghdad Today", "baghdadtoday.news", "ar", "", "C"), ("NINA – National Iraqi News Agency", "ninanews.com", "ar", "", "C"), ("Rudaw (arabe)", "rudaw.net/arabic", "ar", "", "C"), ("KirkukNow", "kirkuknow.com/en", "en", "", "B"), ("INA – Iraqi News Agency", "ina.iq", "ar", "", "D")],
 "IT": [("La Stampa", "lastampa.it", "it", "", "B"), ("Il Messaggero", "ilmessaggero.it", "it", "", "B"), ("RaiNews", "rainews.it", "it", "", "B"), ("Sky TG24", "tg24.sky.it", "it", "", "B"), ("Il Mattino (Napoli)", "ilmattino.it", "it", "", "B"), ("La Nazione (Firenze)", "lanazione.it", "it", "", "B"), ("Il Giorno (Milano)", "ilgiorno.it", "it", "", "B"), ("LiveSicilia", "livesicilia.it", "it", "", "C")],
 "JM": [("Nationwide News Network", "nationwideradiojm.com", "en", "", "C")],
 "JO": [("Al Ghad", "alghad.com", "ar", "", "B"), ("Al Rai", "alrai.com", "ar", "", "C"), ("Al Mamlaka", "almamlakatv.com", "ar", "", "C"), ("Khaberni", "khaberni.com", "ar", "", "C"), ("Petra", "petra.gov.jo", "ar", "", "D")],
 "JP": [("The Asahi Shimbun (AJW)", "asahi.com/ajw", "en", "", "B"), ("The Mainichi (English)", "mainichi.jp/english", "en", "", "B"), ("Kyodo News", "english.kyodonews.net", "en", "", "B"), ("NHK ニュース", "news.web.nhk", "ja", "", "B"), ("読売新聞", "yomiuri.co.jp", "ja", "", "B"), ("時事通信", "jiji.com", "ja", "", "B"), ("日本経済新聞", "nikkei.com", "ja", "", "B"), ("沖縄タイムス", "okinawatimes.co.jp", "ja", "", "B"), ("北海道新聞", "hokkaido-np.co.jp", "ja", "", "B")],
 "KE": [("Capital FM", "capitalfm.co.ke", "en", "", "B"), ("Citizen Digital", "citizen.digital", "en", "", "B"), ("Kenyans.co.ke", "kenyans.co.ke", "en", "", "C"), ("The Eastleigh Voice", "eastleighvoice.co.ke", "en", "", "C"), ("Taifa Leo", "taifaleo.nation.co.ke", "sw", "", "B"), ("BBC News Swahili", "bbc.com/swahili", "sw", "+", "B")],
 "KG": [("Azattyk (RFE/RL)", "rus.azattyk.org", "ru", "", "B"), ("Kaktus Media", "kaktus.media", "ru", "", "C"), ("Kabar", "kabar.kg", "ru", "", "D")],
 "KH": [("Cambodianess", "cambodianess.com", "en", "", "B"), ("Thmey Thmey", "thmeythmey.com", "km", "", "C"), ("Fresh News", "freshnewsasia.com", "km", "", "D")],
 "KP": [("Daily NK (English)", "dailynk.com/english", "en", "", "B"), ("KCNA Watch", "kcnawatch.org", "en", "", "D")],
 "KR": [("Yonhap (English)", "en.yna.co.kr", "en", "", "B"), ("The Korea Times", "koreatimes.co.kr", "en", "", "B"), ("한겨레 Hankyoreh", "hani.co.kr", "ko", "", "B"), ("조선일보 Chosun Ilbo", "chosun.com", "ko", "", "B"), ("중앙일보 JoongAng", "joongang.co.kr", "ko", "", "B"), ("KBS 뉴스", "news.kbs.co.kr", "ko", "", "B"), ("부산일보 Busan Ilbo", "busan.com", "ko", "", "B")],
 "KW": [("Al Qabas", "alqabas.com", "ar", "", "C"), ("Al Rai", "alraimedia.com", "ar", "", "C"), ("KUNA", "kuna.net.kw", "en", "", "D")],
 "KZ": [("Tengrinews", "tengrinews.kz", "ru", "", "C"), ("Azattyq (RFE/RL)", "rus.azattyq.org", "ru", "", "B"), ("Informburo", "informburo.kz", "ru", "", "C"), ("KazTAG", "kaztag.kz", "ru", "", "C"), ("Zakon.kz", "zakon.kz", "ru", "", "C"), ("Uralskaya Nedelya (Ouest)", "uralskweek.kz", "ru", "", "B"), ("Kazinform", "inform.kz", "ru", "", "D")],
 "LA": [("KPL Lao News Agency", "kpl.gov.la", "en", "", "D"), ("Bangkok Post", "bangkokpost.com", "en", "+", "B")],
 "LB": [("L'Orient Today", "lorientoday.com", "en", "", "B")],
 "LK": [("Ada Derana", "adaderana.lk", "en", "", "C"), ("Newsfirst", "newsfirst.lk", "en", "", "C"), ("The Island", "island.lk", "en", "", "C"), ("Tamil Guardian (Nord/Est)", "tamilguardian.com", "en", "", "C"), ("Virakesari", "virakesari.lk", "ta", "", "C")],
 "LR": [("The Bush Chicken", "bushchicken.com", "en", "", "B"), ("Smart News Liberia", "smartnewsliberia.com", "en", "", "C")],
 "LT": [("15min", "15min.lt", "lt", "", "B"), ("BNS", "bns.lt", "lt", "", "B"), ("Lietuvos rytas", "lrytas.lt", "lt", "", "C"), ("Diena (Kaunas)", "diena.lt", "lt", "", "C"), ("Klaipėda", "kl.lt", "lt", "", "C")],
 "LU": [("RTL Today", "today.rtl.lu", "en", "", "B"), ("Virgule", "virgule.lu", "fr", "", "C")],
 "LV": [("Delfi Latvija", "delfi.lv", "lv", "", "B"), ("TVNET", "tvnet.lv", "lv", "", "B"), ("LETA", "leta.lv", "lv", "", "B"), ("LSM (russe)", "rus.lsm.lv", "ru", "", "B"), ("Latvijas Avīze", "la.lv", "lv", "", "C")],
 "LY": [("Libya Review", "libyareview.com", "en", "", "C"), ("Al Marsad", "almarsad.co", "ar", "", "C"), ("218 News", "218tv.net", "ar", "", "C"), ("Libya Al-Ahrar", "libyaalahrar.net", "ar", "", "C"), ("Ean Libya", "eanlibya.com", "ar", "", "C")],
 "MA": [("Le360", "le360.ma", "fr", "", "C"), ("Hespress FR", "fr.hespress.com", "fr", "", "C"), ("Le Desk", "ledesk.ma", "fr", "", "B"), ("Yabiladi", "yabiladi.com", "fr", "", "C"), ("Alyaoum24", "alyaoum24.com", "ar", "", "C")],
 "MD": [("Ziarul de Gardă", "zdg.md", "ro", "", "B"), ("Agora", "agora.md", "ro", "", "B"), ("TV8", "tv8.md", "ro", "", "B"), ("Nokta (Gagauzia)", "nokta.md", "ru", "", "B"), ("Point.md", "point.md", "ru", "", "C"), ("Unimedia", "unimedia.info", "ro", "", "C")],
 "ME": [("CdM", "cdm.me", "sh", "", "B"), ("Pobjeda", "pobjeda.me", "sh", "", "C")],
 "MG": [("Madagascar Tribune", "madagascar-tribune.com", "fr", "", "C"), ("2424.mg", "2424.mg", "fr", "", "C"), ("La Gazette de la Grande Île", "lagazette-dgi.com", "fr", "", "C")],
 "MK": [("Sloboden Pečat", "slobodenpecat.mk", "mk", "", "B"), ("360 Stepeni", "360stepeni.mk", "mk", "", "B"), ("SDK.mk", "sdk.mk", "mk", "", "C")],
 "ML": [("RFI", "rfi.fr", "fr", "+", "B"), ("Le Monde Afrique", "lemonde.fr/afrique", "fr", "+", "B"), ("Bamada.net", "bamada.net", "fr", "", "C")],
 "MM": [("BBC News Burmese", "bbc.com/burmese", "my", "", "B"), ("DVB (birman)", "burmese.dvb.no", "my", "", "B"), ("The Irrawaddy (birman)", "burma.irrawaddy.com", "my", "", "B"), ("Development Media Group (Rakhine)", "dmediag.com", "en", "", "B"), ("Kachin News Group", "kachinnews.com", "en", "", "B"), ("Kachin News Group (birman)", "burmese.kachinnews.com", "my", "", "B"), ("Karen News", "karennews.org", "en", "", "C")],
 "MN": [("Ikon.mn", "ikon.mn", "mn", "", "B"), ("Gogo.mn", "gogo.mn", "mn", "", "C")],
 "MO": [("Hoje Macau", "hojemacau.com.mo", "pt", "", "C"), ("論盡媒體 All About Macau", "aamacau.com", "zh", "", "B")],
 "MR": [("Sahara Medias", "saharamedias.net", "ar", "", "C"), ("AMI – Agence mauritanienne d'information", "ami.mr", "fr", "", "D")],
 "MT": [("Newsbook", "newsbook.com.mt", "en", "", "C")],
 "MV": [("Sun (anglais)", "en.sun.mv", "en", "", "C"), ("Atoll Times", "atolltimes.mv", "en", "", "C")],
 "MW": [("Malawi24", "malawi24.com", "en", "", "C"), ("Zodiak Online", "zodiakmalawi.com", "en", "", "C")],
 "MX": [("Reforma", "reforma.com", "es", "", "B"), ("El Norte", "elnorte.com", "es", "", "B"), ("Noroeste (Sinaloa)", "noroeste.com.mx", "es", "", "B"), ("El Sur de Acapulco (Guerrero)", "suracapulco.mx", "es", "", "B"), ("Quadratín Michoacán", "quadratin.com.mx", "es", "", "C"), ("La Voz de Michoacán", "lavozdemichoacan.com.mx", "es", "", "C"), ("El Diario de Juárez", "diario.mx", "es", "", "B"), ("El Diario de Chihuahua", "eldiariodechihuahua.mx", "es", "", "C"), ("Expreso (Tamaulipas)", "expreso.press", "es", "", "C"), ("El Mañana (Nuevo Laredo)", "elmanana.com", "es", "", "C"), ("AM (Guanajuato)", "am.com.mx", "es", "", "C"), ("Periódico Correo (Guanajuato)", "periodicocorreo.com.mx", "es", "", "C"), ("El Sol de Zacatecas", "oem.com.mx/elsoldezacatecas", "es", "", "C"), ("El Imparcial (Sonora)", "elimparcial.com", "es", "", "C"), ("El Siglo de Torreón", "elsiglodetorreon.com.mx", "es", "", "B"), ("Pie de Página", "piedepagina.mx", "es", "", "B"), ("Chiapas Paralelo", "chiapasparalelo.com", "es", "", "C"), ("Noticaribe (Quintana Roo)", "noticaribe.com.mx", "es", "", "C")],
 "MY": [("Bernama", "bernama.com", "en", "", "C"), ("Malay Mail", "malaymail.com", "en", "", "B"), ("Berita Harian", "bharian.com.my", "ms", "", "B"), ("Astro Awani", "astroawani.com", "ms", "", "B"), ("Sin Chew Daily", "sinchew.com.my", "zh", "", "B"), ("Daily Express (Sabah)", "dailyexpress.com.my", "en", "", "B"), ("The Borneo Post (Sarawak)", "theborneopost.com", "en", "", "B")],
 "MZ": [("Zitamar News", "zitamar.com", "en", "", "B"), ("@Verdade", "verdade.co.mz", "pt", "", "C"), ("MZNews", "mznews.co.mz", "pt", "", "C"), ("DW África (português)", "dw.com/pt-002", "pt", "+", "B"), ("Notícias", "jornalnoticias.co.mz", "pt", "", "D")],
 "NA": [("Windhoek Observer", "observer24.com.na", "en", "", "C"), ("Informanté", "informante.web.na", "en", "", "C")],
 "NC": [("RRB – Radio Rythme Bleu", "rrb.nc", "fr", "", "C"), ("Caledonia", "caledonia.nc", "fr", "", "C")],
 "NE": [("BBC News Hausa", "bbc.com/hausa", "ha", "+", "B")],
 "NG": [("BBC News Hausa", "bbc.com/hausa", "ha", "", "B"), ("RFI Hausa", "rfi.fr/ha", "ha", "", "B"), ("Sahara Reporters", "saharareporters.com", "en", "", "C"), ("Daily Post Nigeria", "dailypost.ng", "en", "", "C"), ("The Nation", "thenationonlineng.net", "en", "", "C"), ("Daily Nigerian (Kano)", "dailynigerian.com", "en", "", "C"), ("Nigerian Tribune", "tribuneonlineng.com", "en", "", "C"), ("Foundation for Investigative Journalism", "fij.ng", "en", "", "B")],
 "NI": [("Divergentes", "divergentes.com", "es", "", "B"), ("Despacho 505", "despacho505.com", "es", "", "B"), ("Artículo 66", "articulo66.com", "es", "", "C"), ("Nicaragua Investiga", "nicaraguainvestiga.com", "es", "", "C"), ("El 19 Digital", "el19digital.com", "es", "", "D")],
 "NL": [("NU.nl", "nu.nl", "nl", "", "B"), ("De Telegraaf", "telegraaf.nl", "nl", "", "C"), ("Rijnmond (Rotterdam)", "rijnmond.nl", "nl", "", "B")],
 "NO": [("VG", "vg.no", "no", "", "B"), ("Aftenposten", "aftenposten.no", "no", "", "B"), ("TV 2", "tv2.no", "no", "", "B"), ("Dagbladet", "dagbladet.no", "no", "", "C"), ("Bergens Tidende", "bt.no", "no", "", "B"), ("Adresseavisen (Trondheim)", "adressa.no", "no", "", "B"), ("Nordlys (Tromsø)", "nordlys.no", "no", "", "B")],
 "NP": [("Kantipur", "ekantipur.com", "ne", "", "B"), ("Onlinekhabar", "onlinekhabar.com", "ne", "", "C"), ("Setopati", "setopati.com", "ne", "", "C"), ("Ratopati", "ratopati.com", "ne", "", "C"), ("The Himalayan Times", "thehimalayantimes.com", "en", "", "C"), ("Nepali Times", "nepalitimes.com", "en", "", "B")],
 "NZ": [("1News", "1news.co.nz", "en", "", "B"), ("Newsroom", "newsroom.co.nz", "en", "", "B"), ("Otago Daily Times", "odt.co.nz", "en", "", "B"), ("The Press", "thepress.co.nz", "en", "", "B")],
 "OM": [("Atheer", "atheer.om", "ar", "", "C"), ("Al Shabiba", "shabiba.com", "ar", "", "C")],
 "PA": [("Panamá América", "panamaamerica.com.pa", "es", "", "C"), ("Telemetro", "telemetro.com", "es", "", "B"), ("Crítica", "critica.com.pa", "es", "", "C")],
 "PE": [("Perú21", "peru21.pe", "es", "", "C"), ("Correo", "diariocorreo.pe", "es", "", "C"), ("Gestión", "gestion.pe", "es", "", "B"), ("Canal N", "canaln.pe", "es", "", "B"), ("Infobae Perú", "infobae.com/peru", "es", "", "C"), ("Ojo Público", "ojo-publico.com", "es", "", "B"), ("IDL-Reporteros", "idl-reporteros.pe", "es", "", "B"), ("Andina (agence d'État)", "andina.pe", "es", "", "C")],
 "PF": [("Tahiti Infos", "tahiti-infos.com", "fr", "", "B")],
 "PG": [("NBC News PNG", "nbc.com.pg", "en", "", "C"), ("RNZ Pacific", "rnz.co.nz", "en", "+", "B"), ("ABC Pacific", "abc.net.au", "en", "+", "B")],
 "PH": [("ABS-CBN News", "abs-cbn.com/news", "en", "", "B"), ("Manila Bulletin", "mb.com.ph", "en", "", "B"), ("MindaNews", "mindanews.com", "en", "", "B"), ("SunStar", "sunstar.com.ph", "en", "", "B"), ("Bombo Radyo", "bomboradyo.com", "tl", "", "C"), ("Abante", "abante.com.ph", "tl", "", "C")],
 "PK": [("BBC Urdu", "bbc.com/urdu", "ur", "", "B"), ("TNN – Tribal News Network (KP)", "tnnenglish.com", "en", "", "C")],
 "PL": [("PAP", "pap.pl", "pl", "", "B"), ("Polsat News", "polsatnews.pl", "pl", "", "B"), ("OKO.press", "oko.press", "pl", "", "B"), ("Polskie Radio", "polskieradio.pl", "pl", "", "B"), ("Trojmiasto.pl (Gdańsk)", "trojmiasto.pl", "pl", "", "C"), ("Kurier Lubelski", "kurierlubelski.pl", "pl", "", "C")],
 "PR": [("Centro de Periodismo Investigativo", "periodismoinvestigativo.com", "es", "", "B"), ("Telemundo Puerto Rico", "telemundopr.com", "es", "", "C"), ("Metro Puerto Rico", "metro.pr", "es", "", "C")],
 "PS": [("WAFA", "wafa.ps", "ar", "", "C"), ("Ma'an News", "maannews.net", "ar", "", "C"), ("Al-Quds", "alquds.com", "ar", "", "C"), ("Al-Ayyam (Ramallah)", "al-ayyam.ps", "ar", "", "C"), ("Arab48", "arab48.com", "ar", "", "B")],
 "PT": [("Observador", "observador.pt", "pt", "", "B"), ("Jornal de Notícias (Porto)", "jn.pt", "pt", "", "B"), ("Correio da Manhã", "cmjornal.pt", "pt", "", "C")],
 "PY": [("Hoy", "hoy.com.py", "es", "", "C"), ("NPY", "npy.com.py", "es", "", "C"), ("Agencia IP", "ip.gov.py", "es", "", "C")],
 "QA": [("Al Raya", "raya.com", "ar", "", "C"), ("Al Sharq", "al-sharq.com", "ar", "", "C"), ("QNA", "qna.org.qa", "en", "", "D")],
 "RO": [("Agerpres", "agerpres.ro", "ro", "", "B"), ("G4Media", "g4media.ro", "ro", "", "B"), ("Adevărul", "adevarul.ro", "ro", "", "B"), ("Știrile ProTV", "stirileprotv.ro", "ro", "", "B"), ("Libertatea", "libertatea.ro", "ro", "", "C"), ("Ziarul de Iași", "ziaruldeiasi.ro", "ro", "", "C"), ("Monitorul de Cluj", "monitorulcj.ro", "ro", "", "C")],
 "RS": [("Danas", "danas.rs", "sh", "", "B"), ("Nova.rs", "nova.rs", "sh", "", "B"), ("KRIK", "krik.rs", "sh", "", "B"), ("B92", "b92.net", "sh", "", "C"), ("Blic", "blic.rs", "sh", "", "C"), ("021.rs (Novi Sad)", "021.rs", "sh", "", "B"), ("Južne vesti (Niš)", "juznevesti.com", "sh", "", "B")],
 "RU": [("Kavkazsky Uzel (Caucasian Knot)", "kavkaz-uzel.eu", "ru", "", "B"), ("Idel.Realii (RFE/RL)", "idelreal.org", "ru", "", "B"), ("Sever.Realii (RFE/RL)", "severreal.org", "ru", "", "B"), ("TV Rain (Dozhd)", "tvrain.tv", "ru", "", "B"), ("Agentstvo", "agents.media", "ru", "", "B"), ("TASS", "tass.ru", "ru", "", "D")],
 "RW": [("Taarifa", "taarifa.rw", "en", "", "C"), ("The Chronicles", "chronicles.rw", "en", "", "C")],
 "SA": [("Okaz", "okaz.com.sa", "ar", "", "C"), ("Al Riyadh", "alriyadh.com", "ar", "", "C"), ("Sabq", "sabq.org", "ar", "", "C"), ("Al Arabiya", "alarabiya.net", "ar", "", "C"), ("SPA – Saudi Press Agency", "spa.gov.sa", "ar", "", "D")],
 "SD": [("Radio Dabanga (arabe)", "dabangasudan.org/ar", "ar", "", "B"), ("Sudan Tribune (arabe)", "sudantribune.net", "ar", "", "B")],
 "SE": [("Dagens Nyheter", "dn.se", "sv", "", "B"), ("Svenska Dagbladet", "svd.se", "sv", "", "B"), ("Aftonbladet", "aftonbladet.se", "sv", "", "C"), ("Expressen", "expressen.se", "sv", "", "C"), ("Göteborgs-Posten", "gp.se", "sv", "", "B"), ("Sydsvenskan (Malmö)", "sydsvenskan.se", "sv", "", "B")],
 "SG": [("联合早报 Lianhe Zaobao", "zaobao.com.sg", "zh", "", "B"), ("Berita Harian Singapura", "beritaharian.sg", "ms", "", "B"), ("Mothership", "mothership.sg", "en", "", "C")],
 "SI": [("24ur", "24ur.com", "sl", "", "C"), ("Delo", "delo.si", "sl", "", "B"), ("STA", "sta.si", "sl", "", "B")],
 "SK": [("SME", "sme.sk", "sk", "", "B"), ("Aktuality.sk", "aktuality.sk", "sk", "", "B"), ("TASR", "tasr.sk", "sk", "", "B")],
 "SL": [("Sierra Leone Telegraph", "thesierraleonetelegraph.com", "en", "", "C"), ("Politico SL", "politicosl.com", "en", "", "C")],
 "SN": [("PressAfrik", "pressafrik.com", "fr", "", "C"), ("Senego", "senego.com", "fr", "", "C"), ("SeneNews", "senenews.com", "fr", "", "C"), ("Le Soleil", "lesoleil.sn", "fr", "", "C"), ("APS – Agence de presse sénégalaise", "aps.sn", "fr", "", "C")],
 "SO": [("BBC News Somali", "bbc.com/somali", "so", "", "B"), ("Goobjoog News", "goobjoog.com", "so", "", "C")],
 "SR": [("Suriname Herald", "srherald.com", "nl", "", "C")],
 "SS": [("Radio Miraya (UNMISS)", "radiomiraya.org", "en", "", "B"), ("Radio Tamazuj (arabe)", "radiotamazuj.org/ar", "ar", "", "B"), ("The City Review", "cityreviewss.com", "en", "", "C"), ("Juba Echo", "jubaecho.com", "en", "", "C"), ("Sudan Tribune", "sudantribune.com", "en", "+", "B")],
 "SV": [("Diario El Mundo", "diario.elmundo.sv", "es", "", "B"), ("Revista Factum", "revistafactum.com", "es", "", "B"), ("La Página", "lapagina.com.sv", "es", "", "C"), ("Focos", "focostv.com", "es", "", "C")],
 "SY": [("Enab Baladi (anglais)", "english.enabbaladi.net", "en", "", "B")],
 "TD": [("RFI", "rfi.fr", "fr", "+", "B"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+", "B"), ("Tchad One", "tchadone.com", "fr", "", "C"), ("Ialtchad Presse", "ialtchad.com", "fr", "", "C"), ("Makaila.fr", "makaila.fr", "fr", "", "C")],
 "TG": [("Togo Breaking News", "togobreakingnews.info", "fr", "", "C"), ("Savoir News", "savoirnews.net", "fr", "", "C")],
 "TH": [("Thai PBS", "thaipbs.or.th", "th", "", "B"), ("BBC News Thai", "bbc.com/thai", "th", "", "B"), ("Isranews (Sud profond)", "isranews.org", "th", "", "B"), ("Deep South Watch", "deepsouthwatch.org", "th", "", "B"), ("The Phuket News", "thephuketnews.com", "en", "", "C"), ("Pattaya Mail", "pattayamail.com", "en", "", "C")],
 "TJ": [("Avesta", "avesta.tj", "ru", "", "C"), ("Eurasianet", "eurasianet.org", "en", "+", "B"), ("Khovar", "khovar.tj", "ru", "", "D")],
 "TL": [("Lusa", "lusa.pt", "pt", "+", "B")],
 "TM": [("Eurasianet", "eurasianet.org", "en", "+", "B"), ("Turkmenportal", "turkmenportal.com", "ru", "", "D")],
 "TN": [("Mosaïque FM", "mosaiquefm.net", "ar", "", "B"), ("Nawaat", "nawaat.org", "ar", "", "B"), ("Inkyfada", "inkyfada.com", "fr", "", "B"), ("Webdo", "webdo.tn", "fr", "", "C"), ("TAP – Agence Tunis Afrique Presse", "tap.info.tn", "fr", "", "D")],
 "TO": [("Kaniva Tonga", "kanivatonga.co.nz", "en", "", "C")],
 "TR": [("Anadolu Ajansı", "aa.com.tr", "tr", "", "D"), ("Sözcü", "sozcu.com.tr", "tr", "", "C"), ("Hürriyet", "hurriyet.com.tr", "tr", "", "C"), ("Medyascope", "medyascope.tv", "tr", "", "B"), ("BBC Türkçe", "bbc.com/turkce", "tr", "", "B"), ("Mezopotamya Ajansı (Sud-Est)", "mezopotamyaajansi.com", "tr", "", "C")],
 "TT": [("CNC3", "cnc3.co.tt", "en", "", "C")],
 "TW": [("中央社 CNA", "cna.com.tw", "zh", "", "B"), ("自由時報 Liberty Times", "ltn.com.tw", "zh", "", "B"), ("聯合新聞網 UDN", "udn.com", "zh", "", "B"), ("公視新聞網 PTS", "news.pts.org.tw", "zh", "", "B"), ("報導者 The Reporter", "twreporter.org", "zh", "", "B"), ("中時新聞網 China Times", "chinatimes.com", "zh", "", "C")],
 "TZ": [("Mwananchi", "mwananchi.co.tz", "sw", "", "B"), ("The Chanzo", "thechanzo.com", "en", "", "B"), ("MwanaHALISI Online", "mwanahalisionline.com", "sw", "", "C"), ("Millard Ayo", "millardayo.com", "sw", "", "C"), ("BBC News Swahili", "bbc.com/swahili", "sw", "+", "B")],
 "UA": [("NV (Novoye Vremya)", "nv.ua", "uk", "", "B"), ("Zaxid.net (Lviv)", "zaxid.net", "uk", "", "B"), ("LIGA.net", "liga.net", "uk", "", "B")],
 "UG": [("Nile Post", "nilepost.co.ug", "en", "", "C"), ("ChimpReports", "chimpreports.com", "en", "", "C"), ("The Independent", "independent.co.ug", "en", "", "B")],
 "US": [("Reuters", "reuters.com", "en", "", "B"), ("CNN", "cnn.com", "en", "", "B"), ("NBC News", "nbcnews.com", "en", "", "B"), ("CBS News", "cbsnews.com", "en", "", "B"), ("ABC News", "abcnews.go.com", "en", "", "B"), ("USA Today", "usatoday.com", "en", "", "B"), ("The Wall Street Journal", "wsj.com", "en", "", "B"), ("Los Angeles Times", "latimes.com", "en", "", "B"), ("Chicago Tribune", "chicagotribune.com", "en", "", "B"), ("Houston Chronicle", "houstonchronicle.com", "en", "", "B"), ("Miami Herald", "miamiherald.com", "en", "", "B"), ("San Francisco Chronicle", "sfchronicle.com", "en", "", "B"), ("The Boston Globe", "bostonglobe.com", "en", "", "B"), ("Politico", "politico.com", "en", "", "B")],
 "UY": [("Montevideo Portal", "montevideo.com.uy", "es", "", "B"), ("Subrayado", "subrayado.com.uy", "es", "", "B")],
 "UZ": [("Ozodlik (RFE/RL)", "ozodlik.org", "uz", "", "B"), ("Podrobno.uz", "podrobno.uz", "ru", "", "C"), ("UzA", "uza.uz", "uz", "", "D")],
 "VE": [("Runrunes", "runrun.es", "es", "", "B"), ("Crónica Uno", "cronica.uno", "es", "", "B"), ("Armando.info", "armando.info", "es", "", "B"), ("El Estímulo", "elestimulo.com", "es", "", "B"), ("La Patilla", "lapatilla.com", "es", "", "C"), ("El Impulso (Lara)", "elimpulso.com", "es", "", "C"), ("Versión Final (Zulia)", "versionfinal.com.ve", "es", "", "C"), ("Últimas Noticias", "ultimasnoticias.com.ve", "es", "", "D")],
 "VN": [("BBC News Tiếng Việt", "bbc.com/vietnamese", "vi", "", "B"), ("RFI Tiếng Việt", "rfi.fr/vi", "vi", "", "B"), ("The Vietnamese", "thevietnamese.org", "en", "", "B"), ("VnExpress", "vnexpress.net", "vi", "", "D"), ("Tuổi Trẻ", "tuoitre.vn", "vi", "", "D"), ("Thanh Niên", "thanhnien.vn", "vi", "", "D")],
 "WS": [("Talamua", "talamua.com", "en", "", "C")],
 "XK": [("Kallxo", "kallxo.com", "sq", "", "B"), ("RTK", "rtklive.com", "sq", "", "B"), ("Gazeta Express", "gazetaexpress.com", "sq", "", "C"), ("Telegrafi", "telegrafi.com", "sq", "", "C"), ("KoSSev (Nord du Kosovo)", "kossev.info", "sh", "", "B")],
 "YE": [("Al-Masdar Online", "almasdaronline.com", "ar", "", "B"), ("Al-Masdar Online English", "al-masdaronline.net", "en", "", "B"), ("Al-Ayyam (Aden)", "alayyam.info", "ar", "", "B"), ("Aden al-Ghad", "adengad.net", "ar", "", "C"), ("Yemen Monitor", "yemenmonitor.com", "ar", "", "C"), ("South24", "south24.net", "en", "", "C"), ("Belqees", "belqees.net", "ar", "", "C"), ("Saba (Sanaa, Houthis)", "saba.ye", "ar", "", "D")],
 "ZA": [("EWN – Eyewitness News", "ewn.co.za", "en", "", "B"), ("SABC News", "sabcnews.com", "en", "", "B"), ("The Citizen", "citizen.co.za", "en", "", "C"), ("GroundUp (Cap-Occidental)", "groundup.org.za", "en", "", "B"), ("The Witness (KwaZulu-Natal)", "witness.co.za", "en", "", "C"), ("SowetanLIVE (Gauteng)", "sowetanlive.co.za", "en", "", "C")],
 "ZM": [("Mwebantu", "mwebantu.com", "en", "", "C"), ("ZNBC", "znbc.co.zm", "en", "", "C")],
 "ZW": [("263Chat", "263chat.com", "en", "", "C"), ("Bulawayo24", "bulawayo24.com", "en", "", "C"), ("CITE (Bulawayo)", "cite.org.zw", "en", "", "B"), ("The NewsHawks", "thenewshawks.com", "en", "", "B"), ("The Herald", "herald.co.zw", "en", "", "D")],
}
# langue des mots-clés corrigée (médias qui publient dans la langue locale et non en anglais)
LANGUE_V25 = {
 "AF|8am.media": "fa",
 "AF|afintl.com": "fa",
 "AL|euronews.al": "sq",
 "AM|azatutyun.am": "hy",
 "BA|n1info.ba": "sh",
 "BD|prothomalo.com": "bn",
 "BG|bta.bg": "bg",
 "BY|belsat.eu": "ru",
 "CY|kathimerini.com.cy": "el",
 "DK|dr.dk": "da",
 "FI|hs.fi": "fi",
 "FI|yle.fi": "fi",
 "GE|interpressnews.ge": "ka",
 "GL|knr.gl": "da",
 "GL|sermitsiaq.ag": "da",
 "HR|hina.hr": "sh",
 "HR|index.hr": "sh",
 "HU|telex.hu": "hu",
 "ID|antaranews.com": "id",
 "ID|tempo.co": "id",
 "IR|iranintl.com": "fa",
 "JO|ammonnews.net": "ar",
 "JO|royanews.tv": "ar",
 "JP|asahi.com": "ja",
 "JP|mainichi.jp": "ja",
 "KG|24.kg": "ru",
 "KP|dailynk.com": "ko",
 "KR|yna.co.kr": "ko",
 "LB|lbcgroup.tv": "ar",
 "LB|mtv.com.lb": "ar",
 "LT|delfi.lt": "lt",
 "LT|lrt.lt": "lt",
 "LV|lsm.lv": "lv",
 "MA|hespress.com": "ar",
 "MD|ipn.md": "ro",
 "ME|rtcg.me": "sh",
 "ME|vijesti.me": "sh",
 "MK|meta.mk": "mk",
 "MK|mia.mk": "mk",
 "MN|news.mn": "mn",
 "MR|alakhbar.info": "ar",
 "NO|nrk.no": "no",
 "RO|digi24.ro": "ro",
 "RO|hotnews.ro": "ro",
 "RS|n1info.rs": "sh",
 "RU|meduza.io": "ru",
 "RU|novayagazeta.eu": "ru",
 "RU|theins.ru": "ru",
 "RU|zona.media": "ru",
 "SE|sverigesradio.se": "sv",
 "SE|svt.se": "sv",
 "SI|rtvslo.si": "sl",
 "SK|dennikn.sk": "sk",
 "SY|enabbaladi.net": "ar",
 "TJ|asiaplustj.info": "ru",
 "TM|hronikatm.com": "ru",
 "TM|turkmen.news": "ru",
 "TR|bianet.org": "tr",
 "UA|pravda.com.ua": "uk",
 "UZ|daryo.uz": "uz",
 "UZ|gazeta.uz": "ru",
 "UZ|kun.uz": "uz",
 "XK|koha.net": "sq",
}
for _iso, _items in AJOUTS_V25.items():   # domaine exact : une édition anglaise distincte (en.tempo.co) est gardée
    _known = {o[1] for o in O.get(_iso, [])}
    O.setdefault(_iso, []).extend(o for o in _items if o[1] not in _known)
for _iso, _items in O.items():
    for _i, _o in enumerate(_items):
        _lg = LANGUE_V25.get(f"{_iso}|{_o[1]}")
        if _lg:
            _items[_i] = (_o[0], _o[1], _lg) + tuple(_o[3:])

if __name__ == "__main__":
    out = {"_comment": ("Médias de référence par pays, interrogés via Google News (site:). Généré par "
                        "tools/outlets_src.py – modifiez ce fichier-là puis relancez-le. Chaque entrée : "
                        "[nom, domaine, langue des mots-clés, '+' si le nom du pays doit être ajouté à la requête]."),
           "countries": {iso: [list(o) for o in items] for iso, items in sorted(O.items())}}
    dest = Path(__file__).resolve().parent.parent / "config" / "press_outlets.json"
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
    n = sum(len(v) for v in O.values())
    print(f"{len(O)} pays, {n} médias → {dest}")
