"""Source du catalogue config/press_outlets.json (médias de référence par pays).

Format : ISO2 → liste de (nom, domaine[/chemin], langue[, "+"[, fiabilité]])
  langue    : langue des mots-clés de recherche (fr, en, es, pt, de, it, nl, pl, tr, ru, uk, ar, he, id,
              th, zh, bn, fa, ur, am, so)
  "+"       : média régional ou international → la requête ajoute le nom du pays ("" sinon)
  fiabilité : lettre de la grille de l'Amirauté (A à F) ; « B » par défaut
Critères : rédaction professionnelle identifiable, pas de relais de propagande d'État ;
dans les pays sans presse libre, médias indépendants en exil ou références internationales.
Regénérer : python tools/outlets_src.py
"""
import json
import re
from pathlib import Path

O = {
 # ---------------- Europe de l'Ouest
 "FR": [("Le Monde", "lemonde.fr", "fr"), ("Le Figaro", "lefigaro.fr", "fr"), ("Libération", "liberation.fr", "fr"), ("Franceinfo", "francetvinfo.fr", "fr"), ("Ouest-France", "ouest-france.fr", "fr")],
 "BE": [("Le Soir", "lesoir.be", "fr"), ("La Libre", "lalibre.be", "fr"), ("RTBF", "rtbf.be", "fr"), ("De Standaard", "standaard.be", "nl")],
 "LU": [("L'essentiel", "lessentiel.lu", "fr"), ("Luxembourg Times", "luxtimes.lu", "en"), ("Luxemburger Wort", "wort.lu", "de")],
 "CH": [("Le Temps", "letemps.ch", "fr"), ("RTS", "rts.ch", "fr"), ("NZZ", "nzz.ch", "de"), ("Swissinfo", "swissinfo.ch", "en")],
 "MC": [("Monaco-Matin", "monacomatin.mc", "fr"), ("Monaco Tribune", "monaco-tribune.com", "fr"), ("Nice-Matin", "nicematin.com", "fr", "+")],
 "DE": [("Der Spiegel", "spiegel.de", "de"), ("FAZ", "faz.net", "de"), ("Süddeutsche Zeitung", "sueddeutsche.de", "de"), ("Tagesschau", "tagesschau.de", "de")],
 "AT": [("Der Standard", "derstandard.at", "de"), ("Die Presse", "diepresse.com", "de"), ("ORF", "orf.at", "de")],
 "LI": [("Liechtensteiner Vaterland", "vaterland.li", "de"), ("Liechtensteiner Volksblatt", "volksblatt.li", "de"), ("NZZ", "nzz.ch", "de", "+")],
 "NL": [("NOS", "nos.nl", "nl"), ("NRC", "nrc.nl", "nl"), ("de Volkskrant", "volkskrant.nl", "nl")],
 "IT": [("Corriere della Sera", "corriere.it", "it"), ("la Repubblica", "repubblica.it", "it"), ("ANSA", "ansa.it", "it"), ("Il Sole 24 Ore", "ilsole24ore.com", "it")],
 "SM": [("San Marino RTV", "sanmarinortv.sm", "it"), ("Libertas", "libertas.sm", "it"), ("ANSA", "ansa.it", "it", "+")],
 "VA": [("Vatican News", "vaticannews.va", "en"), ("ANSA", "ansa.it", "it", "+"), ("Catholic News Agency", "catholicnewsagency.com", "en", "+")],
 "MT": [("Times of Malta", "timesofmalta.com", "en"), ("MaltaToday", "maltatoday.com.mt", "en"), ("Malta Independent", "independent.com.mt", "en")],
 "ES": [("El País", "elpais.com", "es"), ("El Mundo", "elmundo.es", "es"), ("La Vanguardia", "lavanguardia.com", "es"), ("RTVE", "rtve.es", "es")],
 "AD": [("Diari d'Andorra", "diariandorra.ad", "es"), ("Bondia", "bondia.ad", "es"), ("La Vanguardia", "lavanguardia.com", "es", "+")],
 "PT": [("Público", "publico.pt", "pt"), ("Expresso", "expresso.pt", "pt"), ("RTP", "rtp.pt", "pt"), ("Diário de Notícias", "dn.pt", "pt")],
 "GB": [("BBC News", "bbc.com", "en"), ("The Guardian", "theguardian.com", "en"), ("The Independent", "independent.co.uk", "en"), ("Financial Times", "ft.com", "en")],
 "IE": [("The Irish Times", "irishtimes.com", "en"), ("RTÉ", "rte.ie", "en"), ("Irish Independent", "independent.ie", "en")],
 "IS": [("RÚV English", "ruv.is", "en"), ("Iceland Review", "icelandreview.com", "en"), ("Reykjavík Grapevine", "grapevine.is", "en")],
 # ---------------- Europe du Nord et Baltes
 "DK": [("The Local Denmark", "thelocal.dk", "en"), ("The Copenhagen Post", "cphpost.dk", "en"), ("DR", "dr.dk", "en")],
 "SE": [("The Local Sweden", "thelocal.se", "en"), ("Sveriges Radio", "sverigesradio.se", "en"), ("SVT", "svt.se", "en")],
 "NO": [("The Local Norway", "thelocal.no", "en"), ("News in English", "newsinenglish.no", "en"), ("NRK", "nrk.no", "en")],
 "FI": [("Yle News", "yle.fi", "en"), ("Helsinki Times", "helsinkitimes.fi", "en"), ("Helsingin Sanomat", "hs.fi", "en")],
 "EE": [("ERR News", "news.err.ee", "en"), ("Postimees", "news.postimees.ee", "en"), ("Estonian World", "estonianworld.com", "en")],
 "LV": [("LSM", "lsm.lv", "en"), ("BNN", "bnn-news.com", "en"), ("The Baltic Times", "baltictimes.com", "en", "+")],
 "LT": [("LRT", "lrt.lt", "en"), ("Delfi", "delfi.lt", "en"), ("The Baltic Times", "baltictimes.com", "en", "+")],
 # ---------------- Europe centrale et orientale
 "PL": [("Rzeczpospolita", "rp.pl", "pl"), ("TVN24", "tvn24.pl", "pl"), ("Gazeta Wyborcza", "wyborcza.pl", "pl"), ("Notes from Poland", "notesfrompoland.com", "en")],
 "CZ": [("Radio Prague International", "radio.cz", "en"), ("Expats.cz", "expats.cz", "en"), ("Prague Morning", "praguemorning.cz", "en")],
 "SK": [("The Slovak Spectator", "spectator.sme.sk", "en"), ("TASR", "newsnow.tasr.sk", "en"), ("Denník N", "dennikn.sk", "en")],
 "HU": [("Telex", "telex.hu", "en"), ("Daily News Hungary", "dailynewshungary.com", "en"), ("Budapest Times", "budapesttimes.hu", "en")],
 "RO": [("Romania Insider", "romania-insider.com", "en"), ("HotNews", "hotnews.ro", "en"), ("Digi24", "digi24.ro", "en")],
 "BG": [("Novinite", "novinite.com", "en"), ("BTA", "bta.bg", "en"), ("The Sofia Globe", "sofiaglobe.com", "en")],
 "GR": [("Kathimerini", "ekathimerini.com", "en"), ("Greek Reporter", "greekreporter.com", "en"), ("Keep Talking Greece", "keeptalkinggreece.com", "en")],
 "CY": [("Cyprus Mail", "cyprus-mail.com", "en"), ("in-cyprus", "in-cyprus.philenews.com", "en"), ("Kathimerini Cyprus", "kathimerini.com.cy", "en")],
 "SI": [("RTV Slovenija", "rtvslo.si", "en"), ("Total Slovenia News", "total-slovenia-news.com", "en"), ("Slovenia Times", "sloveniatimes.com", "en")],
 "HR": [("Total Croatia News", "total-croatia-news.com", "en"), ("HINA", "hina.hr", "en"), ("Index.hr", "index.hr", "en")],
 "BA": [("Sarajevo Times", "sarajevotimes.com", "en"), ("N1 BiH", "n1info.ba", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "RS": [("N1 Serbia", "n1info.rs", "en"), ("Serbian Monitor", "serbianmonitor.com", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "ME": [("Vijesti", "vijesti.me", "en"), ("RTCG", "rtcg.me", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "MK": [("MIA", "mia.mk", "en"), ("Meta.mk", "meta.mk", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "AL": [("Exit News", "exit.al", "en"), ("Euronews Albania", "euronews.al", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "XK": [("Prishtina Insight", "prishtinainsight.com", "en"), ("Koha", "koha.net", "en"), ("Balkan Insight", "balkaninsight.com", "en", "+")],
 "UA": [("The Kyiv Independent", "kyivindependent.com", "en"), ("Ukrainska Pravda", "pravda.com.ua", "en"), ("Suspilne", "suspilne.media", "uk"), ("Ukrinform", "ukrinform.net", "en")],
 "BY": [("Belsat", "belsat.eu", "en"), ("Zerkalo", "zerkalo.io", "ru"), ("RFE/RL", "rferl.org", "en", "+")],
 "MD": [("NewsMaker", "newsmaker.md", "ru"), ("IPN", "ipn.md", "en"), ("Moldova.org", "moldova.org", "en")],
 "RU": [("Meduza", "meduza.io", "en"), ("The Moscow Times", "themoscowtimes.com", "en"), ("Novaya Gazeta Europe", "novayagazeta.eu", "en"), ("Kommersant", "kommersant.ru", "ru")],
 # ---------------- Caucase, Turquie, Asie centrale
 "GE": [("Civil.ge", "civil.ge", "en"), ("Interpressnews", "interpressnews.ge", "en"), ("OC Media", "oc-media.org", "en", "+")],
 "AM": [("Azatutyun (RFE/RL)", "azatutyun.am", "en"), ("CivilNet", "civilnet.am", "en"), ("OC Media", "oc-media.org", "en", "+")],
 "AZ": [("Turan", "turan.az", "en"), ("JAMnews", "jam-news.net", "en", "+"), ("OC Media", "oc-media.org", "en", "+")],
 "TR": [("Hürriyet Daily News", "hurriyetdailynews.com", "en"), ("Bianet", "bianet.org", "en"), ("T24", "t24.com.tr", "tr"), ("Cumhuriyet", "cumhuriyet.com.tr", "tr")],
 "KZ": [("The Times of Central Asia", "timesca.com", "en", "+"), ("Vlast.kz", "vlast.kz", "ru"), ("Orda.kz", "orda.kz", "ru")],
 "UZ": [("Kun.uz", "kun.uz", "en"), ("Gazeta.uz", "gazeta.uz", "en"), ("Daryo", "daryo.uz", "en")],
 "KG": [("24.kg", "24.kg", "en"), ("Kloop", "kloop.kg", "ru"), ("AKIpress", "akipress.com", "en")],
 "TJ": [("Asia-Plus", "asiaplustj.info", "en"), ("Ozodi (RFE/RL)", "ozodi.org", "ru"), ("The Times of Central Asia", "timesca.com", "en", "+")],
 "TM": [("Turkmen.news", "turkmen.news", "en"), ("Chronicles of Turkmenistan", "hronikatm.com", "en"), ("Azathabar (RFE/RL)", "azathabar.com", "ru")],
 # ---------------- Moyen-Orient
 "IL": [("The Times of Israel", "timesofisrael.com", "en"), ("Haaretz", "haaretz.com", "en"), ("Ynetnews", "ynetnews.com", "en"), ("The Jerusalem Post", "jpost.com", "en")],
 "PS": [("Al Jazeera", "aljazeera.com", "en", "+"), ("Middle East Eye", "middleeasteye.net", "en", "+"), ("+972 Magazine", "972mag.com", "en")],
 "LB": [("L'Orient-Le Jour", "lorientlejour.com", "fr"), ("Naharnet", "naharnet.com", "en"), ("An-Nahar", "annahar.com", "ar")],
 "SY": [("Enab Baladi", "enabbaladi.net", "en"), ("Syria Direct", "syriadirect.org", "en"), ("Al Jazeera", "aljazeera.com", "en", "+")],
 "JO": [("The Jordan Times", "jordantimes.com", "en"), ("Roya News", "royanews.tv", "en"), ("Ammon News", "ammonnews.net", "en")],
 "IQ": [("Shafaq News", "shafaq.com", "en"), ("Rudaw", "rudaw.net", "en"), ("Kurdistan24", "kurdistan24.net", "en")],
 "IR": [("IranWire", "iranwire.com", "en"), ("Iran International", "iranintl.com", "en"), ("Financial Tribune", "financialtribune.com", "en")],
 "SA": [("Arab News", "arabnews.com", "en"), ("Saudi Gazette", "saudigazette.com.sa", "en"), ("Asharq Al-Awsat", "english.aawsat.com", "en")],
 "AE": [("The National", "thenationalnews.com", "en"), ("Gulf News", "gulfnews.com", "en"), ("Khaleej Times", "khaleejtimes.com", "en")],
 "QA": [("The Peninsula", "thepeninsulaqatar.com", "en"), ("Gulf Times", "gulf-times.com", "en"), ("Doha News", "dohanews.co", "en")],
 "KW": [("Kuwait Times", "kuwaittimes.com", "en"), ("Arab Times", "arabtimesonline.com", "en"), ("Times Kuwait", "timeskuwait.com", "en")],
 "BH": [("Gulf Daily News", "gdnonline.com", "en"), ("News of Bahrain", "newsofbahrain.com", "en"), ("Al Ayam", "alayam.com", "ar")],
 "OM": [("Times of Oman", "timesofoman.com", "en"), ("Oman Observer", "omanobserver.om", "en"), ("Muscat Daily", "muscatdaily.com", "en")],
 "YE": [("Al Jazeera", "aljazeera.com", "en", "+"), ("Middle East Eye", "middleeasteye.net", "en", "+"), ("The New Arab", "newarab.com", "en", "+")],
 # ---------------- Afrique du Nord
 "EG": [("Mada Masr", "madamasr.com", "en"), ("Egypt Independent", "egyptindependent.com", "en"), ("Daily News Egypt", "dailynewsegypt.com", "en")],
 "LY": [("Libya Observer", "libyaobserver.ly", "en"), ("Libya Herald", "libyaherald.com", "en"), ("Al Wasat", "alwasat.ly", "ar")],
 "TN": [("La Presse", "lapresse.tn", "fr"), ("Business News", "businessnews.com.tn", "fr"), ("Kapitalis", "kapitalis.com", "fr")],
 "DZ": [("TSA Algérie", "tsa-algerie.com", "fr"), ("El Watan", "elwatan-dz.com", "fr"), ("Algérie 360", "algerie360.com", "fr")],
 "MA": [("TelQuel", "telquel.ma", "fr"), ("Médias24", "medias24.com", "fr"), ("Hespress", "hespress.com", "fr")],
 "MR": [("Cridem", "cridem.org", "fr"), ("Le Calame", "lecalame.info", "fr"), ("Alakhbar", "alakhbar.info", "fr")],
 "SD": [("Sudan Tribune", "sudantribune.com", "en"), ("Radio Dabanga", "dabangasudan.org", "en"), ("Radio Tamazuj", "radiotamazuj.org", "en", "+")],
 "SS": [("Radio Tamazuj", "radiotamazuj.org", "en"), ("Eye Radio", "eyeradio.org", "en"), ("Sudans Post", "sudanspost.com", "en")],
 # ---------------- Afrique de l'Est et Corne
 "ET": [("Addis Standard", "addisstandard.com", "en"), ("The Reporter", "thereporterethiopia.com", "en"), ("Addis Fortune", "addisfortune.news", "en")],
 "ER": [("BBC News", "bbc.com", "en", "+"), ("Africanews", "africanews.com", "en", "+"), ("The EastAfrican", "theeastafrican.co.ke", "en", "+")],
 "DJ": [("Jeune Afrique", "jeuneafrique.com", "fr", "+"), ("RFI", "rfi.fr", "fr", "+"), ("Africanews", "africanews.com", "fr", "+")],
 "SO": [("Hiiraan Online", "hiiraan.com", "en"), ("Garowe Online", "garoweonline.com", "en"), ("Somali Guardian", "somaliguardian.com", "en")],
 "KE": [("Nation", "nation.africa", "en"), ("The Standard", "standardmedia.co.ke", "en"), ("The Star", "the-star.co.ke", "en")],
 "UG": [("Daily Monitor", "monitor.co.ug", "en"), ("The Observer", "observer.ug", "en"), ("New Vision", "newvision.co.ug", "en")],
 "TZ": [("The Citizen", "thecitizen.co.tz", "en"), ("Daily News", "dailynews.co.tz", "en"), ("IPP Media", "ippmedia.com", "en")],
 "RW": [("The New Times", "newtimes.co.rw", "en"), ("KT Press", "ktpress.rw", "en"), ("IGIHE", "en.igihe.com", "en")],
 "BI": [("Iwacu", "iwacu-burundi.org", "fr"), ("Burundi Eco", "burundi-eco.com", "fr"), ("RFI", "rfi.fr", "fr", "+")],
 # ---------------- Afrique centrale
 "CD": [("Actualite.cd", "actualite.cd", "fr"), ("Radio Okapi", "radiookapi.net", "fr"), ("7sur7.cd", "7sur7.cd", "fr")],
 "CG": [("Les Dépêches de Brazzaville", "adiac-congo.com", "fr"), ("RFI", "rfi.fr", "fr", "+"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+")],
 "CF": [("Radio Ndeke Luka", "radiondekeluka.org", "fr"), ("Corbeau News", "corbeaunews-centrafrique.org", "fr"), ("RFI", "rfi.fr", "fr", "+")],
 "CM": [("Journal du Cameroun", "journalducameroun.com", "fr"), ("Actu Cameroun", "actucameroun.com", "fr"), ("Cameroon Tribune", "cameroon-tribune.cm", "fr")],
 "GA": [("Gabonreview", "gabonreview.com", "fr"), ("Gabonactu", "gabonactu.com", "fr"), ("Gabon Media Time", "gabonmediatime.com", "fr")],
 "GQ": [("Jeune Afrique", "jeuneafrique.com", "fr", "+"), ("RFI", "rfi.fr", "fr", "+"), ("Africanews", "africanews.com", "en", "+")],
 "TD": [("Alwihda Info", "alwihdainfo.com", "fr"), ("Tchadinfos", "tchadinfos.com", "fr"), ("Journal du Tchad", "journaldutchad.com", "fr")],
 "ST": [("Téla Nón", "telanon.info", "pt"), ("RFI", "rfi.fr", "fr", "+"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+")],
 # ---------------- Sahel et Afrique de l'Ouest
 "NE": [("ActuNiger", "actuniger.com", "fr"), ("aNiamey", "aniamey.com", "fr"), ("RFI", "rfi.fr", "fr", "+")],
 "ML": [("Maliweb", "maliweb.net", "fr"), ("Malijet", "malijet.com", "fr"), ("Studio Tamani", "studiotamani.org", "fr")],
 "BF": [("Lefaso.net", "lefaso.net", "fr"), ("Burkina24", "burkina24.com", "fr"), ("Le Pays", "lepays.bf", "fr")],
 "SN": [("Seneweb", "seneweb.com", "fr"), ("Dakaractu", "dakaractu.com", "fr"), ("Le Quotidien", "lequotidien.sn", "fr")],
 "GM": [("The Point", "thepoint.gm", "en"), ("Foroyaa", "foroyaa.net", "en"), ("The Standard", "standard.gm", "en")],
 "GW": [("O Democrata", "odemocratagb.com", "pt"), ("RFI", "rfi.fr", "fr", "+"), ("Jeune Afrique", "jeuneafrique.com", "fr", "+")],
 "GN": [("Guinéenews", "guineenews.org", "fr"), ("Africaguinee", "africaguinee.com", "fr"), ("Mosaïque Guinée", "mosaiqueguinee.com", "fr")],
 "SL": [("Awoko", "awokonewspaper.sl", "en"), ("Sierraloaded", "sierraloaded.sl", "en"), ("Calabash", "thecalabashnewspaper.com", "en")],
 "LR": [("FrontPage Africa", "frontpageafricaonline.com", "en"), ("Liberian Observer", "liberianobserver.com", "en"), ("The New Dawn", "thenewdawnliberia.com", "en")],
 "CI": [("Linfodrome", "linfodrome.com", "fr"), ("Abidjan.net", "abidjan.net", "fr"), ("Fraternité Matin", "fratmat.info", "fr")],
 "GH": [("MyJoyOnline", "myjoyonline.com", "en"), ("Citi Newsroom", "citinewsroom.com", "en"), ("Graphic Online", "graphic.com.gh", "en")],
 "TG": [("icilome", "icilome.com", "fr"), ("Republicoftogo.com", "republicoftogo.com", "fr"), ("24heureinfo", "24heureinfo.com", "fr")],
 "BJ": [("La Nouvelle Tribune", "lanouvelletribune.info", "fr"), ("24 Heures au Bénin", "24haubenin.info", "fr"), ("Banouto", "banouto.bj", "fr")],
 "NG": [("Premium Times", "premiumtimesng.com", "en"), ("Punch", "punchng.com", "en"), ("TheCable", "thecable.ng", "en"), ("Vanguard", "vanguardngr.com", "en")],
 "CV": [("Expresso das Ilhas", "expressodasilhas.cv", "pt"), ("Inforpress", "inforpress.cv", "pt"), ("A Semana", "asemana.publ.cv", "pt")],
 # ---------------- Afrique australe et océan Indien
 "AO": [("Novo Jornal", "novojornal.co.ao", "pt"), ("Maka Angola", "makaangola.org", "pt"), ("Jornal de Angola", "jornaldeangola.ao", "pt")],
 "ZM": [("Lusaka Times", "lusakatimes.com", "en"), ("News Diggers", "diggers.news", "en"), ("Zambia Monitor", "zambiamonitor.com", "en")],
 "ZW": [("NewsDay", "newsday.co.zw", "en"), ("ZimLive", "zimlive.com", "en"), ("NewZimbabwe", "newzimbabwe.com", "en")],
 "MW": [("Nyasa Times", "nyasatimes.com", "en"), ("The Nation", "mwnation.com", "en"), ("Times 360", "times.mw", "en")],
 "MZ": [("Club of Mozambique", "clubofmozambique.com", "en"), ("Carta de Moçambique", "cartamz.com", "pt"), ("O País", "opais.co.mz", "pt")],
 "MG": [("L'Express de Madagascar", "lexpress.mg", "fr"), ("Midi Madagasikara", "midi-madagasikara.mg", "fr"), ("NewsMada", "newsmada.com", "fr")],
 "MU": [("L'Express", "lexpress.mu", "fr"), ("Defimedia", "defimedia.info", "fr"), ("Le Mauricien", "lemauricien.com", "fr")],
 "SC": [("Seychelles Nation", "nation.sc", "en"), ("Seychelles News Agency", "seychellesnewsagency.com", "en"), ("Today in Seychelles", "todayinseychelles.com", "en")],
 "KM": [("Al-Watwan", "alwatwan.net", "fr"), ("Comores Infos", "comoresinfos.net", "fr"), ("Habari za Comores", "habarizacomores.com", "fr")],
 "ZA": [("News24", "news24.com", "en"), ("Daily Maverick", "dailymaverick.co.za", "en"), ("TimesLIVE", "timeslive.co.za", "en"), ("IOL", "iol.co.za", "en")],
 "NA": [("The Namibian", "namibian.com.na", "en"), ("New Era", "neweralive.na", "en"), ("Namibian Sun", "namibiansun.com", "en")],
 "BW": [("Mmegi", "mmegi.bw", "en"), ("Sunday Standard", "sundaystandard.info", "en"), ("Weekend Post", "weekendpost.co.bw", "en")],
 "LS": [("Lesotho Times", "lestimes.com", "en"), ("The Post", "thepost.co.ls", "en"), ("Public Eye", "publiceyenews.com", "en")],
 "SZ": [("Times of Eswatini", "times.co.sz", "en"), ("Swaziland News", "swazilandnews.co.za", "en"), ("Africanews", "africanews.com", "en", "+")],
 # ---------------- Asie du Sud
 "AF": [("Amu TV", "amu.tv", "en"), ("TOLOnews", "tolonews.com", "en"), ("8am Media", "8am.media", "en")],
 "PK": [("Dawn", "dawn.com", "en"), ("The News", "thenews.com.pk", "en"), ("The Express Tribune", "tribune.com.pk", "en"), ("Geo News", "geo.tv", "en")],
 "IN": [("The Hindu", "thehindu.com", "en"), ("The Indian Express", "indianexpress.com", "en"), ("Hindustan Times", "hindustantimes.com", "en"), ("NDTV", "ndtv.com", "en")],
 "BD": [("The Daily Star", "thedailystar.net", "en"), ("The Business Standard", "tbsnews.net", "en"), ("bdnews24", "bdnews24.com", "en")],
 "LK": [("Daily Mirror", "dailymirror.lk", "en"), ("EconomyNext", "economynext.com", "en"), ("Sunday Times", "sundaytimes.lk", "en")],
 "NP": [("The Kathmandu Post", "kathmandupost.com", "en"), ("My Republica", "myrepublica.nagariknetwork.com", "en"), ("The Rising Nepal", "risingnepaldaily.com", "en")],
 "BT": [("Kuensel", "kuenselonline.com", "en"), ("The Bhutanese", "thebhutanese.bt", "en"), ("BBS", "bbs.bt", "en")],
 "MV": [("Sun", "sun.mv", "en"), ("Edition.mv", "edition.mv", "en"), ("PSM News", "psmnews.mv", "en")],
 # ---------------- Asie du Sud-Est
 "MM": [("The Irrawaddy", "irrawaddy.com", "en"), ("Mizzima", "mizzima.com", "en"), ("Frontier Myanmar", "frontiermyanmar.net", "en"), ("Myanmar Now", "myanmar-now.org", "en")],
 "TH": [("Bangkok Post", "bangkokpost.com", "en"), ("The Nation", "nationthailand.com", "en"), ("Thai PBS World", "thaipbsworld.com", "en"), ("Khaosod English", "khaosodenglish.com", "en")],
 "KH": [("Khmer Times", "khmertimeskh.com", "en"), ("Phnom Penh Post", "phnompenhpost.com", "en"), ("CamboJA News", "cambojanews.com", "en")],
 "LA": [("Laotian Times", "laotiantimes.com", "en"), ("Vientiane Times", "vientianetimes.gov.la", "en"), ("The Diplomat", "thediplomat.com", "en", "+")],
 "VN": [("VnExpress International", "e.vnexpress.net", "en"), ("Tuoi Tre News", "tuoitrenews.vn", "en"), ("Viet Nam News", "vietnamnews.vn", "en")],
 "MY": [("The Star", "thestar.com.my", "en"), ("Malaysiakini", "malaysiakini.com", "en"), ("Free Malaysia Today", "freemalaysiatoday.com", "en"), ("New Straits Times", "nst.com.my", "en")],
 "SG": [("The Straits Times", "straitstimes.com", "en"), ("CNA", "channelnewsasia.com", "en"), ("TODAY", "todayonline.com", "en")],
 "ID": [("The Jakarta Post", "thejakartapost.com", "en"), ("Tempo", "tempo.co", "en"), ("Kompas", "kompas.com", "id"), ("Antara", "antaranews.com", "en")],
 "PH": [("Philippine Daily Inquirer", "inquirer.net", "en"), ("Rappler", "rappler.com", "en"), ("Philstar", "philstar.com", "en"), ("GMA News", "gmanetwork.com", "en")],
 "TL": [("Tatoli", "tatoli.tl", "en"), ("ABC News", "abc.net.au", "en", "+"), ("The Diplomat", "thediplomat.com", "en", "+")],
 "BN": [("Borneo Bulletin", "borneobulletin.com.bn", "en"), ("The Scoop", "thescoop.co", "en"), ("The Star", "thestar.com.my", "en", "+")],
 # ---------------- Asie de l'Est
 "CN": [("South China Morning Post", "scmp.com", "en", "+"), ("Caixin Global", "caixinglobal.com", "en"), ("Reuters", "reuters.com", "en", "+")],
 "HK": [("Hong Kong Free Press", "hongkongfp.com", "en"), ("The Standard", "thestandard.com.hk", "en"), ("RTHK", "rthk.hk", "en")],
 "TW": [("Taipei Times", "taipeitimes.com", "en"), ("Focus Taiwan", "focustaiwan.tw", "en"), ("Taiwan News", "taiwannews.com.tw", "en")],
 "JP": [("The Japan Times", "japantimes.co.jp", "en"), ("The Mainichi", "mainichi.jp", "en"), ("The Asahi Shimbun", "asahi.com", "en"), ("NHK World", "nhk.or.jp", "en")],
 "KR": [("The Korea Herald", "koreaherald.com", "en"), ("Yonhap", "yna.co.kr", "en"), ("Korea JoongAng Daily", "koreajoongangdaily.joins.com", "en")],
 "KP": [("NK News", "nknews.org", "en"), ("Daily NK", "dailynk.com", "en"), ("38 North", "38north.org", "en")],
 "MN": [("Montsame", "montsame.mn", "en"), ("News.mn", "news.mn", "en"), ("Reuters", "reuters.com", "en", "+")],
 # ---------------- Amérique du Nord
 "US": [("The New York Times", "nytimes.com", "en"), ("The Washington Post", "washingtonpost.com", "en"), ("AP News", "apnews.com", "en"), ("NPR", "npr.org", "en")],
 "CA": [("CBC News", "cbc.ca", "en"), ("The Globe and Mail", "theglobeandmail.com", "en"), ("CTV News", "ctvnews.ca", "en"), ("La Presse", "lapresse.ca", "fr")],
 "MX": [("El Universal", "eluniversal.com.mx", "es"), ("Milenio", "milenio.com", "es"), ("Animal Político", "animalpolitico.com", "es"), ("Proceso", "proceso.com.mx", "es")],
 # ---------------- Amérique centrale et Caraïbes
 "GT": [("Prensa Libre", "prensalibre.com", "es"), ("Soy502", "soy502.com", "es"), ("La Hora", "lahora.gt", "es")],
 "BZ": [("Amandala", "amandala.com.bz", "en"), ("Breaking Belize News", "breakingbelizenews.com", "en"), ("7 News Belize", "7newsbelize.com", "en")],
 "HN": [("La Prensa", "laprensa.hn", "es"), ("El Heraldo", "elheraldo.hn", "es"), ("Proceso Digital", "proceso.hn", "es")],
 "SV": [("La Prensa Gráfica", "laprensagrafica.com", "es"), ("El Diario de Hoy", "elsalvador.com", "es"), ("El Faro", "elfaro.net", "es")],
 "NI": [("Confidencial", "confidencial.digital", "es"), ("La Prensa", "laprensani.com", "es"), ("100% Noticias", "100noticias.com.ni", "es")],
 "CR": [("La Nación", "nacion.com", "es"), ("CRHoy", "crhoy.com", "es"), ("The Tico Times", "ticotimes.net", "en")],
 "PA": [("La Prensa", "prensa.com", "es"), ("La Estrella de Panamá", "laestrella.com.pa", "es"), ("TVN", "tvn-2.com", "es")],
 "CU": [("14ymedio", "14ymedio.com", "es"), ("Diario de Cuba", "diariodecuba.com", "es"), ("elTOQUE", "eltoque.com", "es")],
 "HT": [("Le Nouvelliste", "lenouvelliste.com", "fr"), ("HaïtiLibre", "haitilibre.com", "fr"), ("AyiboPost", "ayibopost.com", "fr")],
 "DO": [("Diario Libre", "diariolibre.com", "es"), ("Listín Diario", "listindiario.com", "es"), ("El Caribe", "elcaribe.com.do", "es")],
 "JM": [("The Gleaner", "jamaica-gleaner.com", "en"), ("Jamaica Observer", "jamaicaobserver.com", "en"), ("Radio Jamaica News", "radiojamaicanewsonline.com", "en")],
 "TT": [("Trinidad Guardian", "guardian.co.tt", "en"), ("Newsday", "newsday.co.tt", "en"), ("Trinidad Express", "trinidadexpress.com", "en")],
 "BS": [("The Tribune", "tribune242.com", "en"), ("The Nassau Guardian", "thenassauguardian.com", "en"), ("EyeWitness News", "ewnews.com", "en")],
 "BB": [("Nation News", "nationnews.com", "en"), ("Barbados Today", "barbadostoday.bb", "en"), ("Barbados Advocate", "barbadosadvocate.com", "en")],
 "LC": [("St Lucia Times", "stluciatimes.com", "en"), ("The Voice", "thevoiceslu.com", "en"), ("St Lucia News Online", "stlucianewsonline.com", "en")],
 "GD": [("NOW Grenada", "nowgrenada.com", "en"), ("The New Today", "thenewtodaygrenada.com", "en"), ("GBN", "grenadabroadcast.com", "en")],
 "VC": [("iWitness News", "iwnsvg.com", "en"), ("Searchlight", "searchlight.vc", "en"), ("St Vincent Times", "stvincenttimes.com", "en")],
 "AG": [("Antigua Observer", "antiguaobserver.com", "en"), ("Antigua Newsroom", "antiguanewsroom.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "KN": [("SKNVibes", "sknvibes.com", "en"), ("The Observer", "thestkittsnevisobserver.com", "en"), ("WINN FM", "winnfm.com", "en")],
 "DM": [("Dominica News Online", "dominicanewsonline.com", "en"), ("Emo News", "emonewsdm.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "GY": [("Stabroek News", "stabroeknews.com", "en"), ("Kaieteur News", "kaieteurnewsonline.com", "en"), ("News Room", "newsroom.gy", "en")],
 "SR": [("Starnieuws", "starnieuws.com", "nl"), ("De Ware Tijd", "dwtonline.com", "nl"), ("Waterkant", "waterkant.net", "nl")],
 # ---------------- Amérique du Sud
 "CO": [("El Tiempo", "eltiempo.com", "es"), ("El Espectador", "elespectador.com", "es"), ("Semana", "semana.com", "es")],
 "VE": [("Efecto Cocuyo", "efectococuyo.com", "es"), ("El Pitazo", "elpitazo.net", "es"), ("Tal Cual", "talcualdigital.com", "es"), ("El Nacional", "elnacional.com", "es")],
 "EC": [("Primicias", "primicias.ec", "es"), ("El Comercio", "elcomercio.com", "es"), ("El Universo", "eluniverso.com", "es")],
 "PE": [("El Comercio", "elcomercio.pe", "es"), ("La República", "larepublica.pe", "es"), ("RPP", "rpp.pe", "es")],
 "BO": [("El Deber", "eldeber.com.bo", "es"), ("Los Tiempos", "lostiempos.com", "es"), ("Correo del Sur", "correodelsur.com", "es")],
 "BR": [("Folha de S.Paulo", "folha.uol.com.br", "pt"), ("g1", "g1.globo.com", "pt"), ("Estadão", "estadao.com.br", "pt"), ("O Globo", "oglobo.globo.com", "pt")],
 "PY": [("ABC Color", "abc.com.py", "es"), ("Última Hora", "ultimahora.com", "es"), ("La Nación", "lanacion.com.py", "es")],
 "UY": [("El País", "elpais.com.uy", "es"), ("El Observador", "elobservador.com.uy", "es"), ("la diaria", "ladiaria.com.uy", "es")],
 "AR": [("La Nación", "lanacion.com.ar", "es"), ("Clarín", "clarin.com", "es"), ("Infobae", "infobae.com", "es"), ("Página/12", "pagina12.com.ar", "es")],
 "CL": [("La Tercera", "latercera.com", "es"), ("Emol", "emol.com", "es"), ("BioBioChile", "biobiochile.cl", "es"), ("El Mostrador", "elmostrador.cl", "es")],
 # ---------------- Océanie
 "AU": [("ABC News", "abc.net.au", "en"), ("The Sydney Morning Herald", "smh.com.au", "en"), ("The Age", "theage.com.au", "en")],
 "NZ": [("RNZ", "rnz.co.nz", "en"), ("NZ Herald", "nzherald.co.nz", "en"), ("Stuff", "stuff.co.nz", "en")],
 "PG": [("Post-Courier", "postcourier.com.pg", "en"), ("The National", "thenational.com.pg", "en"), ("EMTV", "emtv.com.pg", "en")],
 "FJ": [("The Fiji Times", "fijitimes.com.fj", "en"), ("Fijivillage", "fijivillage.com", "en"), ("FBC News", "fbcnews.com.fj", "en")],
 "SB": [("Solomon Star", "solomonstarnews.com", "en"), ("SIBC", "sibconline.com.sb", "en"), ("Island Sun", "theislandsun.com.sb", "en")],
 "VU": [("Vanuatu Daily Post", "dailypost.vu", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+")],
 "NC": [("Les Nouvelles Calédoniennes", "lnc.nc", "fr"), ("NC la 1ère", "la1ere.francetvinfo.fr", "fr", "+"), ("Outremers360", "outremers360.com", "fr", "+")],
 "PF": [("TNTV", "tntv.pf", "fr"), ("Radio 1", "radio1.pf", "fr"), ("Polynésie la 1ère", "la1ere.francetvinfo.fr", "fr", "+")],
 "WS": [("Samoa Observer", "samoaobserver.ws", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+")],
 "TO": [("Matangi Tonga", "matangitonga.to", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+")],
 "KI": [("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "FM": [("Kaselehlie Press", "kpress.info", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "MH": [("Marshall Islands Journal", "marshallislandsjournal.com", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "PW": [("Island Times", "islandtimes.org", "en"), ("RNZ Pacific", "rnz.co.nz", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "NR": [("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 "TV": [("RNZ Pacific", "rnz.co.nz", "en", "+"), ("ABC Pacific", "abc.net.au", "en", "+"), ("Islands Business", "islandsbusiness.com", "en", "+")],
 # ---------------- Territoires
 "PR": [("El Nuevo Día", "elnuevodia.com", "es"), ("Primera Hora", "primerahora.com", "es"), ("NotiCel", "noticel.com", "es")],
 "GU": [("Pacific Daily News", "guampdn.com", "en"), ("KUAM News", "kuam.com", "en"), ("The Guam Daily Post", "postguam.com", "en")],
 "MO": [("Macau Daily Times", "macaudailytimes.com.mo", "en"), ("Macau Business", "macaubusiness.com", "en"), ("Macau News Agency", "macaonews.org", "en")],
 "BM": [("The Royal Gazette", "royalgazette.com", "en"), ("Bernews", "bernews.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "KY": [("Cayman Compass", "caymancompass.com", "en"), ("Cayman News Service", "caymannewsservice.com", "en"), ("Loop News", "loopnews.com", "en", "+")],
 "GL": [("Sermitsiaq", "sermitsiaq.ag", "en"), ("KNR", "knr.gl", "en"), ("Arctic Today", "arctictoday.com", "en", "+")],
}

# ---------------- Presse de 25 pays à risque (liste de Stef, presse_25_pays.csv, v0.9)
# (nom, site, langue des mots-clés, "+" si le nom du pays est ajouté, fiabilité Amirauté A-F), par priorité P1 → P3
PRESSE_25 = {
 "NE": [('Aïr Info', 'airinfoagadez.com', 'fr', '', 'B'), ('Studio Kalangou (Fondation Hirondelle)', 'studiokalangou.org', 'fr', '', 'B'), ("L'Événement Niger", 'levenementniger.com', 'fr', '', 'B'), ('Les Échos du Niger', 'lesechosduniger.com', 'fr', '', 'C'), ('aNiamey', 'news.aniamey.com', 'fr', '', 'C'), ('Labari Info (RTL Niger)', 'labarinfo.com', 'fr', '', 'C'), ('Le Sahel', 'lesahel.org', 'fr', '', 'D'), ('ANP – Agence nigérienne de presse', 'anp.ne', 'fr', '', 'D')],
 "BF": [("L'Observateur Paalga", 'lobservateur.bf', 'fr', '', 'C'), ("Aujourd'hui au Faso", 'aujourd8.net', 'fr', '', 'C'), ('Wakat Séra', 'wakatsera.com', 'fr', '', 'C'), ('Studio Yafa (Fondation Hirondelle)', 'studioyafa.org', 'fr', '', 'B'), ('Sidwaya', 'sidwaya.info', 'fr', '', 'D'), ("AIB – Agence d'information du Burkina", 'aib.media', 'fr', '', 'D')],
 "ML": [('Journal du Mali', 'journaldumali.com', 'fr', '', 'C'), ('Sahelien.com', 'sahelien.com', 'fr', '', 'C'), ('aBamako', 'news.abamako.com', 'fr', '', 'C'), ('Mali Actu', 'maliactu.net', 'fr', '', 'D'), ("L'Essor", 'lessormali.com', 'fr', '', 'D')],
 "TH": [('Prachatai English', 'prachatai.com/english', 'en', '', 'B'), ('Thairath', 'thairath.co.th', 'th', '', 'C'), ('Matichon', 'matichon.co.th', 'th', '', 'C'), ('Khaosod', 'khaosod.co.th', 'th', '', 'C')],
 "ID": [('Antara News', 'en.antaranews.com', 'en', '', 'C'), ('Detik.com', 'detik.com', 'id', '', 'C'), ('CNN Indonesia', 'cnnindonesia.com', 'id', '', 'C'), ('Jakarta Globe', 'jakartaglobe.id', 'en', '', 'C'), ('Liputan6', 'liputan6.com', 'id', '', 'C'), ('Republika', 'republika.co.id', 'id', '', 'C')],
 "CN": [('Hong Kong Free Press', 'hongkongfp.com', 'en', '', 'B'), ('China Digital Times', 'chinadigitaltimes.net', 'en', '', 'B'), ('The Standard (Hong Kong)', 'thestandard.com.hk', 'en', '', 'C'), ('The Paper (澎湃新闻)', 'thepaper.cn', 'zh', '', 'D'), ('Sixth Tone', 'sixthtone.com', 'en', '', 'D'), ('RTHK News', 'news.rthk.hk', 'en', '', 'D')],
 "AU": [('The Guardian Australia', 'theguardian.com/au', 'en', '', 'B'), ('SBS News', 'sbs.com.au/news', 'en', '', 'B'), ('news.com.au', 'news.com.au', 'en', '', 'C'), ('9News', '9news.com.au', 'en', '', 'C'), ('7NEWS', '7news.com.au', 'en', '', 'C'), ('The New Daily', 'thenewdaily.com.au', 'en', '', 'C'), ('The Conversation Australia', 'theconversation.com/au', 'en', '+', 'B')],
 "SD": [('Al-Taghyeer', 'altaghyeer.info', 'ar', '', 'C'), ('Ayin Network', '3ayin.com', 'en', '', 'B'), ('Darfur24', 'darfur24.com', 'en', '', 'C'), ('Sudan War Monitor', 'sudanwarmonitor.com', 'en', '', 'C'), ('Sudans Post', 'sudanspost.com', 'en', '+', 'C'), ('Alrakoba', 'alrakoba.net', 'ar', '', 'D'), ('SUNA', 'suna-sd.net', 'en', '', 'D')],
 "CD": [('Kivu Morning Post', 'kivumorningpost.com', 'fr', '', 'C'), ('Politico.cd', 'politico.cd', 'fr', '', 'C'), ('Studio Hirondelle RDC', 'studiohirondellerdc.org', 'fr', '', 'B'), ('Habari RDC', 'habarirdc.net', 'fr', '', 'C'), ('Mediacongo', 'mediacongo.net', 'fr', '', 'C')],
 "LB": [("NNA – Agence nationale d'information", 'nna-leb.gov.lb', 'en', '', 'C'), ('LBCI', 'lbcgroup.tv', 'en', '', 'C'), ('MTV Lebanon', 'mtv.com.lb', 'en', '', 'C'), ('Al Jadeed', 'aljadeed.tv', 'ar', '', 'C'), ('Nidaa al-Watan', 'nidaalwatan.com', 'ar', '', 'C'), ('Megaphone', 'megaphone.news', 'en', '', 'B')],
 "IL": [('Ynet', 'ynet.co.il', 'he', '', 'B'), ('i24NEWS', 'i24news.tv', 'en', '', 'C'), ('N12 (Mako)', 'mako.co.il', 'he', '', 'C'), ('Israel Hayom', 'israelhayom.com', 'en', '', 'C'), ('+972 Magazine', '972mag.com', 'en', '', 'C')],
 "ET": [('Ethiopia Insight', 'ethiopia-insight.com', 'en', '', 'B'), ('Wazema', 'wazemaradio.com', 'am', '', 'C'), ('Capital Ethiopia', 'capitalethiopia.com', 'en', '', 'C'), ('Borkena', 'borkena.com', 'en', '', 'D'), ('ENA – Ethiopian News Agency', 'ena.et', 'en', '', 'D')],
 "SY": [('Enab Baladi', 'english.enabbaladi.net', 'en', '', 'B'), ("SOHR – Observatoire syrien des droits de l'homme", 'syriahr.com/en', 'en', '', 'C'), ('The Syrian Observer', 'syrianobserver.com', 'en', '', 'C'), ('Zaman al-Wasl', 'zamanalwsl.net', 'ar', '', 'C'), ('Syria TV', 'syria.tv', 'ar', '', 'C'), ('North Press Agency', 'npasyria.com/en', 'en', '', 'D'), ('SANA', 'sana.sy/en', 'en', '', 'D')],
 "UA": [('Hromadske', 'hromadske.ua', 'uk', '', 'B'), ('UNIAN', 'unian.info', 'en', '', 'C'), ('RBC-Ukraine', 'newsukraine.rbc.ua', 'en', '', 'C'), ('LB.ua', 'lb.ua', 'uk', '', 'C'), ('Kyiv Post', 'kyivpost.com', 'en', '', 'B')],
 "MM": [('DVB – Democratic Voice of Burma', 'english.dvb.no', 'en', '', 'B'), ('Mizzima', 'eng.mizzima.com', 'en', '', 'C'), ('BNI – Burma News International', 'bnionline.net', 'en', '', 'B'), ('SHAN – Shan Herald Agency for News', 'english.shannews.org', 'en', '', 'C'), ('Narinjara', 'narinjara.com', 'en', '', 'C')],
 "CM": [('Mimi Mefo Info', 'mimimefoinfos.com', 'en', '', 'C'), ('The Guardian Post', 'theguardianpostcameroon.com', 'en', '', 'C'), ('Cameroon News Agency', 'cameroonnewsagency.com', 'en', '', 'C'), ('Datacameroon', 'datacameroon.com', 'fr', '', 'C')],
 "IR": [('Amwaj.media', 'amwaj.media', 'en', '+', 'B'), ('BBC Persian', 'bbc.com/persian', 'fa', '', 'B'), ('HRANA', 'en-hrana.org', 'en', '', 'C'), ('Hengaw', 'hengaw.net', 'en', '', 'C'), ('Radio Farda', 'radiofarda.com', 'fa', '', 'B'), ('Shargh', 'sharghdaily.com', 'fa', '', 'C'), ('Etemad', 'etemadonline.com', 'fa', '', 'C'), ('ISNA', 'en.isna.ir', 'en', '', 'D')],
 "SO": [('Caasimada', 'caasimada.net', 'so', '', 'C'), ('Radio Dalsan', 'radiodalsan.com', 'en', '', 'C'), ('Horseed Media', 'horseedmedia.net', 'en', '', 'C'), ('Horn Observer', 'hornobserver.com', 'en', '', 'C'), ('Horn Diplomat', 'horndiplomat.com', 'en', '', 'C'), ('SONNA', 'sonna.so', 'en', '', 'D')],
 "GB": [('BBC News', 'bbc.co.uk/news', 'en', '', 'B'), ('Sky News', 'news.sky.com', 'en', '', 'B'), ('Evening Standard', 'standard.co.uk', 'en', '', 'C'), ('Manchester Evening News', 'manchestereveningnews.co.uk', 'en', '', 'C'), ('Metro', 'metro.co.uk', 'en', '', 'C'), ('Daily Mirror', 'mirror.co.uk', 'en', '', 'C'), ('Daily Record', 'dailyrecord.co.uk', 'en', '', 'C'), ('Belfast Live', 'belfastlive.co.uk', 'en', '', 'C')],
 "PK": [('Business Recorder', 'brecorder.com', 'en', '', 'B'), ('Daily Jang', 'jang.com.pk', 'ur', '', 'C'), ('Pakistan Today', 'pakistantoday.com.pk', 'en', '', 'C'), ('Samaa', 'samaa.tv', 'en', '', 'C'), ('Daily Express (ourdou)', 'express.pk', 'ur', '', 'C'), ('The Balochistan Post', 'thebalochistanpost.net', 'en', '', 'D')],
 "NG": [('Daily Trust', 'dailytrust.com', 'en', '', 'B'), ('HumAngle', 'humanglemedia.com', 'en', '', 'B'), ('Channels TV', 'channelstv.com', 'en', '', 'B'), ('The Guardian Nigeria', 'guardian.ng', 'en', '', 'C'), ('ThisDay', 'thisdaylive.com', 'en', '', 'C'), ('Leadership', 'leadership.ng', 'en', '', 'C')],
 "RU": [('Mediazona', 'zona.media', 'en', '', 'B'), ('The Insider', 'theins.ru', 'en', '', 'B'), ('Verstka', 'verstka.media', 'ru', '', 'B'), ('7x7', 'semnasem.org', 'ru', '', 'C'), ('Sibir.Realii (RFE/RL)', 'sibreal.org', 'ru', '', 'B'), ('Fontanka.ru', 'fontanka.ru', 'ru', '', 'C'), ('Interfax', 'interfax.ru', 'ru', '', 'D')],
 "BD": [('Prothom Alo', 'prothomalo.com', 'en', '', 'B'), ('New Age', 'newagebd.net', 'en', '', 'B'), ('Dhaka Tribune', 'dhakatribune.com', 'en', '', 'C'), ('The Financial Express', 'thefinancialexpress.com.bd', 'en', '', 'C'), ('Kaler Kantho', 'kalerkantho.com', 'bn', '', 'C'), ('BSS', 'bssnews.net', 'en', '', 'D')],
 "MX": [('La Jornada', 'jornada.com.mx', 'es', '', 'C'), ('Excélsior', 'excelsior.com.mx', 'es', '', 'C'), ('Aristegui Noticias', 'aristeguinoticias.com', 'es', '', 'B'), ('Infobae México', 'infobae.com/mexico', 'es', '', 'C'), ('El Informador', 'informador.mx', 'es', '', 'C'), ('Zeta Tijuana', 'zetatijuana.com', 'es', '', 'B'), ('Ríodoce', 'riodoce.mx', 'es', '', 'B'), ('El Financiero', 'elfinanciero.com.mx', 'es', '', 'B')],
 "AF": [('KabulNow', 'kabulnow.com', 'en', '', 'B'), ('Etilaatroz', 'etilaatroz.com', 'fa', '', 'B'), ('Khaama Press', 'khaama.com', 'en', '', 'C'), ('Rukhshana Media', 'rukhshana.com', 'en', '', 'B'), ('Afghanistan International', 'afintl.com', 'en', '', 'D'), ('Ariana News', 'ariananews.af', 'en', '', 'D')],
}
# fiabilité (grille de l'Amirauté) des médias déjà présents au catalogue, d'après la même liste
FIABILITE = {"AF|8am.media": "B",
 "AF|amu.tv": "B",
 "AF|tolonews.com": "C",
 "AU|abc.net.au": "B",
 "BD|bdnews24.com": "C",
 "BD|tbsnews.net": "B",
 "BD|thedailystar.net": "B",
 "BF|burkina24.com": "C",
 "BF|lefaso.net": "C",
 "BF|lepays.bf": "C",
 "CD|7sur7.cd": "C",
 "CD|actualite.cd": "B",
 "CD|radiookapi.net": "B",
 "CM|actucameroun.com": "C",
 "CM|cameroon-tribune.cm": "D",
 "CM|journalducameroun.com": "C",
 "ET|addisfortune.news": "B",
 "ET|addisstandard.com": "B",
 "ET|thereporterethiopia.com": "C",
 "GB|independent.co.uk": "C",
 "GB|theguardian.com": "B",
 "ID|kompas.com": "B",
 "ID|tempo.co": "B",
 "IL|jpost.com": "C",
 "IL|timesofisrael.com": "B",
 "IL|ynetnews.com": "B",
 "IR|iranintl.com": "D",
 "IR|iranwire.com": "B",
 "LB|annahar.com": "B",
 "LB|naharnet.com": "C",
 "ML|maliweb.net": "C",
 "ML|studiotamani.org": "B",
 "MM|irrawaddy.com": "B",
 "MM|myanmar-now.org": "B",
 "MX|animalpolitico.com": "B",
 "MX|eluniversal.com.mx": "B",
 "MX|milenio.com": "C",
 "NE|actuniger.com": "C",
 "NG|premiumtimesng.com": "B",
 "NG|punchng.com": "B",
 "NG|thecable.ng": "B",
 "NG|vanguardngr.com": "C",
 "PK|dawn.com": "B",
 "PK|geo.tv": "C",
 "PK|thenews.com.pk": "C",
 "PK|tribune.com.pk": "B",
 "RU|kommersant.ru": "C",
 "RU|meduza.io": "B",
 "RU|novayagazeta.eu": "B",
 "RU|themoscowtimes.com": "B",
 "SD|dabangasudan.org": "B",
 "SD|sudantribune.com": "B",
 "SO|garoweonline.com": "C",
 "SO|hiiraan.com": "C",
 "SO|somaliguardian.com": "C",
 "SY|syriadirect.org": "B",
 "TH|bangkokpost.com": "B",
 "TH|khaosodenglish.com": "B",
 "TH|nationthailand.com": "C",
 "TH|thaipbsworld.com": "B",
 "UA|kyivindependent.com": "B",
 "UA|pravda.com.ua": "B",
 "UA|suspilne.media": "B",
 "UA|ukrinform.net": "C"}
for _iso, _items in PRESSE_25.items():  # ajoutés au catalogue du pays (sans doublon de domaine)
    _base = lambda d: re.sub(r"^(news|www|m|en|english|eng)\.", "", d.split("/")[0])  # news.aniamey.com ~ aniamey.com
    _known = {_base(o[1]) for o in O.get(_iso, [])}
    O.setdefault(_iso, []).extend(o for o in _items if _base(o[1]) not in _known)
for _iso, _items in O.items():
    for _i, _o in enumerate(_items):
        _l = FIABILITE.get(f"{_iso}|{_o[1].split('/')[0]}")
        if _l and len(_o) < 5:
            _items[_i] = tuple(_o) + (("",) if len(_o) == 3 else ()) + (_l,)

if __name__ == "__main__":
    out = {"_comment": ("Médias de référence par pays, interrogés via Google News (site:). Généré par "
                        "tools/outlets_src.py – modifiez ce fichier-là puis relancez-le. Chaque entrée : "
                        "[nom, domaine, langue des mots-clés, '+' si le nom du pays doit être ajouté à la requête]."),
           "countries": {iso: [list(o) for o in items] for iso, items in sorted(O.items())}}
    dest = Path(__file__).resolve().parent.parent / "config" / "press_outlets.json"
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
    n = sum(len(v) for v in O.values())
    print(f"{len(O)} pays, {n} médias → {dest}")
